/*
 * App URI: sfa/보전/DPD200M0
 * Source Location: sfa/보전/DPD200M0.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("sfa/보전/DPD200M0", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * ${filename}
			 * Created at ${date} ${time}.
			 *
			 * @author ${user}
			 ************************************************/

			var count = 0;

			/*
			 * "다음" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var button = e.control;

				if (count == 0){
					app.openDialog("sfa/보전/CSBE00P1", {width : 1200, height : 550}, function(dialog){
				    dialog.ready(function(dialogApp){
				        // 필요한 경우, 다이얼로그의 앱이 초기화 된 후, 앱 속성을 전달하십시오.
				    });
					}).then(function(returnValue){
					    ;
					});			
				}else{
					var host = app.getHost(); // 부모 임베디드 앱
						cpr.core.App.load("sfa/보전/****", function(loadedApp) {
					    if (loadedApp) {
					        host.app = loadedApp;
					        host.initValue = {
					            "param": "param"
					        }
					    }
					});			
				}
			}

			/*
			 * "이전" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				var button = e.control;

				var host = app.getHost(); // 부모 임베디드 앱
					cpr.core.App.load("sfa/보전/DPD010M0", function(loadedApp) {
				    if (loadedApp) {
				        host.app = loadedApp;
				        host.initValue = {
				            "param": "param"
				        }
				    }
				});	
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "계약번호"},
					{"name": "피보험자"},
					{"name": "상품명"},
					{"name": "계약일자"},
					{"name": "계약상태"},
					{"name": "입금상태"},
					{"name": "납입방법"},
					{"name": "유지년월"},
					{"name": "유지회차"},
					{"name": "합계보험료"}
				],
				"rows": [
					{"계약번호": "1580449123", "피보험자": "김흥국", "상품명": "(무)흥국생명 온라인정기보험", "계약일자": "20210516", "계약상태": "정상", "입금상태": "정상", "납입방법": "카드납입", "유지년월": "202402", "유지회차": "70", "합계보험료": "32700"},
					{"계약번호": "1580449123", "피보험자": "김흥국", "상품명": "(무)흥국생명 온라인정기보험", "계약일자": "20210516", "계약상태": "정상", "입금상태": "정상", "납입방법": "카드납입", "유지년월": "202402", "유지회차": "70", "합계보험료": "32700"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("ds2");
			dataSet_2.parseData({
				"columns": [
					{"name": "소유자명"},
					{"name": "주민등록번호"},
					{"name": "카드사"},
					{"name": "카드번호"},
					{"name": "유효기간"},
					{"name": "관계"}
				],
				"rows": [{"소유자명": "김흥국", "주민등록번호": "620429-1234567", "카드사": "국민카드", "카드번호": "4092-1601-7261-****", "유효기간": "202508", "관계": "본인"}]
			});
			app.register(dataSet_2);
			
			var dataSet_3 = new cpr.data.DataSet("ds3");
			dataSet_3.parseData({
				"columns": [
					{"name": "구분"},
					{"name": "계약번호"},
					{"name": "카드사"},
					{"name": "카드번호"},
					{"name": "소유자명"},
					{"name": "주민등록번호"},
					{"name": "유효기간"},
					{"name": "게시월"},
					{"name": "신청일자"},
					{"name": "신청결과"},
					{"name": "할부개월수"}
				],
				"rows": [{"구분": "조회", "계약번호": "4801-1234-1245-****", "카드사": "국민카드", "카드번호": "4801-1234-1245-****", "소유자명": "김흥국", "주민등록번호": "672101-1******", "유효기간": "202508", "게시월": "202111", "신청일자": "20211113", "신청결과": "", "할부개월수": "0"}]
			});
			app.register(dataSet_3);
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["grid-window-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 0;
			verticalLayout_1.leftMargin = 20;
			verticalLayout_1.rightMargin = 20;
			verticalLayout_1.topMargin = 20;
			verticalLayout_1.bottomMargin = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpAppTitle");
			group_1.style.setClasses(["app-title"]);
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr", "1fr"]);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output("optTitle2");
				output_1.value = "카드이체신청";
				output_1.style.setClasses(["navi-left"]);
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_2 = new cpr.controls.Container("grpNavi2");
				group_2.style.setClasses(["breadcrumbs"]);
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 5;
				flowLayout_1.verticalSpacing = 0;
				flowLayout_1.horizontalAlign = "right";
				flowLayout_1.verticalAlign = "middle";
				flowLayout_1.lineWrap = false;
				group_2.setLayout(flowLayout_1);
				(function(container){
					var button_1 = new cpr.controls.Button();
					button_1.value = "이전";
					button_1.style.setClasses(["btn-primary04", "btn-md"]);
					if(typeof onButtonClick2 == "function") {
						button_1.addEventListener("click", onButtonClick2);
					}
					container.addChild(button_1, {
						"autoSize": "width",
						"width": "60px",
						"height": "30px"
					});
					var button_2 = new cpr.controls.Button();
					button_2.value = "다음";
					button_2.style.setClasses(["btn-primary04", "btn-md"]);
					if(typeof onButtonClick == "function") {
						button_2.addEventListener("click", onButtonClick);
					}
					container.addChild(button_2, {
						"autoSize": "width",
						"width": "60px",
						"height": "30px"
					});
				})(group_2);
				container.addChild(group_2, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1600px",
				"height": "35px"
			});
			
			var group_3 = new cpr.controls.Container("grpBody");
			group_3.style.setClasses(["grid-content-body"]);
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 7;
			group_3.setLayout(verticalLayout_2);
			(function(container){
				var group_4 = new cpr.controls.Container("grpTopSearch");
				var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_3.spacing = 12;
				group_4.setLayout(verticalLayout_3);
				(function(container){
					var group_5 = new cpr.controls.Container();
					group_5.style.setClasses(["search-box"]);
					var formLayout_2 = new cpr.controls.layouts.FormLayout();
					formLayout_2.scrollable = false;
					formLayout_2.topMargin = "6px";
					formLayout_2.rightMargin = "20px";
					formLayout_2.bottomMargin = "6px";
					formLayout_2.leftMargin = "20px";
					formLayout_2.horizontalSpacing = "20px";
					formLayout_2.verticalSpacing = "8px";
					formLayout_2.setColumns(["0px", "1fr", "0px", "1fr", "0px", "2fr", "63px"]);
					formLayout_2.setColumnAutoSizing(0, true);
					formLayout_2.setColumnAutoSizing(2, true);
					formLayout_2.setColumnAutoSizing(4, true);
					formLayout_2.setColumnAutoSizing(6, true);
					formLayout_2.setRows(["26px"]);
					group_5.setLayout(formLayout_2);
					(function(container){
						var output_2 = new cpr.controls.Output();
						output_2.value = "계약자";
						output_2.style.setClasses(["label", "required"]);
						container.addChild(output_2, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_6 = new cpr.controls.Container();
						group_6.style.setClasses(["form-inside"]);
						var formLayout_3 = new cpr.controls.layouts.FormLayout();
						formLayout_3.scrollable = false;
						formLayout_3.topMargin = "0px";
						formLayout_3.rightMargin = "0px";
						formLayout_3.bottomMargin = "0px";
						formLayout_3.leftMargin = "0px";
						formLayout_3.horizontalSpacing = "5px";
						formLayout_3.verticalSpacing = "5px";
						formLayout_3.setColumns(["1fr", "1fr"]);
						formLayout_3.setRows(["1fr"]);
						group_6.setLayout(formLayout_3);
						(function(container){
							var inputBox_1 = new cpr.controls.InputBox("ipb2");
							inputBox_1.value = "김흥국";
							container.addChild(inputBox_1, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var inputBox_2 = new cpr.controls.InputBox("ipb3");
							inputBox_2.value = "6204212-1******";
							inputBox_2.style.css({
								"border-right-style" : "dashed",
								"border-top-width" : "3px",
								"border-bottom-color" : "red",
								"border-left-style" : "dashed",
								"border-right-width" : "3px",
								"border-bottom-width" : "3px",
								"border-left-color" : "red",
								"border-top-color" : "red",
								"border-bottom-style" : "dashed",
								"border-right-color" : "red",
								"border-left-width" : "3px",
								"border-top-style" : "dashed"
							});
							container.addChild(inputBox_2, {
								"colIndex": 0,
								"rowIndex": 0
							});
						})(group_6);
						container.addChild(group_6, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var output_3 = new cpr.controls.Output();
						output_3.value = "계약번호";
						output_3.style.setClasses(["label", "required"]);
						container.addChild(output_3, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var searchInput_1 = new cpr.controls.SearchInput();
						searchInput_1.value = "";
						searchInput_1.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						container.addChild(searchInput_1, {
							"colIndex": 3,
							"rowIndex": 0
						});
						var group_7 = new cpr.controls.Container();
						group_7.style.setClasses(["btn-flow-area"]);
						var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
						flowLayout_2.scrollable = false;
						flowLayout_2.verticalSpacing = 0;
						flowLayout_2.horizontalAlign = "right";
						flowLayout_2.lineWrap = false;
						flowLayout_2.leftMargin = 20;
						group_7.setLayout(flowLayout_2);
						(function(container){
							var button_3 = new cpr.controls.Button();
							button_3.value = "조회";
							button_3.style.setClasses(["btn-search"]);
							container.addChild(button_3, {
								"width": "49px",
								"height": "26px"
							});
						})(group_7);
						container.addChild(group_7, {
							"colIndex": 6,
							"rowIndex": 0,
							"colSpan": 1,
							"rowSpan": 1,
							"verticalAlign": "center",
							"height": 26
						});
					})(group_5);
					container.addChild(group_5, {
						"autoSize": "none",
						"width": "4096px",
						"height": "40px"
					});
				})(group_4);
				container.addChild(group_4, {
					"autoSize": "height",
					"width": "4096px",
					"height": "40px"
				});
				var group_8 = new cpr.controls.Container();
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 8;
				group_8.setLayout(verticalLayout_4);
				(function(container){
					var group_9 = new cpr.controls.Container("grpBodyGroundGrid2");
					group_9.style.setClasses(["grid-box"]);
					var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_5.spacing = 8;
					group_9.setLayout(verticalLayout_5);
					(function(container){
						var grid_1 = new cpr.controls.Grid("grd1");
						grid_1.readOnly = true;
						grid_1.init({
							"dataSet": app.lookup("ds1"),
							"columnMovable": true,
							"autoFit": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10",
							"resizableColumns": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10",
							"columns": [
								{"width": "32px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "200px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnType = "checkbox";
											cell.filterable = false;
											cell.sortable = false;
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "계약번호";
											cell.text = "계약번호";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "피보험자";
											cell.text = "피보험자";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "상품명";
											cell.text = "상품명";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "계약일자";
											cell.text = "계약일자";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "계약상태";
											cell.text = "계약상태";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "입금상태";
											cell.text = "입금상태";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "납입방법";
											cell.text = "납입방법";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "유지년월";
											cell.text = "유지년월";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "유지회차";
											cell.text = "유지회차";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "합계보험료";
											cell.text = "합계보험료";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnType = "checkbox";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "계약번호";
											cell.control = (function(){
												var output_4 = new cpr.controls.Output();
												output_4.style.setClasses(["text-center"]);
												output_4.bind("value").toDataColumn("계약번호");
												return output_4;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "피보험자";
											cell.control = (function(){
												var output_5 = new cpr.controls.Output();
												output_5.style.setClasses(["text-center"]);
												output_5.bind("value").toDataColumn("피보험자");
												return output_5;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "상품명";
											cell.control = (function(){
												var output_6 = new cpr.controls.Output();
												output_6.bind("value").toDataColumn("상품명");
												return output_6;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "계약일자";
											cell.control = (function(){
												var output_7 = new cpr.controls.Output();
												output_7.dataType = "date";
												output_7.format = "YYYY-MM-DD";
												output_7.bind("value").toDataColumn("계약일자");
												return output_7;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "계약상태";
											cell.control = (function(){
												var output_8 = new cpr.controls.Output();
												output_8.style.setClasses(["text-center"]);
												output_8.bind("value").toDataColumn("계약상태");
												return output_8;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "입금상태";
											cell.control = (function(){
												var output_9 = new cpr.controls.Output();
												output_9.style.setClasses(["text-center"]);
												output_9.bind("value").toDataColumn("입금상태");
												return output_9;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.columnName = "납입방법";
											cell.control = (function(){
												var output_10 = new cpr.controls.Output();
												output_10.style.setClasses(["text-center"]);
												output_10.bind("value").toDataColumn("납입방법");
												return output_10;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.columnName = "유지년월";
											cell.control = (function(){
												var output_11 = new cpr.controls.Output();
												output_11.dataType = "date";
												output_11.format = "YYYY-MM-DD";
												output_11.bind("value").toDataColumn("유지년월");
												return output_11;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.columnName = "유지회차";
											cell.control = (function(){
												var numberEditor_1 = new cpr.controls.NumberEditor("nbe1");
												numberEditor_1.bind("value").toDataColumn("유지회차");
												return numberEditor_1;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.columnName = "합계보험료";
											cell.control = (function(){
												var output_12 = new cpr.controls.Output();
												output_12.value = "Output";
												output_12.dataType = "number";
												output_12.format = "s#,##0";
												output_12.style.setClasses(["text-right"]);
												output_12.bind("value").toDataColumn("합계보험료");
												return output_12;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							}
						});
						grid_1.style.setClasses(["list-normal"]);
						container.addChild(grid_1, {
							"autoSize": "none",
							"width": "1052px",
							"height": "127px"
						});
					})(group_9);
					container.addChild(group_9, {
						"autoSize": "height",
						"width": "1538px",
						"height": "142px"
					});
				})(group_8);
				container.addChild(group_8, {
					"autoSize": "height",
					"width": "1538px",
					"height": "152px"
				});
				var group_10 = new cpr.controls.Container();
				var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_6.spacing = 8;
				group_10.setLayout(verticalLayout_6);
				(function(container){
					var group_11 = new cpr.controls.Container("grpBodyGroundGrid");
					group_11.style.setClasses(["grid-box"]);
					var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_7.spacing = 8;
					group_11.setLayout(verticalLayout_7);
					(function(container){
						var group_12 = new cpr.controls.Container();
						group_12.style.setClasses(["button-table-area"]);
						var formLayout_4 = new cpr.controls.layouts.FormLayout();
						formLayout_4.scrollable = false;
						formLayout_4.topMargin = "0px";
						formLayout_4.rightMargin = "0px";
						formLayout_4.bottomMargin = "0px";
						formLayout_4.leftMargin = "0px";
						formLayout_4.horizontalSpacing = "0px";
						formLayout_4.verticalSpacing = "0px";
						formLayout_4.setColumns(["0px", "1fr"]);
						formLayout_4.setColumnAutoSizing(0, true);
						formLayout_4.setRows(["1fr"]);
						group_12.setLayout(formLayout_4);
						(function(container){
							var group_13 = new cpr.controls.Container();
							group_13.style.setClasses(["grid-title-box"]);
							var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
							verticalLayout_8.spacing = 0;
							group_13.setLayout(verticalLayout_8);
							(function(container){
								var output_13 = new cpr.controls.Output();
								output_13.value = "카드선택";
								output_13.style.setClasses(["grid-title"]);
								container.addChild(output_13, {
									"autoSize": "height",
									"width": "300px",
									"height": "26px"
								});
							})(group_13);
							container.addChild(group_13, {
								"colIndex": 0,
								"rowIndex": 0
							});
						})(group_12);
						container.addChild(group_12, {
							"autoSize": "height",
							"width": "1560px",
							"height": "26px"
						});
						var grid_2 = new cpr.controls.Grid("grd2");
						grid_2.readOnly = true;
						grid_2.init({
							"dataSet": app.lookup("ds2"),
							"columnMovable": true,
							"autoFit": "1, 2, 3, 4, 5, 6",
							"resizableColumns": "1, 2, 3, 4, 5, 6",
							"columns": [
								{"width": "32px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "소유자명";
											cell.text = "선택";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "소유자명";
											cell.text = "소유자명";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "주민등록번호";
											cell.text = "주민등록번호";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "카드사";
											cell.text = "카드사";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "카드번호";
											cell.text = "카드번호";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "유효기간";
											cell.text = "유효기간";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "관계";
											cell.text = "관계";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnType = "checkbox";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "소유자명";
											cell.control = (function(){
												var output_14 = new cpr.controls.Output();
												output_14.style.setClasses(["text-center"]);
												output_14.bind("value").toDataColumn("소유자명");
												return output_14;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "주민등록번호";
											cell.control = (function(){
												var output_15 = new cpr.controls.Output();
												output_15.format = "000000-0000000";
												output_15.style.setClasses(["text-center"]);
												output_15.bind("value").toDataColumn("주민등록번호");
												return output_15;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "카드사";
											cell.control = (function(){
												var output_16 = new cpr.controls.Output();
												output_16.style.setClasses(["text-center"]);
												output_16.bind("value").toDataColumn("카드사");
												return output_16;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "카드번호";
											cell.control = (function(){
												var output_17 = new cpr.controls.Output();
												output_17.format = "0000-0000-0000";
												output_17.style.setClasses(["text-center"]);
												output_17.bind("value").toDataColumn("카드번호");
												return output_17;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "유효기간";
											cell.control = (function(){
												var output_18 = new cpr.controls.Output();
												output_18.dataType = "date";
												output_18.format = "YYYY-MM";
												output_18.style.setClasses(["text-center"]);
												output_18.bind("value").toDataColumn("유효기간");
												return output_18;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "관계";
											cell.control = (function(){
												var output_19 = new cpr.controls.Output();
												output_19.style.setClasses(["text-center"]);
												output_19.bind("value").toDataColumn("관계");
												return output_19;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							}
						});
						grid_2.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						container.addChild(grid_2, {
							"autoSize": "none",
							"width": "1052px",
							"height": "74px"
						});
					})(group_11);
					container.addChild(group_11, {
						"autoSize": "height",
						"width": "1600px",
						"height": "127px"
					});
					var group_14 = new cpr.controls.Container("grp1");
					group_14.style.setClasses(["button-table-area"]);
					var formLayout_5 = new cpr.controls.layouts.FormLayout();
					formLayout_5.scrollable = false;
					formLayout_5.topMargin = "0px";
					formLayout_5.rightMargin = "0px";
					formLayout_5.bottomMargin = "0px";
					formLayout_5.leftMargin = "0px";
					formLayout_5.horizontalSpacing = "0px";
					formLayout_5.verticalSpacing = "0px";
					formLayout_5.setColumns(["1fr", "43px", "1fr"]);
					formLayout_5.setColumnAutoSizing(1, true);
					formLayout_5.setRows(["1fr"]);
					group_14.setLayout(formLayout_5);
					(function(container){
						var group_15 = new cpr.controls.Container("grp2");
						group_15.style.setClasses(["button-table-bottom-left-area"]);
						var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
						flowLayout_3.scrollable = false;
						flowLayout_3.horizontalSpacing = 10;
						flowLayout_3.verticalSpacing = 0;
						flowLayout_3.lineWrap = false;
						group_15.setLayout(flowLayout_3);
						container.addChild(group_15, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_16 = new cpr.controls.Container("grp3");
						group_16.style.setClasses(["button-table-bottom-center-area"]);
						var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
						flowLayout_4.scrollable = false;
						flowLayout_4.horizontalSpacing = 10;
						flowLayout_4.verticalSpacing = 0;
						flowLayout_4.horizontalAlign = "center";
						group_16.setLayout(flowLayout_4);
						container.addChild(group_16, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var group_17 = new cpr.controls.Container("grp4");
						group_17.style.setClasses(["button-table-bottom-right-area"]);
						var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
						flowLayout_5.scrollable = false;
						flowLayout_5.horizontalSpacing = 10;
						flowLayout_5.verticalSpacing = 0;
						flowLayout_5.horizontalAlign = "right";
						flowLayout_5.lineWrap = false;
						group_17.setLayout(flowLayout_5);
						(function(container){
							var button_4 = new cpr.controls.Button("btn1");
							button_4.value = "카드등록";
							button_4.style.setClasses(["btn-primary04"]);
							button_4.style.css({
								"border-right-style" : "dashed",
								"border-top-width" : "3px",
								"border-bottom-color" : "red",
								"border-left-style" : "dashed",
								"border-right-width" : "3px",
								"border-bottom-width" : "3px",
								"border-left-color" : "red",
								"border-top-color" : "red",
								"border-bottom-style" : "dashed",
								"border-right-color" : "red",
								"border-left-width" : "3px",
								"border-top-style" : "dashed"
							});
							container.addChild(button_4, {
								"autoSize": "width",
								"width": "60px",
								"height": "30px"
							});
						})(group_17);
						container.addChild(group_17, {
							"colIndex": 2,
							"rowIndex": 0
						});
					})(group_14);
					container.addChild(group_14, {
						"autoSize": "height",
						"width": "1560px",
						"height": "30px"
					});
				})(group_10);
				container.addChild(group_10, {
					"autoSize": "height",
					"width": "1538px",
					"height": "147px"
				});
				var group_18 = new cpr.controls.Container();
				group_18.style.setClasses(["form-box"]);
				var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_9.spacing = 8;
				group_18.setLayout(verticalLayout_9);
				(function(container){
					var group_19 = new cpr.controls.Container();
					var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_10.spacing = 8;
					group_19.setLayout(verticalLayout_10);
					(function(container){
						var group_20 = new cpr.controls.Container();
						group_20.style.setClasses(["form-normal"]);
						var formLayout_6 = new cpr.controls.layouts.FormLayout();
						formLayout_6.scrollable = false;
						formLayout_6.topMargin = "2px";
						formLayout_6.rightMargin = "5px";
						formLayout_6.bottomMargin = "2px";
						formLayout_6.leftMargin = "5px";
						formLayout_6.horizontalSpacing = "11px";
						formLayout_6.verticalSpacing = "5px";
						formLayout_6.horizontalSeparatorWidth = 1;
						formLayout_6.verticalSeparatorWidth = 1;
						formLayout_6.setColumns(["110px", "1fr"]);
						formLayout_6.setUseColumnShade(0, true);
						formLayout_6.setColumnAutoSizing(0, true);
						formLayout_6.setRows(["26px"]);
						formLayout_6.setRowAutoSizing(0, true);
						group_20.setLayout(formLayout_6);
						(function(container){
							var output_20 = new cpr.controls.Output();
							output_20.value = "신청구분";
							output_20.style.setClasses(["label"]);
							container.addChild(output_20, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var radioButton_1 = new cpr.controls.RadioButton("rdb2");
							radioButton_1.value = "value4";
							radioButton_1.style.css({
								"border-right-style" : "dashed",
								"border-top-width" : "3px",
								"border-bottom-color" : "red",
								"border-left-style" : "dashed",
								"border-right-width" : "3px",
								"border-bottom-width" : "3px",
								"border-left-color" : "red",
								"border-top-color" : "red",
								"border-bottom-style" : "dashed",
								"border-right-color" : "red",
								"border-left-width" : "3px",
								"border-top-style" : "dashed"
							});
							(function(radioButton_1){
								radioButton_1.addItem(new cpr.controls.Item("신청", "value1"));
								radioButton_1.addItem(new cpr.controls.Item("변경", "value2"));
								radioButton_1.addItem(new cpr.controls.Item("해지", "value3"));
							})(radioButton_1);
							container.addChild(radioButton_1, {
								"colIndex": 1,
								"rowIndex": 0,
								"colSpan": 1,
								"rowSpan": 1
							});
						})(group_20);
						container.addChild(group_20, {
							"autoSize": "height",
							"width": "1538px",
							"height": "33px"
						});
					})(group_19);
					container.addChild(group_19, {
						"autoSize": "height",
						"width": "1538px",
						"height": "33px"
					});
				})(group_18);
				container.addChild(group_18, {
					"autoSize": "height",
					"width": "1538px",
					"height": "38px"
				});
				var group_21 = new cpr.controls.Container();
				var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_11.spacing = 8;
				group_21.setLayout(verticalLayout_11);
				(function(container){
					var group_22 = new cpr.controls.Container("grpBodyGroundGrid3");
					group_22.style.setClasses(["grid-box"]);
					var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_12.spacing = 8;
					group_22.setLayout(verticalLayout_12);
					(function(container){
						var group_23 = new cpr.controls.Container();
						group_23.style.setClasses(["button-table-area"]);
						var formLayout_7 = new cpr.controls.layouts.FormLayout();
						formLayout_7.scrollable = false;
						formLayout_7.topMargin = "0px";
						formLayout_7.rightMargin = "0px";
						formLayout_7.bottomMargin = "0px";
						formLayout_7.leftMargin = "0px";
						formLayout_7.horizontalSpacing = "0px";
						formLayout_7.verticalSpacing = "0px";
						formLayout_7.setColumns(["0px", "1fr"]);
						formLayout_7.setColumnAutoSizing(0, true);
						formLayout_7.setRows(["1fr"]);
						group_23.setLayout(formLayout_7);
						(function(container){
							var group_24 = new cpr.controls.Container();
							group_24.style.setClasses(["grid-title-box"]);
							var verticalLayout_13 = new cpr.controls.layouts.VerticalLayout();
							verticalLayout_13.spacing = 0;
							group_24.setLayout(verticalLayout_13);
							(function(container){
								var output_21 = new cpr.controls.Output();
								output_21.value = "선택계약";
								output_21.style.setClasses(["grid-title"]);
								container.addChild(output_21, {
									"autoSize": "height",
									"width": "300px",
									"height": "26px"
								});
							})(group_24);
							container.addChild(group_24, {
								"colIndex": 0,
								"rowIndex": 0
							});
						})(group_23);
						container.addChild(group_23, {
							"autoSize": "height",
							"width": "1560px",
							"height": "26px"
						});
						var grid_3 = new cpr.controls.Grid("grd3");
						grid_3.init({
							"dataSet": app.lookup("ds3"),
							"columnMovable": true,
							"resizableColumns": "all",
							"columns": [
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "구분";
											cell.text = "구분";
											cell.style.css({
												"border-right-style" : "dashed",
												"border-top-width" : "3px",
												"border-bottom-color" : "red",
												"border-left-style" : "dashed",
												"border-right-width" : "3px",
												"border-bottom-width" : "3px",
												"border-left-color" : "red",
												"border-top-color" : "red",
												"border-bottom-style" : "dashed",
												"border-right-color" : "red",
												"border-left-width" : "3px",
												"border-top-style" : "dashed"
											});
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "계약번호";
											cell.text = "계약번호";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "카드사";
											cell.text = "카드사";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "카드번호";
											cell.text = "카드번호";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "소유자명";
											cell.text = "소유자명";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "주민등록번호";
											cell.text = "주민등록번호";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "유효기간";
											cell.text = "유효기간";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "게시월";
											cell.text = "게시월";
											cell.style.css({
												"border-right-style" : "dashed",
												"border-top-width" : "3px",
												"border-bottom-color" : "red",
												"border-left-style" : "dashed",
												"border-right-width" : "3px",
												"border-bottom-width" : "3px",
												"border-left-color" : "red",
												"border-top-color" : "red",
												"border-bottom-style" : "dashed",
												"border-right-color" : "red",
												"border-left-width" : "3px",
												"border-top-style" : "dashed"
											});
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "신청일자";
											cell.text = "신청일자";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "신청결과";
											cell.text = "신청결과";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "할부개월수";
											cell.text = "할부개월수";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnName = "구분";
											cell.control = (function(){
												var comboBox_1 = new cpr.controls.ComboBox("cmb1");
												comboBox_1.style.setClasses(["text-center"]);
												(function(comboBox_1){
													comboBox_1.addItem(new cpr.controls.Item("조회", "조회"));
												})(comboBox_1);
												comboBox_1.bind("value").toDataColumn("구분");
												return comboBox_1;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "계약번호";
											cell.control = (function(){
												var output_22 = new cpr.controls.Output();
												output_22.style.setClasses(["text-center"]);
												output_22.bind("value").toDataColumn("계약번호");
												return output_22;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "카드사";
											cell.control = (function(){
												var output_23 = new cpr.controls.Output();
												output_23.style.setClasses(["text-center"]);
												output_23.bind("value").toDataColumn("카드사");
												return output_23;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "카드번호";
											cell.control = (function(){
												var output_24 = new cpr.controls.Output();
												output_24.format = "0000-0000-0000";
												output_24.style.setClasses(["text-center"]);
												output_24.bind("value").toDataColumn("카드번호");
												return output_24;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "소유자명";
											cell.control = (function(){
												var output_25 = new cpr.controls.Output();
												output_25.style.setClasses(["text-center"]);
												output_25.bind("value").toDataColumn("소유자명");
												return output_25;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "주민등록번호";
											cell.control = (function(){
												var output_26 = new cpr.controls.Output();
												output_26.format = "000000-0000000";
												output_26.style.setClasses(["text-center"]);
												output_26.bind("value").toDataColumn("주민등록번호");
												return output_26;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "유효기간";
											cell.control = (function(){
												var output_27 = new cpr.controls.Output();
												output_27.dataType = "date";
												output_27.format = "YYYY-MM";
												output_27.bind("value").toDataColumn("유효기간");
												return output_27;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.columnName = "게시월";
											cell.control = (function(){
												var dateInput_1 = new cpr.controls.DateInput("dti1");
												dateInput_1.calendarType = "yearmonth";
												dateInput_1.mask = "YYYY-MM";
												dateInput_1.format = "YYYYMM";
												dateInput_1.bind("value").toDataColumn("게시월");
												return dateInput_1;
											})();
											cell.controlConstraint = {
												"horizontalAlign": "fill",
												"width": 120
											};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.columnName = "신청일자";
											cell.control = (function(){
												var output_28 = new cpr.controls.Output();
												output_28.dataType = "date";
												output_28.format = "YYYY-MM-DD";
												output_28.bind("value").toDataColumn("신청일자");
												return output_28;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.columnName = "신청결과";
											cell.control = (function(){
												var output_29 = new cpr.controls.Output();
												output_29.style.setClasses(["text-center"]);
												output_29.bind("value").toDataColumn("신청결과");
												return output_29;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.columnName = "할부개월수";
											cell.control = (function(){
												var output_30 = new cpr.controls.Output();
												output_30.style.setClasses(["text-center"]);
												output_30.bind("value").toDataColumn("할부개월수");
												return output_30;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							}
						});
						container.addChild(grid_3, {
							"autoSize": "none",
							"width": "1052px",
							"height": "114px"
						});
					})(group_22);
					container.addChild(group_22, {
						"autoSize": "height",
						"width": "1600px",
						"height": "165px"
					});
					var group_25 = new cpr.controls.Container();
					group_25.style.setClasses(["button-table-area"]);
					var formLayout_8 = new cpr.controls.layouts.FormLayout();
					formLayout_8.scrollable = false;
					formLayout_8.topMargin = "0px";
					formLayout_8.rightMargin = "0px";
					formLayout_8.bottomMargin = "0px";
					formLayout_8.leftMargin = "0px";
					formLayout_8.horizontalSpacing = "0px";
					formLayout_8.verticalSpacing = "0px";
					formLayout_8.setColumns(["1fr", "43px", "1fr"]);
					formLayout_8.setColumnAutoSizing(1, true);
					formLayout_8.setRows(["1fr"]);
					group_25.setLayout(formLayout_8);
					(function(container){
						var group_26 = new cpr.controls.Container();
						group_26.style.setClasses(["button-table-bottom-left-area"]);
						var flowLayout_6 = new cpr.controls.layouts.FlowLayout();
						flowLayout_6.scrollable = false;
						flowLayout_6.horizontalSpacing = 10;
						flowLayout_6.verticalSpacing = 0;
						flowLayout_6.lineWrap = false;
						group_26.setLayout(flowLayout_6);
						container.addChild(group_26, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_27 = new cpr.controls.Container();
						group_27.style.setClasses(["button-table-bottom-center-area"]);
						var flowLayout_7 = new cpr.controls.layouts.FlowLayout();
						flowLayout_7.scrollable = false;
						flowLayout_7.horizontalSpacing = 10;
						flowLayout_7.verticalSpacing = 0;
						flowLayout_7.horizontalAlign = "center";
						group_27.setLayout(flowLayout_7);
						container.addChild(group_27, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var group_28 = new cpr.controls.Container();
						group_28.style.setClasses(["button-table-bottom-right-area"]);
						var flowLayout_8 = new cpr.controls.layouts.FlowLayout();
						flowLayout_8.scrollable = false;
						flowLayout_8.horizontalSpacing = 10;
						flowLayout_8.verticalSpacing = 0;
						flowLayout_8.horizontalAlign = "right";
						flowLayout_8.lineWrap = false;
						group_28.setLayout(flowLayout_8);
						(function(container){
							var button_5 = new cpr.controls.Button();
							button_5.value = "반영";
							button_5.style.setClasses(["btn-primary03"]);
							container.addChild(button_5, {
								"autoSize": "width",
								"width": "60px",
								"height": "30px"
							});
						})(group_28);
						container.addChild(group_28, {
							"colIndex": 2,
							"rowIndex": 0
						});
					})(group_25);
					container.addChild(group_25, {
						"autoSize": "height",
						"width": "1600px",
						"height": "30px"
					});
				})(group_21);
				container.addChild(group_21, {
					"autoSize": "height",
					"width": "1538px",
					"height": "211px"
				});
			})(group_3);
			container.addChild(group_3, {
				"autoSize": "height",
				"width": "1560px",
				"height": "1332px"
			});
		}
	});
	app.title = "카드이체신청";
	cpr.core.Platform.INSTANCE.register(app);
})();
