/*
 * App URI: app/240304/UW032
 * Source Location: app/240304/UW032.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/240304/UW032", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * UW032.js
			 * Created at 2024. 2. 29. 오후 1:42:38.
			 *
			 * @author syj66
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"}
				],
				"rows": [
					{"column1": "체격 (신장)", "column2": "178", "column3": "(cm)", "column4": "", "column5": "체격 (체중)", "column6": "114", "column7": "(kg)", "column8": ""},
					{"column1": "복위", "column2": "118", "column3": "(cm)", "column4": "", "column5": "흉위", "column6": "116", "column7": "120(mmHG)", "column8": ""},
					{"column1": "BMI", "column2": "35.98", "column3": "18-30(mmHG)", "column4": "", "column5": "혈압1 (최고)", "column6": "125", "column7": "120(mmHG)", "column8": ""},
					{"column1": "혈압1 (최저)", "column2": "80", "column3": "80(mmHG)", "column4": "", "column5": "혈압2 (최고)", "column6": "130", "column7": "120(mmHG)", "column8": ""}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("ds2");
			dataSet_2.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"}
				]
			});
			app.register(dataSet_2);
			
			var dataSet_3 = new cpr.data.DataSet("ds3");
			dataSet_3.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"},
					{"name": "column12"},
					{"name": "column13"},
					{"name": "column14"},
					{"name": "column15"},
					{"name": "column16"}
				],
				"rows": [{"column1": "", "column2": "", "column3": "", "column4": "", "column5": "", "column6": "", "column7": "", "column8": "", "column9": "", "column10": "", "column11": "", "column12": "", "column13": "", "column14": "", "column15": "", "column16": ""}]
			});
			app.register(dataSet_3);
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["pop-content-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 15;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container();
				var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_3.spacing = 10;
				group_2.setLayout(verticalLayout_3);
				(function(container){
					var group_3 = new cpr.controls.Container();
					group_3.style.setClasses(["search-box"]);
					var formLayout_1 = new cpr.controls.layouts.FormLayout();
					formLayout_1.scrollable = false;
					formLayout_1.topMargin = "6px";
					formLayout_1.rightMargin = "20px";
					formLayout_1.bottomMargin = "6px";
					formLayout_1.leftMargin = "20px";
					formLayout_1.horizontalSpacing = "20px";
					formLayout_1.verticalSpacing = "8px";
					formLayout_1.setColumns(["0px", "2fr", "0px", "3fr", "0px", "1fr", "0px", "2fr", "63px"]);
					formLayout_1.setColumnAutoSizing(0, true);
					formLayout_1.setColumnAutoSizing(2, true);
					formLayout_1.setColumnAutoSizing(4, true);
					formLayout_1.setColumnAutoSizing(6, true);
					formLayout_1.setColumnAutoSizing(8, true);
					formLayout_1.setRows(["26px"]);
					group_3.setLayout(formLayout_1);
					(function(container){
						var output_1 = new cpr.controls.Output();
						output_1.value = "성명";
						output_1.style.setClasses(["label"]);
						container.addChild(output_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var inputBox_1 = new cpr.controls.InputBox("ipb1");
						inputBox_1.value = "이양우";
						container.addChild(inputBox_1, {
							"colIndex": 1,
							"rowIndex": 0,
							"horizontalAlign": "fill",
							"width": 120
						});
						var output_2 = new cpr.controls.Output();
						output_2.value = "주민번호";
						output_2.style.setClasses(["label"]);
						container.addChild(output_2, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var group_4 = new cpr.controls.Container("grp1");
						group_4.style.setClasses(["form-inside"]);
						var formLayout_2 = new cpr.controls.layouts.FormLayout();
						formLayout_2.scrollable = false;
						formLayout_2.topMargin = "0px";
						formLayout_2.rightMargin = "0px";
						formLayout_2.bottomMargin = "0px";
						formLayout_2.leftMargin = "0px";
						formLayout_2.horizontalSpacing = "0px";
						formLayout_2.verticalSpacing = "0px";
						formLayout_2.setColumns(["1fr", "10px", "1fr"]);
						formLayout_2.setRows(["1fr"]);
						group_4.setLayout(formLayout_2);
						(function(container){
							var inputBox_2 = new cpr.controls.InputBox("ipb3");
							inputBox_2.value = "670601";
							container.addChild(inputBox_2, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_3 = new cpr.controls.Output();
							output_3.value = "-";
							output_3.style.setClasses(["text-center"]);
							container.addChild(output_3, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var inputBox_3 = new cpr.controls.InputBox("ipb2");
							inputBox_3.value = "1228328";
							container.addChild(inputBox_3, {
								"colIndex": 2,
								"rowIndex": 0
							});
						})(group_4);
						container.addChild(group_4, {
							"colIndex": 3,
							"rowIndex": 0
						});
						var output_4 = new cpr.controls.Output();
						output_4.value = "보험연령";
						output_4.style.setClasses(["label"]);
						container.addChild(output_4, {
							"colIndex": 4,
							"rowIndex": 0
						});
						var group_5 = new cpr.controls.Container("grp2");
						group_5.style.setClasses(["form-inside"]);
						var formLayout_3 = new cpr.controls.layouts.FormLayout();
						formLayout_3.scrollable = false;
						formLayout_3.topMargin = "0px";
						formLayout_3.rightMargin = "0px";
						formLayout_3.bottomMargin = "0px";
						formLayout_3.leftMargin = "0px";
						formLayout_3.horizontalSpacing = "5px";
						formLayout_3.verticalSpacing = "5px";
						formLayout_3.setColumns(["1fr", "0px"]);
						formLayout_3.setColumnAutoSizing(1, true);
						formLayout_3.setRows(["1fr"]);
						group_5.setLayout(formLayout_3);
						(function(container){
							var inputBox_4 = new cpr.controls.InputBox("ipb4");
							inputBox_4.enabled = false;
							inputBox_4.value = "56";
							container.addChild(inputBox_4, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_5 = new cpr.controls.Output();
							output_5.value = "세";
							container.addChild(output_5, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_5);
						container.addChild(group_5, {
							"colIndex": 5,
							"rowIndex": 0
						});
						var output_6 = new cpr.controls.Output();
						output_6.value = "진단일자";
						output_6.style.setClasses(["label"]);
						container.addChild(output_6, {
							"colIndex": 6,
							"rowIndex": 0
						});
						var dateInput_1 = new cpr.controls.DateInput("dti1");
						container.addChild(dateInput_1, {
							"colIndex": 7,
							"rowIndex": 0,
							"horizontalAlign": "fill",
							"width": 120
						});
						var group_6 = new cpr.controls.Container("grp23");
						group_6.style.setClasses(["btn-flow-area"]);
						var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
						flowLayout_1.scrollable = false;
						flowLayout_1.verticalSpacing = 0;
						flowLayout_1.horizontalAlign = "right";
						flowLayout_1.lineWrap = false;
						flowLayout_1.leftMargin = 20;
						group_6.setLayout(flowLayout_1);
						(function(container){
							var button_1 = new cpr.controls.Button("btn4");
							button_1.value = "조회";
							button_1.style.setClasses(["btn-primary03"]);
							container.addChild(button_1, {
								"autoSize": "width",
								"width": "43px",
								"height": "26px"
							});
						})(group_6);
						container.addChild(group_6, {
							"colIndex": 8,
							"rowIndex": 0,
							"colSpan": 1,
							"rowSpan": 1,
							"verticalAlign": "center",
							"height": 26
						});
					})(group_3);
					container.addChild(group_3, {
						"autoSize": "height",
						"width": "729px",
						"height": "40px"
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "729px",
					"height": "42px"
				});
				var group_7 = new cpr.controls.Container();
				group_7.style.setClasses(["form-box", "box-spacing-free"]);
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 8;
				group_7.setLayout(verticalLayout_4);
				(function(container){
					var group_8 = new cpr.controls.Container("grp15");
					group_8.style.setClasses(["button-table-area"]);
					var formLayout_4 = new cpr.controls.layouts.FormLayout();
					formLayout_4.scrollable = false;
					formLayout_4.topMargin = "0px";
					formLayout_4.rightMargin = "0px";
					formLayout_4.bottomMargin = "0px";
					formLayout_4.leftMargin = "0px";
					formLayout_4.horizontalSpacing = "0px";
					formLayout_4.verticalSpacing = "0px";
					formLayout_4.setColumns(["0px", "1fr"]);
					formLayout_4.setColumnAutoSizing(0, true);
					formLayout_4.setRows(["1fr"]);
					group_8.setLayout(formLayout_4);
					(function(container){
						var group_9 = new cpr.controls.Container("grp16");
						group_9.style.setClasses(["form-title-box"]);
						var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
						group_9.setLayout(verticalLayout_5);
						(function(container){
							var output_7 = new cpr.controls.Output();
							output_7.style.setClasses(["form-title"]);
							container.addChild(output_7, {
								"autoSize": "height",
								"width": "300px",
								"height": "26px"
							});
						})(group_9);
						container.addChild(group_9, {
							"colIndex": 0,
							"rowIndex": 0,
							"colSpan": 1,
							"rowSpan": 1
						});
						var group_10 = new cpr.controls.Container("grp33");
						group_10.style.setClasses(["button-table-top-area"]);
						var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
						flowLayout_2.scrollable = false;
						flowLayout_2.horizontalSpacing = 5;
						flowLayout_2.verticalSpacing = 5;
						flowLayout_2.horizontalAlign = "right";
						flowLayout_2.lineWrap = false;
						group_10.setLayout(flowLayout_2);
						(function(container){
							var button_2 = new cpr.controls.Button("btn2");
							button_2.value = "입력";
							button_2.style.setClasses(["btn-secondary01"]);
							container.addChild(button_2, {
								"autoSize": "width",
								"width": "43px",
								"height": "26px"
							});
						})(group_10);
						container.addChild(group_10, {
							"colIndex": 1,
							"rowIndex": 0
						});
					})(group_8);
					container.addChild(group_8, {
						"autoSize": "height",
						"width": "1560px",
						"height": "26px"
					});
					var group_11 = new cpr.controls.Container("grp17");
					group_11.style.setClasses(["form-normal"]);
					var formLayout_5 = new cpr.controls.layouts.FormLayout();
					formLayout_5.scrollable = false;
					formLayout_5.topMargin = "2px";
					formLayout_5.rightMargin = "5px";
					formLayout_5.bottomMargin = "2px";
					formLayout_5.leftMargin = "5px";
					formLayout_5.horizontalSpacing = "11px";
					formLayout_5.verticalSpacing = "5px";
					formLayout_5.horizontalSeparatorWidth = 1;
					formLayout_5.verticalSeparatorWidth = 1;
					formLayout_5.setColumns(["80px", "1fr"]);
					formLayout_5.setUseColumnShade(0, true);
					formLayout_5.setColumnAutoSizing(0, true);
					formLayout_5.setRows(["26px"]);
					group_11.setLayout(formLayout_5);
					(function(container){
						var output_8 = new cpr.controls.Output();
						output_8.value = "";
						output_8.style.setClasses(["label"]);
						container.addChild(output_8, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_12 = new cpr.controls.Container("grp20");
						group_12.style.setClasses(["form-inside"]);
						var formLayout_6 = new cpr.controls.layouts.FormLayout();
						formLayout_6.scrollable = false;
						formLayout_6.topMargin = "0px";
						formLayout_6.rightMargin = "0px";
						formLayout_6.bottomMargin = "0px";
						formLayout_6.leftMargin = "0px";
						formLayout_6.horizontalSpacing = "5px";
						formLayout_6.verticalSpacing = "2px";
						formLayout_6.setColumns(["1fr", "1fr", "1fr", "1fr", "1fr", "1fr"]);
						formLayout_6.setRows(["1fr"]);
						group_12.setLayout(formLayout_6);
						(function(container){
							var inputBox_5 = new cpr.controls.InputBox("ipb9");
							inputBox_5.enabled = false;
							inputBox_5.value = "강남GA";
							container.addChild(inputBox_5, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var inputBox_6 = new cpr.controls.InputBox("ipb11");
							inputBox_6.enabled = false;
							inputBox_6.value = "메가_리치한국";
							container.addChild(inputBox_6, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var inputBox_7 = new cpr.controls.InputBox("ipb14");
							inputBox_7.enabled = false;
							inputBox_7.value = "임효민";
							container.addChild(inputBox_7, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var inputBox_8 = new cpr.controls.InputBox("ipb18");
							inputBox_8.enabled = false;
							inputBox_8.value = "(무)흥국생명치매담은다(多)사랑";
							container.addChild(inputBox_8, {
								"colIndex": 3,
								"rowIndex": 0
							});
							var inputBox_9 = new cpr.controls.InputBox("ipb15");
							inputBox_9.enabled = false;
							inputBox_9.value = "신계약";
							container.addChild(inputBox_9, {
								"colIndex": 4,
								"rowIndex": 0
							});
							var inputBox_10 = new cpr.controls.InputBox("ipb17");
							inputBox_10.enabled = false;
							inputBox_10.value = "차병원파라";
							container.addChild(inputBox_10, {
								"colIndex": 5,
								"rowIndex": 0
							});
						})(group_12);
						container.addChild(group_12, {
							"colIndex": 1,
							"rowIndex": 0
						});
					})(group_11);
					container.addChild(group_11, {
						"autoSize": "height",
						"width": "962px",
						"height": "33px"
					});
				})(group_7);
				container.addChild(group_7, {
					"autoSize": "height",
					"width": "962px",
					"height": "72px"
				});
				var group_13 = new cpr.controls.Container();
				var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_6.spacing = 8;
				group_13.setLayout(verticalLayout_6);
				(function(container){
					var group_14 = new cpr.controls.Container();
					group_14.style.setClasses(["grid-box"]);
					var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_7.spacing = 8;
					group_14.setLayout(verticalLayout_7);
					(function(container){
						var grid_1 = new cpr.controls.Grid("grd1");
						grid_1.init({
							"dataSet": app.lookup("ds1"),
							"columnMovable": true,
							"autoFit": "1, 2, 3, 4, 5, 6, 7, 8",
							"resizableColumns": "1, 2, 3, 4, 5, 6, 7, 8",
							"columns": [
								{
									"width": "48px",
									"visible": false
								},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.text = "NO";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column1";
											cell.text = "진단항목";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column2";
											cell.text = "결과";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column3";
											cell.text = "범위";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column4";
											cell.text = "소견";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column5";
											cell.text = "진단항목";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column6";
											cell.text = "결과";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column7";
											cell.text = "범위";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column8";
											cell.text = "소견";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnType = "rowindex";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "column1";
											cell.control = (function(){
												var output_9 = new cpr.controls.Output();
												output_9.value = "Output";
												output_9.bind("value").toDataColumn("column1");
												return output_9;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "column2";
											cell.control = (function(){
												var output_10 = new cpr.controls.Output();
												output_10.value = "Output";
												output_10.style.setClasses(["text-right"]);
												output_10.bind("value").toDataColumn("column2");
												return output_10;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "column3";
											cell.control = (function(){
												var output_11 = new cpr.controls.Output();
												output_11.value = "Output";
												output_11.style.setClasses(["text-right"]);
												output_11.bind("value").toDataColumn("column3");
												return output_11;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "column4";
											cell.control = (function(){
												var output_12 = new cpr.controls.Output();
												output_12.value = "Output";
												output_12.bind("value").toDataColumn("column4");
												return output_12;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "column5";
											cell.control = (function(){
												var output_13 = new cpr.controls.Output();
												output_13.value = "Output";
												output_13.bind("value").toDataColumn("column5");
												return output_13;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "column6";
											cell.control = (function(){
												var output_14 = new cpr.controls.Output();
												output_14.value = "Output";
												output_14.style.setClasses(["text-right"]);
												output_14.bind("value").toDataColumn("column6");
												return output_14;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.columnName = "column7";
											cell.control = (function(){
												var output_15 = new cpr.controls.Output();
												output_15.value = "Output";
												output_15.style.setClasses(["text-right"]);
												output_15.bind("value").toDataColumn("column7");
												return output_15;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.columnName = "column8";
											cell.control = (function(){
												var output_16 = new cpr.controls.Output();
												output_16.value = "Output";
												output_16.bind("value").toDataColumn("column8");
												return output_16;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							}
						});
						grid_1.style.setClasses(["list-normal"]);
						container.addChild(grid_1, {
							"width": "400px",
							"height": "219px"
						});
					})(group_14);
					container.addChild(group_14, {
						"autoSize": "height",
						"width": "1600px",
						"height": "244px"
					});
				})(group_13);
				container.addChild(group_13, {
					"autoSize": "height",
					"width": "767px",
					"height": "282px"
				});
				var group_15 = new cpr.controls.Container();
				var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_8.spacing = 8;
				group_15.setLayout(verticalLayout_8);
				(function(container){
					var group_16 = new cpr.controls.Container();
					group_16.style.setClasses(["grid-box", "box-spacing-free"]);
					var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_9.spacing = 8;
					group_16.setLayout(verticalLayout_9);
					(function(container){
						var grid_2 = new cpr.controls.Grid("grd2");
						grid_2.init({
							"dataSet": app.lookup("ds2"),
							"columnMovable": true,
							"autoFit": "1, 2, 3, 4, 5, 6, 7, 8",
							"resizableColumns": "1, 2, 3, 4, 5, 6, 7, 8",
							"columns": [
								{
									"width": "48px",
									"visible": false
								},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.text = "NO";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column1";
											cell.text = "구분";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column2";
											cell.text = "병력명";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column3";
											cell.text = "시작년월";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column4";
											cell.text = "종료년월";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column5";
											cell.text = "구분";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column6";
											cell.text = "병력명";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column7";
											cell.text = "시작년월";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column8";
											cell.text = "종료년월";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnType = "rowindex";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "column1";
											cell.control = (function(){
												var output_17 = new cpr.controls.Output();
												output_17.value = "Output";
												output_17.bind("value").toDataColumn("column1");
												return output_17;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "column2";
											cell.control = (function(){
												var output_18 = new cpr.controls.Output();
												output_18.value = "Output";
												output_18.bind("value").toDataColumn("column2");
												return output_18;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "column3";
											cell.control = (function(){
												var output_19 = new cpr.controls.Output();
												output_19.value = "Output";
												output_19.dataType = "date";
												output_19.format = "YYYY-MM-DD";
												output_19.style.setClasses(["text-center"]);
												output_19.bind("value").toDataColumn("column3");
												return output_19;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "column4";
											cell.control = (function(){
												var output_20 = new cpr.controls.Output();
												output_20.value = "Output";
												output_20.dataType = "date";
												output_20.format = "YYYY-MM-DD";
												output_20.style.setClasses(["text-center"]);
												output_20.bind("value").toDataColumn("column4");
												return output_20;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "column5";
											cell.control = (function(){
												var output_21 = new cpr.controls.Output();
												output_21.value = "Output";
												output_21.bind("value").toDataColumn("column5");
												return output_21;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "column6";
											cell.control = (function(){
												var output_22 = new cpr.controls.Output();
												output_22.value = "Output";
												output_22.bind("value").toDataColumn("column6");
												return output_22;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.columnName = "column7";
											cell.control = (function(){
												var output_23 = new cpr.controls.Output();
												output_23.value = "Output";
												output_23.dataType = "date";
												output_23.format = "YYYY-MM-DD";
												output_23.style.setClasses(["text-center"]);
												output_23.bind("value").toDataColumn("column7");
												return output_23;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.columnName = "column8";
											cell.control = (function(){
												var output_24 = new cpr.controls.Output();
												output_24.value = "Output";
												output_24.dataType = "date";
												output_24.format = "YYYY-MM-DD";
												output_24.style.setClasses(["text-center"]);
												output_24.bind("value").toDataColumn("column8");
												return output_24;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							}
						});
						grid_2.style.setClasses(["list-normal"]);
						container.addChild(grid_2, {
							"width": "400px",
							"height": "219px"
						});
					})(group_16);
					container.addChild(group_16, {
						"autoSize": "height",
						"width": "1600px",
						"height": "244px"
					});
				})(group_15);
				container.addChild(group_15, {
					"autoSize": "height",
					"width": "767px",
					"height": "282px"
				});
				var group_17 = new cpr.controls.Container("grp3");
				var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_10.spacing = 8;
				group_17.setLayout(verticalLayout_10);
				(function(container){
					var group_18 = new cpr.controls.Container("grp4");
					group_18.style.setClasses(["grid-box", "box-spacing-free"]);
					var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_11.spacing = 8;
					group_18.setLayout(verticalLayout_11);
					(function(container){
						var grid_3 = new cpr.controls.Grid("grd3");
						grid_3.init({
							"dataSet": app.lookup("ds3"),
							"columnMovable": true,
							"autoFit": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16",
							"resizableColumns": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16",
							"columns": [
								{
									"width": "48px",
									"visible": false
								},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.text = "NO";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column1";
											cell.text = "체격";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column2";
											cell.text = "혈압";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column3";
											cell.text = "맥박";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column4";
											cell.text = "소변";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column5";
											cell.text = "간기능";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column6";
											cell.text = "혈당";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column7";
											cell.text = "흉부X선";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column8";
											cell.text = "심전도";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column9";
											cell.text = "B형간염";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column10";
											cell.text = "전혈구";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 11},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column11";
											cell.text = "신장";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 12},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column12";
											cell.text = "지질";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 13},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column13";
											cell.text = "기왕증";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 14},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column14";
											cell.text = "현증";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 15},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column15";
											cell.text = "기타";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 16},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column16";
											cell.text = "합계";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnType = "rowindex";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "column1";
											cell.control = (function(){
												var output_25 = new cpr.controls.Output();
												output_25.value = "Output";
												output_25.bind("value").toDataColumn("column1");
												return output_25;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "column2";
											cell.control = (function(){
												var output_26 = new cpr.controls.Output();
												output_26.value = "Output";
												output_26.bind("value").toDataColumn("column2");
												return output_26;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "column3";
											cell.control = (function(){
												var output_27 = new cpr.controls.Output();
												output_27.value = "Output";
												output_27.bind("value").toDataColumn("column3");
												return output_27;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "column4";
											cell.control = (function(){
												var output_28 = new cpr.controls.Output();
												output_28.value = "Output";
												output_28.bind("value").toDataColumn("column4");
												return output_28;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "column5";
											cell.control = (function(){
												var output_29 = new cpr.controls.Output();
												output_29.value = "Output";
												output_29.bind("value").toDataColumn("column5");
												return output_29;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "column6";
											cell.control = (function(){
												var output_30 = new cpr.controls.Output();
												output_30.value = "Output";
												output_30.bind("value").toDataColumn("column6");
												return output_30;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.columnName = "column7";
											cell.control = (function(){
												var output_31 = new cpr.controls.Output();
												output_31.value = "Output";
												output_31.bind("value").toDataColumn("column7");
												return output_31;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.columnName = "column8";
											cell.control = (function(){
												var output_32 = new cpr.controls.Output();
												output_32.value = "Output";
												output_32.bind("value").toDataColumn("column8");
												return output_32;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.columnName = "column9";
											cell.control = (function(){
												var output_33 = new cpr.controls.Output();
												output_33.value = "Output";
												output_33.bind("value").toDataColumn("column9");
												return output_33;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.columnName = "column10";
											cell.control = (function(){
												var output_34 = new cpr.controls.Output();
												output_34.value = "Output";
												output_34.bind("value").toDataColumn("column10");
												return output_34;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 11},
										"configurator": function(cell){
											cell.columnName = "column11";
											cell.control = (function(){
												var output_35 = new cpr.controls.Output();
												output_35.value = "Output";
												output_35.bind("value").toDataColumn("column11");
												return output_35;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 12},
										"configurator": function(cell){
											cell.columnName = "column12";
											cell.control = (function(){
												var output_36 = new cpr.controls.Output();
												output_36.value = "Output";
												output_36.bind("value").toDataColumn("column12");
												return output_36;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 13},
										"configurator": function(cell){
											cell.columnName = "column13";
											cell.control = (function(){
												var output_37 = new cpr.controls.Output();
												output_37.value = "Output";
												output_37.bind("value").toDataColumn("column13");
												return output_37;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 14},
										"configurator": function(cell){
											cell.columnName = "column14";
											cell.control = (function(){
												var output_38 = new cpr.controls.Output();
												output_38.value = "Output";
												output_38.bind("value").toDataColumn("column14");
												return output_38;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 15},
										"configurator": function(cell){
											cell.columnName = "column15";
											cell.control = (function(){
												var output_39 = new cpr.controls.Output();
												output_39.value = "Output";
												output_39.bind("value").toDataColumn("column15");
												return output_39;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 16},
										"configurator": function(cell){
											cell.columnName = "column16";
											cell.control = (function(){
												var output_40 = new cpr.controls.Output();
												output_40.value = "Output";
												output_40.bind("value").toDataColumn("column16");
												return output_40;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							}
						});
						grid_3.style.setClasses(["list-normal"]);
						container.addChild(grid_3, {
							"width": "400px",
							"height": "219px"
						});
					})(group_18);
					container.addChild(group_18, {
						"autoSize": "height",
						"width": "1600px",
						"height": "244px"
					});
				})(group_17);
				container.addChild(group_17, {
					"autoSize": "height",
					"width": "729px",
					"height": "282px"
				});
				var group_19 = new cpr.controls.Container("grp5");
				group_19.style.setClasses(["form-box", "box-spacing-free"]);
				var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_12.spacing = 4;
				group_19.setLayout(verticalLayout_12);
				(function(container){
					var group_20 = new cpr.controls.Container("grp9");
					var verticalLayout_13 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_13.scrollable = false;
					verticalLayout_13.spacing = 8;
					group_20.setLayout(verticalLayout_13);
					(function(container){
						var group_21 = new cpr.controls.Container("grp18");
						group_21.style.setClasses(["form-normal"]);
						var formLayout_7 = new cpr.controls.layouts.FormLayout();
						formLayout_7.scrollable = false;
						formLayout_7.topMargin = "2px";
						formLayout_7.rightMargin = "5px";
						formLayout_7.bottomMargin = "2px";
						formLayout_7.leftMargin = "5px";
						formLayout_7.horizontalSpacing = "11px";
						formLayout_7.verticalSpacing = "5px";
						formLayout_7.horizontalSeparatorWidth = 1;
						formLayout_7.verticalSeparatorWidth = 1;
						formLayout_7.setColumns(["80px", "1fr", "80px", "1fr", "80px", "2fr"]);
						formLayout_7.setUseColumnShade(0, true);
						formLayout_7.setUseColumnShade(2, true);
						formLayout_7.setUseColumnShade(4, true);
						formLayout_7.setColumnAutoSizing(0, true);
						formLayout_7.setColumnAutoSizing(2, true);
						formLayout_7.setColumnAutoSizing(4, true);
						formLayout_7.setRows(["26px", "26px"]);
						group_21.setLayout(formLayout_7);
						(function(container){
							var output_41 = new cpr.controls.Output();
							output_41.value = "조정점수";
							output_41.style.setClasses(["label"]);
							container.addChild(output_41, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var group_22 = new cpr.controls.Container("grp21");
							group_22.style.setClasses(["form-inside"]);
							var formLayout_8 = new cpr.controls.layouts.FormLayout();
							formLayout_8.scrollable = false;
							formLayout_8.topMargin = "0px";
							formLayout_8.rightMargin = "0px";
							formLayout_8.bottomMargin = "0px";
							formLayout_8.leftMargin = "0px";
							formLayout_8.horizontalSpacing = "5px";
							formLayout_8.verticalSpacing = "2px";
							formLayout_8.setColumns(["80px", "1fr"]);
							formLayout_8.setRows(["1fr"]);
							group_22.setLayout(formLayout_8);
							(function(container){
								var numberEditor_1 = new cpr.controls.NumberEditor("nbe13");
								container.addChild(numberEditor_1, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var inputBox_11 = new cpr.controls.InputBox("ipb12");
								container.addChild(inputBox_11, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_22);
							container.addChild(group_22, {
								"colIndex": 1,
								"rowIndex": 0,
								"colSpan": 3,
								"rowSpan": 1
							});
							var output_42 = new cpr.controls.Output();
							output_42.value = "부담보";
							output_42.style.setClasses(["label"]);
							container.addChild(output_42, {
								"colIndex": 4,
								"rowIndex": 0
							});
							var group_23 = new cpr.controls.Container();
							var formLayout_9 = new cpr.controls.layouts.FormLayout();
							formLayout_9.scrollable = false;
							formLayout_9.horizontalSpacing = "20px";
							formLayout_9.verticalSpacing = "2px";
							formLayout_9.setColumns(["1fr", "1fr"]);
							formLayout_9.setRows(["1fr"]);
							group_23.setLayout(formLayout_9);
							(function(container){
								var group_24 = new cpr.controls.Container("grp19");
								group_24.style.setClasses(["form-inside"]);
								var formLayout_10 = new cpr.controls.layouts.FormLayout();
								formLayout_10.scrollable = false;
								formLayout_10.topMargin = "0px";
								formLayout_10.rightMargin = "0px";
								formLayout_10.bottomMargin = "0px";
								formLayout_10.leftMargin = "0px";
								formLayout_10.horizontalSpacing = "5px";
								formLayout_10.verticalSpacing = "2px";
								formLayout_10.setColumns(["2fr", "1fr"]);
								formLayout_10.setRows(["1fr"]);
								group_24.setLayout(formLayout_10);
								(function(container){
									var comboBox_1 = new cpr.controls.ComboBox("cmb3");
									(function(comboBox_1){
									})(comboBox_1);
									container.addChild(comboBox_1, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var comboBox_2 = new cpr.controls.ComboBox("cmb4");
									(function(comboBox_2){
									})(comboBox_2);
									container.addChild(comboBox_2, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_24);
								container.addChild(group_24, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var group_25 = new cpr.controls.Container("grp27");
								group_25.style.setClasses(["form-inside"]);
								var formLayout_11 = new cpr.controls.layouts.FormLayout();
								formLayout_11.scrollable = false;
								formLayout_11.topMargin = "0px";
								formLayout_11.rightMargin = "0px";
								formLayout_11.bottomMargin = "0px";
								formLayout_11.leftMargin = "0px";
								formLayout_11.horizontalSpacing = "5px";
								formLayout_11.verticalSpacing = "2px";
								formLayout_11.setColumns(["2fr", "1fr"]);
								formLayout_11.setRows(["1fr"]);
								group_25.setLayout(formLayout_11);
								(function(container){
									var comboBox_3 = new cpr.controls.ComboBox("cmb16");
									(function(comboBox_3){
									})(comboBox_3);
									container.addChild(comboBox_3, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var comboBox_4 = new cpr.controls.ComboBox("cmb17");
									(function(comboBox_4){
									})(comboBox_4);
									container.addChild(comboBox_4, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_25);
								container.addChild(group_25, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_23);
							container.addChild(group_23, {
								"colIndex": 5,
								"rowIndex": 0,
								"colSpan": 1,
								"rowSpan": 1
							});
							var output_43 = new cpr.controls.Output();
							output_43.value = "장애등급";
							output_43.style.setClasses(["label"]);
							container.addChild(output_43, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var group_26 = new cpr.controls.Container("grp22");
							group_26.style.setClasses(["form-inside"]);
							var formLayout_12 = new cpr.controls.layouts.FormLayout();
							formLayout_12.scrollable = false;
							formLayout_12.topMargin = "0px";
							formLayout_12.rightMargin = "0px";
							formLayout_12.bottomMargin = "0px";
							formLayout_12.leftMargin = "0px";
							formLayout_12.horizontalSpacing = "5px";
							formLayout_12.verticalSpacing = "2px";
							formLayout_12.setColumns(["1fr", "1fr"]);
							formLayout_12.setRows(["1fr"]);
							group_26.setLayout(formLayout_12);
							(function(container){
								var comboBox_5 = new cpr.controls.ComboBox("cmb11");
								(function(comboBox_5){
								})(comboBox_5);
								container.addChild(comboBox_5, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var inputBox_12 = new cpr.controls.InputBox("ipb13");
								container.addChild(inputBox_12, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_26);
							container.addChild(group_26, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_44 = new cpr.controls.Output();
							output_44.value = "보류";
							output_44.style.setClasses(["label"]);
							container.addChild(output_44, {
								"colIndex": 2,
								"rowIndex": 1
							});
							var comboBox_6 = new cpr.controls.ComboBox("cmb2");
							(function(comboBox_6){
							})(comboBox_6);
							container.addChild(comboBox_6, {
								"colIndex": 3,
								"rowIndex": 1,
								"horizontalAlign": "fill",
								"width": 60
							});
							var radioButton_1 = new cpr.controls.RadioButton("rdb3");
							radioButton_1.value = "value2";
							radioButton_1.style.setClasses(["label", "text-center"]);
							(function(radioButton_1){
								radioButton_1.addItem(new cpr.controls.Item("Y", "value1"));
								radioButton_1.addItem(new cpr.controls.Item("N", "value2"));
							})(radioButton_1);
							container.addChild(radioButton_1, {
								"colIndex": 4,
								"rowIndex": 1
							});
							var group_27 = new cpr.controls.Container();
							var formLayout_13 = new cpr.controls.layouts.FormLayout();
							formLayout_13.scrollable = false;
							formLayout_13.horizontalSpacing = "20px";
							formLayout_13.verticalSpacing = "2px";
							formLayout_13.setColumns(["1fr", "1fr"]);
							formLayout_13.setRows(["1fr"]);
							group_27.setLayout(formLayout_13);
							(function(container){
								var group_28 = new cpr.controls.Container("grp24");
								group_28.style.setClasses(["form-inside"]);
								var formLayout_14 = new cpr.controls.layouts.FormLayout();
								formLayout_14.scrollable = false;
								formLayout_14.topMargin = "0px";
								formLayout_14.rightMargin = "0px";
								formLayout_14.bottomMargin = "0px";
								formLayout_14.leftMargin = "0px";
								formLayout_14.horizontalSpacing = "5px";
								formLayout_14.verticalSpacing = "2px";
								formLayout_14.setColumns(["2fr", "1fr"]);
								formLayout_14.setRows(["1fr"]);
								group_28.setLayout(formLayout_14);
								(function(container){
									var comboBox_7 = new cpr.controls.ComboBox("cmb10");
									(function(comboBox_7){
									})(comboBox_7);
									container.addChild(comboBox_7, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var comboBox_8 = new cpr.controls.ComboBox("cmb12");
									(function(comboBox_8){
									})(comboBox_8);
									container.addChild(comboBox_8, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_28);
								container.addChild(group_28, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var group_29 = new cpr.controls.Container("grp25");
								group_29.style.setClasses(["form-inside"]);
								var formLayout_15 = new cpr.controls.layouts.FormLayout();
								formLayout_15.scrollable = false;
								formLayout_15.topMargin = "0px";
								formLayout_15.rightMargin = "0px";
								formLayout_15.bottomMargin = "0px";
								formLayout_15.leftMargin = "0px";
								formLayout_15.horizontalSpacing = "5px";
								formLayout_15.verticalSpacing = "2px";
								formLayout_15.setColumns(["2fr", "1fr"]);
								formLayout_15.setRows(["1fr"]);
								group_29.setLayout(formLayout_15);
								(function(container){
									var comboBox_9 = new cpr.controls.ComboBox("cmb13");
									(function(comboBox_9){
									})(comboBox_9);
									container.addChild(comboBox_9, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var comboBox_10 = new cpr.controls.ComboBox("cmb14");
									(function(comboBox_10){
									})(comboBox_10);
									container.addChild(comboBox_10, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_29);
								container.addChild(group_29, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_27);
							container.addChild(group_27, {
								"colIndex": 5,
								"rowIndex": 1,
								"colSpan": 1,
								"rowSpan": 1
							});
						})(group_21);
						container.addChild(group_21, {
							"autoSize": "height",
							"width": "1600px",
							"height": "64px"
						});
						var group_30 = new cpr.controls.Container("grp10");
						group_30.style.setClasses(["form-normal"]);
						var formLayout_16 = new cpr.controls.layouts.FormLayout();
						formLayout_16.scrollable = false;
						formLayout_16.topMargin = "2px";
						formLayout_16.rightMargin = "5px";
						formLayout_16.bottomMargin = "2px";
						formLayout_16.leftMargin = "5px";
						formLayout_16.horizontalSpacing = "11px";
						formLayout_16.verticalSpacing = "5px";
						formLayout_16.horizontalSeparatorWidth = 1;
						formLayout_16.verticalSeparatorWidth = 1;
						formLayout_16.setColumns(["80px", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "80px", "1fr"]);
						formLayout_16.setUseColumnShade(0, true);
						formLayout_16.setUseColumnShade(7, true);
						formLayout_16.setColumnAutoSizing(0, true);
						formLayout_16.setColumnAutoSizing(7, true);
						formLayout_16.setRows(["26px", "26px", "26px"]);
						formLayout_16.setUseRowShade(0, true);
						group_30.setLayout(formLayout_16);
						(function(container){
							var output_45 = new cpr.controls.Output();
							output_45.value = "심사구분";
							output_45.style.setClasses(["label"]);
							container.addChild(output_45, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_46 = new cpr.controls.Output();
							output_46.value = "LTC";
							output_46.style.setClasses(["label"]);
							container.addChild(output_46, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_47 = new cpr.controls.Output();
							output_47.value = "CI";
							output_47.style.setClasses(["label"]);
							container.addChild(output_47, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var output_48 = new cpr.controls.Output();
							output_48.value = "건강";
							output_48.style.setClasses(["label"]);
							container.addChild(output_48, {
								"colIndex": 3,
								"rowIndex": 0
							});
							var output_49 = new cpr.controls.Output();
							output_49.value = "기타";
							output_49.style.setClasses(["label"]);
							container.addChild(output_49, {
								"colIndex": 4,
								"rowIndex": 0
							});
							var output_50 = new cpr.controls.Output();
							output_50.value = "암";
							output_50.style.setClasses(["label"]);
							container.addChild(output_50, {
								"colIndex": 5,
								"rowIndex": 0
							});
							var output_51 = new cpr.controls.Output();
							output_51.value = "###";
							output_51.style.setClasses(["label"]);
							container.addChild(output_51, {
								"colIndex": 6,
								"rowIndex": 0
							});
							var output_52 = new cpr.controls.Output();
							output_52.value = "처리자";
							output_52.style.setClasses(["label"]);
							container.addChild(output_52, {
								"colIndex": 7,
								"rowIndex": 0
							});
							var inputBox_13 = new cpr.controls.InputBox("ipb5");
							inputBox_13.enabled = false;
							inputBox_13.value = "74010";
							container.addChild(inputBox_13, {
								"colIndex": 8,
								"rowIndex": 0,
								"horizontalAlign": "fill",
								"width": 80
							});
							var output_53 = new cpr.controls.Output();
							output_53.value = "심사지수";
							output_53.style.setClasses(["label"]);
							container.addChild(output_53, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var group_31 = new cpr.controls.Container("grp7");
							group_31.style.setClasses(["form-inside"]);
							var formLayout_17 = new cpr.controls.layouts.FormLayout();
							formLayout_17.scrollable = false;
							formLayout_17.topMargin = "0px";
							formLayout_17.rightMargin = "0px";
							formLayout_17.bottomMargin = "0px";
							formLayout_17.leftMargin = "0px";
							formLayout_17.horizontalSpacing = "5px";
							formLayout_17.verticalSpacing = "2px";
							formLayout_17.setColumns(["1fr", "1fr"]);
							formLayout_17.setRows(["1fr"]);
							group_31.setLayout(formLayout_17);
							(function(container){
								var numberEditor_2 = new cpr.controls.NumberEditor("nbe1");
								container.addChild(numberEditor_2, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var numberEditor_3 = new cpr.controls.NumberEditor("nbe2");
								container.addChild(numberEditor_3, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_31);
							container.addChild(group_31, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var group_32 = new cpr.controls.Container("grp11");
							group_32.style.setClasses(["form-inside"]);
							var formLayout_18 = new cpr.controls.layouts.FormLayout();
							formLayout_18.scrollable = false;
							formLayout_18.topMargin = "0px";
							formLayout_18.rightMargin = "0px";
							formLayout_18.bottomMargin = "0px";
							formLayout_18.leftMargin = "0px";
							formLayout_18.horizontalSpacing = "5px";
							formLayout_18.verticalSpacing = "2px";
							formLayout_18.setColumns(["1fr", "1fr"]);
							formLayout_18.setRows(["1fr"]);
							group_32.setLayout(formLayout_18);
							(function(container){
								var numberEditor_4 = new cpr.controls.NumberEditor("nbe3");
								container.addChild(numberEditor_4, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var numberEditor_5 = new cpr.controls.NumberEditor("nbe4");
								container.addChild(numberEditor_5, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_32);
							container.addChild(group_32, {
								"colIndex": 2,
								"rowIndex": 1
							});
							var group_33 = new cpr.controls.Container("grp8");
							group_33.style.setClasses(["form-inside"]);
							var formLayout_19 = new cpr.controls.layouts.FormLayout();
							formLayout_19.scrollable = false;
							formLayout_19.topMargin = "0px";
							formLayout_19.rightMargin = "0px";
							formLayout_19.bottomMargin = "0px";
							formLayout_19.leftMargin = "0px";
							formLayout_19.horizontalSpacing = "5px";
							formLayout_19.verticalSpacing = "2px";
							formLayout_19.setColumns(["1fr", "1fr"]);
							formLayout_19.setRows(["1fr"]);
							group_33.setLayout(formLayout_19);
							(function(container){
								var numberEditor_6 = new cpr.controls.NumberEditor("nbe5");
								container.addChild(numberEditor_6, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var numberEditor_7 = new cpr.controls.NumberEditor("nbe6");
								container.addChild(numberEditor_7, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_33);
							container.addChild(group_33, {
								"colIndex": 3,
								"rowIndex": 1
							});
							var group_34 = new cpr.controls.Container("grp13");
							group_34.style.setClasses(["form-inside"]);
							var formLayout_20 = new cpr.controls.layouts.FormLayout();
							formLayout_20.scrollable = false;
							formLayout_20.topMargin = "0px";
							formLayout_20.rightMargin = "0px";
							formLayout_20.bottomMargin = "0px";
							formLayout_20.leftMargin = "0px";
							formLayout_20.horizontalSpacing = "5px";
							formLayout_20.verticalSpacing = "2px";
							formLayout_20.setColumns(["1fr", "1fr"]);
							formLayout_20.setRows(["1fr"]);
							group_34.setLayout(formLayout_20);
							(function(container){
								var numberEditor_8 = new cpr.controls.NumberEditor("nbe9");
								container.addChild(numberEditor_8, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var numberEditor_9 = new cpr.controls.NumberEditor("nbe10");
								container.addChild(numberEditor_9, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_34);
							container.addChild(group_34, {
								"colIndex": 4,
								"rowIndex": 1
							});
							var group_35 = new cpr.controls.Container("grp12");
							group_35.style.setClasses(["form-inside"]);
							var formLayout_21 = new cpr.controls.layouts.FormLayout();
							formLayout_21.scrollable = false;
							formLayout_21.topMargin = "0px";
							formLayout_21.rightMargin = "0px";
							formLayout_21.bottomMargin = "0px";
							formLayout_21.leftMargin = "0px";
							formLayout_21.horizontalSpacing = "5px";
							formLayout_21.verticalSpacing = "2px";
							formLayout_21.setColumns(["1fr", "1fr"]);
							formLayout_21.setRows(["1fr"]);
							group_35.setLayout(formLayout_21);
							(function(container){
								var numberEditor_10 = new cpr.controls.NumberEditor("nbe7");
								container.addChild(numberEditor_10, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var numberEditor_11 = new cpr.controls.NumberEditor("nbe8");
								container.addChild(numberEditor_11, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_35);
							container.addChild(group_35, {
								"colIndex": 5,
								"rowIndex": 1
							});
							var group_36 = new cpr.controls.Container("grp14");
							group_36.style.setClasses(["form-inside"]);
							var formLayout_22 = new cpr.controls.layouts.FormLayout();
							formLayout_22.scrollable = false;
							formLayout_22.topMargin = "0px";
							formLayout_22.rightMargin = "0px";
							formLayout_22.bottomMargin = "0px";
							formLayout_22.leftMargin = "0px";
							formLayout_22.horizontalSpacing = "5px";
							formLayout_22.verticalSpacing = "2px";
							formLayout_22.setColumns(["1fr", "1fr"]);
							formLayout_22.setRows(["1fr"]);
							group_36.setLayout(formLayout_22);
							(function(container){
								var numberEditor_12 = new cpr.controls.NumberEditor("nbe11");
								container.addChild(numberEditor_12, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var numberEditor_13 = new cpr.controls.NumberEditor("nbe12");
								container.addChild(numberEditor_13, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_36);
							container.addChild(group_36, {
								"colIndex": 6,
								"rowIndex": 1
							});
							var output_54 = new cpr.controls.Output();
							output_54.value = "심사자";
							output_54.style.setClasses(["label"]);
							container.addChild(output_54, {
								"colIndex": 7,
								"rowIndex": 1
							});
							var inputBox_14 = new cpr.controls.InputBox("ipb10");
							inputBox_14.enabled = false;
							inputBox_14.value = "74010";
							container.addChild(inputBox_14, {
								"colIndex": 8,
								"rowIndex": 1,
								"horizontalAlign": "fill",
								"width": 80
							});
							var output_55 = new cpr.controls.Output();
							output_55.value = "심사결과";
							output_55.style.setClasses(["label"]);
							container.addChild(output_55, {
								"colIndex": 0,
								"rowIndex": 2
							});
							var comboBox_11 = new cpr.controls.ComboBox("cmb1");
							(function(comboBox_11){
							})(comboBox_11);
							container.addChild(comboBox_11, {
								"colIndex": 1,
								"rowIndex": 2,
								"horizontalAlign": "fill",
								"width": 80
							});
							var comboBox_12 = new cpr.controls.ComboBox("cmb5");
							(function(comboBox_12){
							})(comboBox_12);
							container.addChild(comboBox_12, {
								"colIndex": 2,
								"rowIndex": 2,
								"horizontalAlign": "fill",
								"width": 60
							});
							var comboBox_13 = new cpr.controls.ComboBox("cmb6");
							(function(comboBox_13){
							})(comboBox_13);
							container.addChild(comboBox_13, {
								"colIndex": 3,
								"rowIndex": 2,
								"horizontalAlign": "fill",
								"width": 60
							});
							var comboBox_14 = new cpr.controls.ComboBox("cmb7");
							(function(comboBox_14){
							})(comboBox_14);
							container.addChild(comboBox_14, {
								"colIndex": 4,
								"rowIndex": 2,
								"horizontalAlign": "fill",
								"width": 60
							});
							var comboBox_15 = new cpr.controls.ComboBox("cmb8");
							(function(comboBox_15){
							})(comboBox_15);
							container.addChild(comboBox_15, {
								"colIndex": 5,
								"rowIndex": 2,
								"horizontalAlign": "fill",
								"width": 60
							});
							var comboBox_16 = new cpr.controls.ComboBox("cmb9");
							(function(comboBox_16){
							})(comboBox_16);
							container.addChild(comboBox_16, {
								"colIndex": 6,
								"rowIndex": 2,
								"horizontalAlign": "fill",
								"width": 60
							});
							var output_56 = new cpr.controls.Output();
							output_56.value = "심사일자";
							output_56.style.setClasses(["label"]);
							container.addChild(output_56, {
								"colIndex": 7,
								"rowIndex": 2
							});
							var inputBox_15 = new cpr.controls.InputBox("ipb6");
							inputBox_15.enabled = false;
							inputBox_15.value = "74010";
							container.addChild(inputBox_15, {
								"colIndex": 8,
								"rowIndex": 2,
								"horizontalAlign": "fill",
								"width": 80
							});
						})(group_30);
						container.addChild(group_30, {
							"autoSize": "height",
							"width": "729px",
							"height": "95px"
						});
						var group_37 = new cpr.controls.Container("grp6");
						group_37.style.setClasses(["form-normal"]);
						var formLayout_23 = new cpr.controls.layouts.FormLayout();
						formLayout_23.scrollable = false;
						formLayout_23.topMargin = "2px";
						formLayout_23.rightMargin = "5px";
						formLayout_23.bottomMargin = "2px";
						formLayout_23.leftMargin = "5px";
						formLayout_23.horizontalSpacing = "11px";
						formLayout_23.verticalSpacing = "5px";
						formLayout_23.horizontalSeparatorWidth = 1;
						formLayout_23.verticalSeparatorWidth = 1;
						formLayout_23.setColumns(["80px", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "80px", "1fr"]);
						formLayout_23.setUseColumnShade(0, true);
						formLayout_23.setUseColumnShade(7, true);
						formLayout_23.setColumnAutoSizing(0, true);
						formLayout_23.setColumnAutoSizing(7, true);
						formLayout_23.setRows(["26px"]);
						group_37.setLayout(formLayout_23);
						(function(container){
							var output_57 = new cpr.controls.Output();
							output_57.value = "심사의견";
							output_57.style.setClasses(["label"]);
							container.addChild(output_57, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var inputBox_16 = new cpr.controls.InputBox("ipb7");
							container.addChild(inputBox_16, {
								"colIndex": 1,
								"rowIndex": 0,
								"colSpan": 6,
								"rowSpan": 1
							});
							var output_58 = new cpr.controls.Output();
							output_58.value = "수수료";
							output_58.style.setClasses(["label"]);
							container.addChild(output_58, {
								"colIndex": 7,
								"rowIndex": 0
							});
							var inputBox_17 = new cpr.controls.InputBox("ipb8");
							inputBox_17.enabled = false;
							inputBox_17.value = "74010";
							container.addChild(inputBox_17, {
								"colIndex": 8,
								"rowIndex": 0,
								"horizontalAlign": "fill",
								"width": 80
							});
						})(group_37);
						container.addChild(group_37, {
							"autoSize": "height",
							"width": "729px",
							"height": "33px"
						});
					})(group_20);
					container.addChild(group_20, {
						"autoSize": "height",
						"width": "729px",
						"height": "208px"
					});
				})(group_19);
				container.addChild(group_19, {
					"autoSize": "height",
					"width": "729px",
					"height": "238px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "962px",
				"height": "1265px"
			});
			
			var group_38 = new cpr.controls.Container("grp29");
			group_38.style.setClasses(["button-table-area"]);
			var formLayout_24 = new cpr.controls.layouts.FormLayout();
			formLayout_24.scrollable = false;
			formLayout_24.topMargin = "0px";
			formLayout_24.rightMargin = "0px";
			formLayout_24.bottomMargin = "0px";
			formLayout_24.leftMargin = "0px";
			formLayout_24.horizontalSpacing = "0px";
			formLayout_24.verticalSpacing = "0px";
			formLayout_24.setColumns(["1fr", "43px", "1fr"]);
			formLayout_24.setColumnAutoSizing(1, true);
			formLayout_24.setRows(["1fr"]);
			group_38.setLayout(formLayout_24);
			(function(container){
				var group_39 = new cpr.controls.Container("grp30");
				group_39.style.setClasses(["button-table-bottom-left-area"]);
				var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
				flowLayout_3.scrollable = false;
				flowLayout_3.horizontalSpacing = 10;
				flowLayout_3.verticalSpacing = 0;
				flowLayout_3.lineWrap = false;
				group_39.setLayout(flowLayout_3);
				(function(container){
					var button_3 = new cpr.controls.Button("btn3");
					button_3.value = "진단서";
					button_3.style.setClasses(["btn-primary02", "btn-md"]);
					container.addChild(button_3, {
						"autoSize": "width",
						"width": "60px",
						"height": "30px"
					});
				})(group_39);
				container.addChild(group_39, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_40 = new cpr.controls.Container("grp31");
				group_40.style.setClasses(["button-table-bottom-center-area"]);
				var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
				flowLayout_4.scrollable = false;
				flowLayout_4.horizontalSpacing = 10;
				flowLayout_4.verticalSpacing = 0;
				flowLayout_4.horizontalAlign = "center";
				group_40.setLayout(flowLayout_4);
				(function(container){
					var button_4 = new cpr.controls.Button("btn5");
					button_4.value = "닫기";
					button_4.style.setClasses(["btn-primary04", "btn-md"]);
					container.addChild(button_4, {
						"autoSize": "width",
						"width": "43px",
						"height": "30px"
					});
				})(group_40);
				container.addChild(group_40, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var group_41 = new cpr.controls.Container("grp32");
				group_41.style.setClasses(["button-table-bottom-right-area"]);
				var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
				flowLayout_5.scrollable = false;
				flowLayout_5.horizontalSpacing = 10;
				flowLayout_5.verticalSpacing = 0;
				flowLayout_5.horizontalAlign = "right";
				flowLayout_5.lineWrap = false;
				group_41.setLayout(flowLayout_5);
				(function(container){
					var button_5 = new cpr.controls.Button("btn8");
					button_5.value = "안내장발행";
					button_5.style.setClasses(["btn-secondary01", "btn-md"]);
					container.addChild(button_5, {
						"autoSize": "width",
						"width": "74px",
						"height": "30px"
					});
				})(group_41);
				container.addChild(group_41, {
					"colIndex": 2,
					"rowIndex": 0
				});
			})(group_38);
			container.addChild(group_38, {
				"autoSize": "height",
				"width": "729px",
				"height": "30px"
			});
		}
	});
	app.title = "진단결과";
	cpr.core.Platform.INSTANCE.register(app);
})();
