/*
 * App URI: sfa/신계약+UW/NBCM10M2
 * Source Location: sfa/신계약+UW/NBCM10M2.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("sfa/신계약+UW/NBCM10M2", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * NBCM10M2.js
			 * Created at 2024. 4. 5. 오전 9:31:07.
			 *
			 * @author chwec
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "보장내용"},
					{"name": "보장금액"}
				],
				"rows": [
					{"보장내용": "\u203b이 보험은 무배당 상품으로서 배당을 하지 않습니다."},
					{"보장내용": "[주 계 약 - 1형 일시형]"},
					{"보장내용": "● 사망보험금"},
					{"보장내용": "-피보험자(보험대상자)가 보험기간 중 사망하거나 장해분류표 중 동일한", "보장금액": "150000000"},
					{"보장내용": "재해 또는 재해이외의 동일한 원인으로 여러 신체부위의 장해지급률을"},
					{"보장내용": "더하여, 80% 이상인 장해상태가 되었을 때"},
					{"보장내용": "주)1. 보험료 납입기간 중 피보험자(보험대상자)가 장해분류표 중 동일"},
					{"보장내용": "한 재해 또는 재해이외의 동일한 원인으로 여러 신체부위의 장해"},
					{"보장내용": "지급률을 더하여 50%이상 80%미만인 장해상태가 되었을 경우"},
					{"보장내용": "에는 차회 이후의 보험료 납입을 면제하여 드립니다. 다만 새로이"},
					{"보장내용": "갱신되는 계약에서는 갱신 전 보험사고로 인한 보험료 납입면제를"},
					{"보장내용": "적용하지 아니하고 보험료를 계속 납입하여야 합니다."},
					{"보장내용": "2. 피보험자(보험대상자)가 사망하거나 장해분류표 중 동일한 재해"},
					{"보장내용": "또는 재해 이외의 동일한 원인으로 여러 신체부위의 장해지급률을"},
					{"보장내용": "더하여 80% 이상인 장해상태가 되었을 경우에는 이 계약은 그때"},
					{"보장내용": "부터 효력을 가지지 아니합니다."},
					{"보장내용": "3. 주보험 및 갱신 특약의 최종 갱신 후 계약의 보험기간은 80세까지"},
					{"보장내용": "입니다."}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["pop-content-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 15;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("grpTopSearch");
				var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_3.spacing = 10;
				group_2.setLayout(verticalLayout_3);
				(function(container){
					var group_3 = new cpr.controls.Container();
					group_3.style.setClasses(["search-box"]);
					var formLayout_1 = new cpr.controls.layouts.FormLayout();
					formLayout_1.scrollable = false;
					formLayout_1.topMargin = "6px";
					formLayout_1.rightMargin = "20px";
					formLayout_1.bottomMargin = "6px";
					formLayout_1.leftMargin = "20px";
					formLayout_1.horizontalSpacing = "20px";
					formLayout_1.verticalSpacing = "8px";
					formLayout_1.setColumns(["0px", "1fr", "0px", "2fr", "63px"]);
					formLayout_1.setColumnAutoSizing(0, true);
					formLayout_1.setColumnAutoSizing(2, true);
					formLayout_1.setColumnAutoSizing(4, true);
					formLayout_1.setRows(["26px"]);
					group_3.setLayout(formLayout_1);
					(function(container){
						var output_1 = new cpr.controls.Output();
						output_1.value = "계약번호";
						output_1.style.setClasses(["label", "required"]);
						container.addChild(output_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var output_2 = new cpr.controls.Output();
						output_2.value = "상품명";
						output_2.style.setClasses(["label"]);
						container.addChild(output_2, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var group_4 = new cpr.controls.Container();
						group_4.style.setClasses(["btn-flow-area"]);
						var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
						flowLayout_1.scrollable = false;
						flowLayout_1.verticalSpacing = 0;
						flowLayout_1.horizontalAlign = "right";
						flowLayout_1.lineWrap = false;
						flowLayout_1.leftMargin = 20;
						group_4.setLayout(flowLayout_1);
						(function(container){
							var button_1 = new cpr.controls.Button();
							button_1.value = "조회";
							button_1.style.setClasses(["btn-primary03"]);
							container.addChild(button_1, {
								"autoSize": "width",
								"width": "43px",
								"height": "26px"
							});
						})(group_4);
						container.addChild(group_4, {
							"colIndex": 4,
							"rowIndex": 0,
							"colSpan": 1,
							"rowSpan": 1,
							"verticalAlign": "center",
							"height": 26
						});
						var group_5 = new cpr.controls.Container();
						group_5.style.setClasses(["form-inside"]);
						var formLayout_2 = new cpr.controls.layouts.FormLayout();
						formLayout_2.scrollable = false;
						formLayout_2.horizontalSpacing = "5px";
						formLayout_2.verticalSpacing = "2px";
						formLayout_2.setColumns(["1fr", "3fr"]);
						formLayout_2.setRows(["1fr"]);
						group_5.setLayout(formLayout_2);
						(function(container){
							var inputBox_1 = new cpr.controls.InputBox("ipb13");
							inputBox_1.value = "P04581";
							container.addChild(inputBox_1, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var inputBox_2 = new cpr.controls.InputBox("ipb3");
							inputBox_2.value = "(무) 가족愛Dream보험";
							container.addChild(inputBox_2, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_5);
						container.addChild(group_5, {
							"colIndex": 3,
							"rowIndex": 0
						});
						var inputBox_3 = new cpr.controls.InputBox("ipb2");
						inputBox_3.value = "164813";
						container.addChild(inputBox_3, {
							"colIndex": 1,
							"rowIndex": 0
						});
					})(group_3);
					container.addChild(group_3, {
						"autoSize": "height",
						"width": "729px",
						"height": "40px"
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "729px",
					"height": "40px"
				});
				var group_6 = new cpr.controls.Container("grpBodyGroundGrid");
				group_6.style.setClasses(["grid-box"]);
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 8;
				group_6.setLayout(verticalLayout_4);
				(function(container){
					var grid_1 = new cpr.controls.Grid("grd1");
					grid_1.init({
						"dataSet": app.lookup("ds1"),
						"columns": [
							{"width": "200px"},
							{"width": "100px"}
						],
						"header": {
							"rows": [{"height": "31px"}],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "보장내용";
										cell.text = "보장내용";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "보장금액";
										cell.text = "보장금액";
									}
								}
							]
						},
						"detail": {
							"rows": [{"height": "31px"}],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
										cell.columnName = "보장내용";
										cell.control = (function(){
											var output_3 = new cpr.controls.Output();
											output_3.bind("value").toDataColumn("보장내용");
											return output_3;
										})();
										cell.controlConstraint = {};
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1},
									"configurator": function(cell){
										cell.columnName = "보장금액";
										cell.control = (function(){
											var numberEditor_1 = new cpr.controls.NumberEditor("nbe1");
											numberEditor_1.format = "s#,###";
											numberEditor_1.bind("value").toDataColumn("보장금액");
											return numberEditor_1;
										})();
										cell.controlConstraint = {};
									}
								}
							]
						}
					});
					grid_1.style.setClasses(["list-normal"]);
					container.addChild(grid_1, {
						"width": "400px",
						"height": "498px"
					});
				})(group_6);
				container.addChild(group_6, {
					"autoSize": "height",
					"width": "1600px",
					"height": "503px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "729px",
				"height": "558px"
			});
			
			var group_7 = new cpr.controls.Container();
			group_7.style.setClasses(["button-table-area"]);
			var formLayout_3 = new cpr.controls.layouts.FormLayout();
			formLayout_3.scrollable = false;
			formLayout_3.topMargin = "0px";
			formLayout_3.rightMargin = "0px";
			formLayout_3.bottomMargin = "0px";
			formLayout_3.leftMargin = "0px";
			formLayout_3.horizontalSpacing = "0px";
			formLayout_3.verticalSpacing = "0px";
			formLayout_3.setColumns(["1fr", "43px", "1fr"]);
			formLayout_3.setColumnAutoSizing(1, true);
			formLayout_3.setRows(["1fr"]);
			group_7.setLayout(formLayout_3);
			(function(container){
				var group_8 = new cpr.controls.Container();
				group_8.style.setClasses(["button-table-bottom-left-area"]);
				var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
				flowLayout_2.scrollable = false;
				flowLayout_2.horizontalSpacing = 10;
				flowLayout_2.verticalSpacing = 0;
				flowLayout_2.lineWrap = false;
				group_8.setLayout(flowLayout_2);
				(function(container){
					var button_2 = new cpr.controls.Button();
					button_2.value = "고객별조회";
					button_2.style.setClasses(["btn-primary04", "btn-md"]);
					container.addChild(button_2, {
						"autoSize": "width",
						"width": "80px",
						"height": "30px"
					});
				})(group_8);
				container.addChild(group_8, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_9 = new cpr.controls.Container();
				group_9.style.setClasses(["button-table-bottom-center-area"]);
				var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
				flowLayout_3.scrollable = false;
				flowLayout_3.horizontalSpacing = 10;
				flowLayout_3.verticalSpacing = 0;
				flowLayout_3.horizontalAlign = "center";
				group_9.setLayout(flowLayout_3);
				container.addChild(group_9, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var group_10 = new cpr.controls.Container();
				group_10.style.setClasses(["button-table-bottom-right-area"]);
				var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
				flowLayout_4.scrollable = false;
				flowLayout_4.horizontalSpacing = 10;
				flowLayout_4.verticalSpacing = 0;
				flowLayout_4.horizontalAlign = "right";
				flowLayout_4.lineWrap = false;
				group_10.setLayout(flowLayout_4);
				container.addChild(group_10, {
					"colIndex": 2,
					"rowIndex": 0
				});
			})(group_7);
			container.addChild(group_7, {
				"autoSize": "height",
				"width": "729px",
				"height": "30px"
			});
		}
	});
	app.title = "계약번호별 보장내용 조회";
	cpr.core.Platform.INSTANCE.register(app);
})();
