/*
 * App URI: sfa/신계약+UW/NBDZ10M1
 * Source Location: sfa/신계약+UW/NBDZ10M1.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("sfa/신계약+UW/NBDZ10M1", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * NBDZ10M1.js
			 * Created at 2024. 4. 3. 오후 4:19:31.
			 *
			 * @author chwec
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"},
					{"name": "column12"}
				],
				"rows": [{"column1": "피보험자", "column2": "조민영", "column3": "I06790 (무)KDB파워플랜저축보험", "column4": "12000", "column5": "0", "column6": "12000", "column7": "1000000", "column8": "0", "column9": "1000000", "column10": "201503", "column11": "1", "column12": ""}]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["grid-window-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 0;
			verticalLayout_1.leftMargin = 20;
			verticalLayout_1.rightMargin = 20;
			verticalLayout_1.topMargin = 20;
			verticalLayout_1.bottomMargin = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpAppTitle");
			group_1.style.setClasses(["app-title"]);
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr", "1fr"]);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output("optTitle2");
				output_1.value = "변경청약안내";
				output_1.style.setClasses(["navi-left"]);
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_2 = new cpr.controls.Container("grpNavi2");
				group_2.style.setClasses(["breadcrumbs"]);
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 5;
				flowLayout_1.verticalSpacing = 0;
				flowLayout_1.horizontalAlign = "right";
				flowLayout_1.verticalAlign = "middle";
				flowLayout_1.lineWrap = false;
				group_2.setLayout(flowLayout_1);
				(function(container){
					var output_2 = new cpr.controls.Output();
					output_2.value = "";
					output_2.style.setClasses(["home"]);
					container.addChild(output_2, {
						"width": "20px",
						"height": "20px"
					});
					var output_3 = new cpr.controls.Output();
					output_3.value = "1Depth";
					output_3.style.setClasses(["breadcrumb-item"]);
					container.addChild(output_3, {
						"autoSize": "width",
						"width": "45px",
						"height": "17px"
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "2Depth";
					output_4.style.setClasses(["breadcrumb-item"]);
					container.addChild(output_4, {
						"autoSize": "width",
						"width": "45px",
						"height": "17px"
					});
					var output_5 = new cpr.controls.Output();
					output_5.value = "3Depth";
					output_5.style.setClasses(["breadcrumb-item"]);
					container.addChild(output_5, {
						"autoSize": "width",
						"width": "45px",
						"height": "17px"
					});
					var output_6 = new cpr.controls.Output();
					output_6.value = "4Depth";
					output_6.style.setClasses(["breadcrumb-item"]);
					container.addChild(output_6, {
						"autoSize": "width",
						"width": "45px",
						"height": "17px"
					});
				})(group_2);
				container.addChild(group_2, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1560px",
				"height": "35px"
			});
			
			var group_3 = new cpr.controls.Container("grpTopSearch");
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 12;
			group_3.setLayout(verticalLayout_2);
			(function(container){
				var group_4 = new cpr.controls.Container("grpTopSearchBox2");
				group_4.style.setClasses(["search-box"]);
				var formLayout_2 = new cpr.controls.layouts.FormLayout();
				formLayout_2.scrollable = false;
				formLayout_2.topMargin = "6px";
				formLayout_2.rightMargin = "20px";
				formLayout_2.bottomMargin = "6px";
				formLayout_2.leftMargin = "20px";
				formLayout_2.horizontalSpacing = "20px";
				formLayout_2.verticalSpacing = "8px";
				formLayout_2.setColumns(["0px", "1fr", "0px", "1fr", "0px", "1fr", "63px"]);
				formLayout_2.setColumnAutoSizing(0, true);
				formLayout_2.setColumnAutoSizing(2, true);
				formLayout_2.setColumnAutoSizing(4, true);
				formLayout_2.setColumnAutoSizing(6, true);
				formLayout_2.setRows(["26px"]);
				group_4.setLayout(formLayout_2);
				(function(container){
					var output_7 = new cpr.controls.Output();
					output_7.value = "계약/청약번호";
					output_7.style.setClasses(["label", "required"]);
					container.addChild(output_7, {
						"colIndex": 2,
						"rowIndex": 0
					});
					var group_5 = new cpr.controls.Container();
					group_5.style.setClasses(["form-inside"]);
					var formLayout_3 = new cpr.controls.layouts.FormLayout();
					formLayout_3.scrollable = false;
					formLayout_3.topMargin = "0px";
					formLayout_3.rightMargin = "0px";
					formLayout_3.bottomMargin = "0px";
					formLayout_3.leftMargin = "0px";
					formLayout_3.horizontalSpacing = "5px";
					formLayout_3.verticalSpacing = "5px";
					formLayout_3.setColumns(["120px", "1fr"]);
					formLayout_3.setRows(["1fr"]);
					group_5.setLayout(formLayout_3);
					(function(container){
						var inputBox_1 = new cpr.controls.InputBox("ipb1");
						inputBox_1.value = "04811";
						container.addChild(inputBox_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var searchInput_1 = new cpr.controls.SearchInput();
						searchInput_1.value = "10015";
						container.addChild(searchInput_1, {
							"colIndex": 1,
							"rowIndex": 0
						});
					})(group_5);
					container.addChild(group_5, {
						"colIndex": 3,
						"rowIndex": 0
					});
					var group_6 = new cpr.controls.Container();
					group_6.style.setClasses(["btn-flow-area"]);
					var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
					flowLayout_2.scrollable = false;
					flowLayout_2.verticalSpacing = 0;
					flowLayout_2.horizontalAlign = "right";
					flowLayout_2.lineWrap = false;
					flowLayout_2.leftMargin = 20;
					group_6.setLayout(flowLayout_2);
					(function(container){
						var button_1 = new cpr.controls.Button();
						button_1.value = "조회";
						button_1.style.setClasses(["btn-search"]);
						container.addChild(button_1, {
							"width": "49px",
							"height": "26px"
						});
					})(group_6);
					container.addChild(group_6, {
						"colIndex": 6,
						"rowIndex": 0,
						"colSpan": 1,
						"rowSpan": 1,
						"verticalAlign": "center",
						"height": 26
					});
				})(group_4);
				container.addChild(group_4, {
					"autoSize": "height",
					"width": "1560px",
					"height": "40px"
				});
			})(group_3);
			container.addChild(group_3, {
				"autoSize": "height",
				"width": "1560px",
				"height": "40px"
			});
			
			var group_7 = new cpr.controls.Container("grpBody");
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.spacing = 7;
			group_7.setLayout(verticalLayout_3);
			(function(container){
				var group_8 = new cpr.controls.Container();
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 8;
				group_8.setLayout(verticalLayout_4);
				(function(container){
					var group_9 = new cpr.controls.Container();
					group_9.style.setClasses(["form-box"]);
					var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_5.scrollable = false;
					verticalLayout_5.spacing = 8;
					group_9.setLayout(verticalLayout_5);
					(function(container){
						var group_10 = new cpr.controls.Container();
						group_10.style.setClasses(["form-title-box"]);
						var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
						group_10.setLayout(verticalLayout_6);
						(function(container){
							var output_8 = new cpr.controls.Output();
							output_8.value = "계약사항";
							output_8.style.setClasses(["form-title"]);
							container.addChild(output_8, {
								"autoSize": "height",
								"width": "300px",
								"height": "17px"
							});
						})(group_10);
						container.addChild(group_10, {
							"autoSize": "height",
							"width": "300px",
							"height": "17px"
						});
						var group_11 = new cpr.controls.Container();
						group_11.style.setClasses(["form-normal"]);
						var formLayout_4 = new cpr.controls.layouts.FormLayout();
						formLayout_4.scrollable = false;
						formLayout_4.topMargin = "2px";
						formLayout_4.rightMargin = "5px";
						formLayout_4.bottomMargin = "2px";
						formLayout_4.leftMargin = "5px";
						formLayout_4.horizontalSpacing = "11px";
						formLayout_4.verticalSpacing = "5px";
						formLayout_4.horizontalSeparatorWidth = 1;
						formLayout_4.verticalSeparatorWidth = 1;
						formLayout_4.setColumns(["110px", "1fr", "110px", "1fr", "110px", "1fr", "110px", "1fr"]);
						formLayout_4.setUseColumnShade(0, true);
						formLayout_4.setUseColumnShade(2, true);
						formLayout_4.setUseColumnShade(4, true);
						formLayout_4.setUseColumnShade(6, true);
						formLayout_4.setColumnAutoSizing(0, true);
						formLayout_4.setColumnAutoSizing(2, true);
						formLayout_4.setColumnAutoSizing(4, true);
						formLayout_4.setColumnAutoSizing(6, true);
						formLayout_4.setRows(["26px", "26px", "26px", "26px"]);
						group_11.setLayout(formLayout_4);
						(function(container){
							var output_9 = new cpr.controls.Output();
							output_9.value = "상품명";
							output_9.style.setClasses(["label"]);
							container.addChild(output_9, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var group_12 = new cpr.controls.Container();
							group_12.style.setClasses(["form-inside"]);
							var formLayout_5 = new cpr.controls.layouts.FormLayout();
							formLayout_5.scrollable = false;
							formLayout_5.horizontalSpacing = "5px";
							formLayout_5.verticalSpacing = "2px";
							formLayout_5.setColumns(["1fr", "3fr"]);
							formLayout_5.setRows(["1fr"]);
							group_12.setLayout(formLayout_5);
							(function(container){
								var inputBox_2 = new cpr.controls.InputBox("ipb3");
								inputBox_2.value = "P06790";
								container.addChild(inputBox_2, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var inputBox_3 = new cpr.controls.InputBox("ipb12");
								inputBox_3.value = "(무)KDB파워플랜저축보험";
								container.addChild(inputBox_3, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_12);
							container.addChild(group_12, {
								"colIndex": 1,
								"rowIndex": 0,
								"colSpan": 3,
								"rowSpan": 1
							});
							var output_10 = new cpr.controls.Output();
							output_10.value = "납입방법";
							output_10.style.setClasses(["label"]);
							container.addChild(output_10, {
								"colIndex": 4,
								"rowIndex": 0
							});
							var inputBox_4 = new cpr.controls.InputBox("ipb11");
							inputBox_4.value = "자동이체";
							container.addChild(inputBox_4, {
								"colIndex": 5,
								"rowIndex": 0
							});
							var output_11 = new cpr.controls.Output();
							output_11.value = "적부조사일자";
							output_11.style.setClasses(["label"]);
							container.addChild(output_11, {
								"colIndex": 6,
								"rowIndex": 0
							});
							var maskEditor_1 = new cpr.controls.MaskEditor("mse1");
							maskEditor_1.mask = "___-__-__";
							container.addChild(maskEditor_1, {
								"colIndex": 7,
								"rowIndex": 0
							});
							var output_12 = new cpr.controls.Output();
							output_12.value = "계약자";
							output_12.style.setClasses(["label"]);
							container.addChild(output_12, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var group_13 = new cpr.controls.Container();
							group_13.style.setClasses(["form-inside"]);
							var formLayout_6 = new cpr.controls.layouts.FormLayout();
							formLayout_6.scrollable = false;
							formLayout_6.horizontalSpacing = "5px";
							formLayout_6.verticalSpacing = "2px";
							formLayout_6.setColumns(["2fr", "3fr"]);
							formLayout_6.setRows(["1fr"]);
							group_13.setLayout(formLayout_6);
							(function(container){
								var inputBox_5 = new cpr.controls.InputBox("ipb13");
								inputBox_5.value = "조민영";
								container.addChild(inputBox_5, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var maskEditor_2 = new cpr.controls.MaskEditor("mse2");
								maskEditor_2.value = "8007071111111";
								maskEditor_2.mask = "000000-0******";
								container.addChild(maskEditor_2, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_13);
							container.addChild(group_13, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_13 = new cpr.controls.Output();
							output_13.value = "계약번호";
							output_13.style.setClasses(["label"]);
							container.addChild(output_13, {
								"colIndex": 2,
								"rowIndex": 1
							});
							var inputBox_6 = new cpr.controls.InputBox("ipb14");
							inputBox_6.value = "048111";
							container.addChild(inputBox_6, {
								"colIndex": 3,
								"rowIndex": 1
							});
							var output_14 = new cpr.controls.Output();
							output_14.value = "납입기간";
							output_14.style.setClasses(["label"]);
							container.addChild(output_14, {
								"colIndex": 4,
								"rowIndex": 1
							});
							var inputBox_7 = new cpr.controls.InputBox("ipb2");
							inputBox_7.value = "20";
							inputBox_7.style.setClasses(["text-right"]);
							container.addChild(inputBox_7, {
								"colIndex": 5,
								"rowIndex": 1
							});
							var output_15 = new cpr.controls.Output();
							output_15.value = "수금기관명";
							output_15.style.setClasses(["label"]);
							container.addChild(output_15, {
								"colIndex": 6,
								"rowIndex": 1
							});
							var inputBox_8 = new cpr.controls.InputBox("ipb5");
							inputBox_8.value = "보험시스템팀";
							container.addChild(inputBox_8, {
								"colIndex": 7,
								"rowIndex": 1
							});
							var output_16 = new cpr.controls.Output();
							output_16.value = "계약일자";
							output_16.style.setClasses(["label"]);
							container.addChild(output_16, {
								"colIndex": 0,
								"rowIndex": 2
							});
							var dateInput_1 = new cpr.controls.DateInput("dti1");
							dateInput_1.value = "20150319";
							container.addChild(dateInput_1, {
								"colIndex": 1,
								"rowIndex": 2,
								"horizontalAlign": "left",
								"width": 120
							});
							var output_17 = new cpr.controls.Output();
							output_17.value = "계약변경여부";
							output_17.style.setClasses(["label"]);
							container.addChild(output_17, {
								"colIndex": 2,
								"rowIndex": 2
							});
							var inputBox_9 = new cpr.controls.InputBox("ipb15");
							inputBox_9.value = "N";
							container.addChild(inputBox_9, {
								"colIndex": 3,
								"rowIndex": 2
							});
							var output_18 = new cpr.controls.Output();
							output_18.value = "납입횟수";
							output_18.style.setClasses(["label"]);
							container.addChild(output_18, {
								"colIndex": 4,
								"rowIndex": 2
							});
							var inputBox_10 = new cpr.controls.InputBox("ipb10");
							inputBox_10.value = "1";
							inputBox_10.style.setClasses(["text-right"]);
							container.addChild(inputBox_10, {
								"colIndex": 5,
								"rowIndex": 2
							});
							var output_19 = new cpr.controls.Output();
							output_19.value = "약관대출금액";
							output_19.style.setClasses(["label"]);
							container.addChild(output_19, {
								"colIndex": 6,
								"rowIndex": 2
							});
							var inputBox_11 = new cpr.controls.InputBox("ipb8");
							inputBox_11.value = "0";
							inputBox_11.style.setClasses(["text-right"]);
							container.addChild(inputBox_11, {
								"colIndex": 7,
								"rowIndex": 2
							});
							var output_20 = new cpr.controls.Output();
							output_20.value = "계약상태";
							output_20.style.setClasses(["label"]);
							container.addChild(output_20, {
								"colIndex": 0,
								"rowIndex": 3
							});
							var inputBox_12 = new cpr.controls.InputBox("ipb16");
							inputBox_12.value = "청약";
							container.addChild(inputBox_12, {
								"colIndex": 1,
								"rowIndex": 3
							});
							var output_21 = new cpr.controls.Output();
							output_21.value = "주계약 가입금액";
							output_21.style.setClasses(["label"]);
							container.addChild(output_21, {
								"colIndex": 2,
								"rowIndex": 3
							});
							var numberEditor_1 = new cpr.controls.NumberEditor("nbe3");
							numberEditor_1.value = "120000000";
							container.addChild(numberEditor_1, {
								"colIndex": 3,
								"rowIndex": 3
							});
							var output_22 = new cpr.controls.Output();
							output_22.value = "보험료";
							output_22.style.setClasses(["label"]);
							container.addChild(output_22, {
								"colIndex": 4,
								"rowIndex": 3
							});
							var numberEditor_2 = new cpr.controls.NumberEditor("nbe2");
							numberEditor_2.value = "1007490";
							container.addChild(numberEditor_2, {
								"colIndex": 5,
								"rowIndex": 3
							});
							var output_23 = new cpr.controls.Output();
							output_23.value = "선납할인금액";
							output_23.style.setClasses(["label"]);
							container.addChild(output_23, {
								"colIndex": 6,
								"rowIndex": 3
							});
							var inputBox_13 = new cpr.controls.InputBox("ipb9");
							inputBox_13.value = "0";
							inputBox_13.style.setClasses(["text-right"]);
							container.addChild(inputBox_13, {
								"colIndex": 7,
								"rowIndex": 3
							});
						})(group_11);
						container.addChild(group_11, {
							"autoSize": "height",
							"width": "2358px",
							"height": "126px"
						});
					})(group_9);
					container.addChild(group_9, {
						"autoSize": "height",
						"width": "2358px",
						"height": "154px"
					});
				})(group_8);
				container.addChild(group_8, {
					"autoSize": "height",
					"width": "2358px",
					"height": "154px"
				});
				var group_14 = new cpr.controls.Container();
				var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_7.spacing = 8;
				group_14.setLayout(verticalLayout_7);
				(function(container){
					var group_15 = new cpr.controls.Container("grpBodyGroundGrid");
					group_15.style.setClasses(["grid-box"]);
					var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_8.spacing = 8;
					group_15.setLayout(verticalLayout_8);
					(function(container){
						var group_16 = new cpr.controls.Container("grpGridTitle");
						group_16.style.setClasses(["button-table-area"]);
						var formLayout_7 = new cpr.controls.layouts.FormLayout();
						formLayout_7.scrollable = false;
						formLayout_7.topMargin = "0px";
						formLayout_7.rightMargin = "0px";
						formLayout_7.bottomMargin = "0px";
						formLayout_7.leftMargin = "0px";
						formLayout_7.horizontalSpacing = "0px";
						formLayout_7.verticalSpacing = "0px";
						formLayout_7.setColumns(["0px", "1fr"]);
						formLayout_7.setColumnAutoSizing(0, true);
						formLayout_7.setRows(["1fr"]);
						group_16.setLayout(formLayout_7);
						(function(container){
							var group_17 = new cpr.controls.Container();
							group_17.style.setClasses(["grid-title-box"]);
							var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
							verticalLayout_9.spacing = 0;
							group_17.setLayout(verticalLayout_9);
							(function(container){
								var output_24 = new cpr.controls.Output("optGrildTitle");
								output_24.value = "보험가입현황";
								output_24.style.setClasses(["grid-title"]);
								container.addChild(output_24, {
									"autoSize": "height",
									"width": "300px",
									"height": "26px"
								});
							})(group_17);
							container.addChild(group_17, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var group_18 = new cpr.controls.Container();
							group_18.style.setClasses(["button-table-top-area"]);
							var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
							flowLayout_3.scrollable = false;
							flowLayout_3.horizontalSpacing = 5;
							flowLayout_3.verticalSpacing = 5;
							flowLayout_3.horizontalAlign = "right";
							flowLayout_3.lineWrap = false;
							group_18.setLayout(flowLayout_3);
							container.addChild(group_18, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_16);
						container.addChild(group_16, {
							"autoSize": "height",
							"width": "1600px",
							"height": "26px"
						});
						var grid_1 = new cpr.controls.Grid("grd1");
						grid_1.init({
							"dataSet": app.lookup("ds1"),
							"columns": [
								{"width": "100px"},
								{"width": "100px"},
								{"width": "250px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [
									{"height": "31px"},
									{"height": "31px"}
								],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column1";
											cell.text = "구분";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column2";
											cell.text = "피보험자명";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column3";
											cell.text = "보험종류";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column4";
											cell.text = "변경전";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column5";
											cell.text = "변경";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column6";
											cell.text = "변경후";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column7";
											cell.text = "변경전";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 7},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column8";
											cell.text = "변경";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 8},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column9";
											cell.text = "변경후";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column10";
											cell.text = "유지년월";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column11";
											cell.text = "유지회차";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 11, "rowSpan": 2, "colSpan": 3},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column12";
											cell.text = "계약관계자";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3, "rowSpan": 1, "colSpan": 3},
										"configurator": function(cell){
											cell.text = "주계약금액(만원)";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6, "rowSpan": 1, "colSpan": 3},
										"configurator": function(cell){
											cell.text = "보험료(원)";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnName = "column1";
											cell.control = (function(){
												var output_25 = new cpr.controls.Output();
												output_25.style.setClasses(["text-center"]);
												output_25.bind("value").toDataColumn("column1");
												return output_25;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "column2";
											cell.control = (function(){
												var output_26 = new cpr.controls.Output();
												output_26.style.setClasses(["text-center"]);
												output_26.bind("value").toDataColumn("column2");
												return output_26;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "column3";
											cell.control = (function(){
												var output_27 = new cpr.controls.Output();
												output_27.bind("value").toDataColumn("column3");
												return output_27;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "column4";
											cell.control = (function(){
												var numberEditor_3 = new cpr.controls.NumberEditor("nbe5");
												numberEditor_3.bind("value").toDataColumn("column4");
												return numberEditor_3;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "column5";
											cell.control = (function(){
												var numberEditor_4 = new cpr.controls.NumberEditor("nbe1");
												numberEditor_4.bind("value").toDataColumn("column5");
												return numberEditor_4;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "column6";
											cell.control = (function(){
												var numberEditor_5 = new cpr.controls.NumberEditor("nbe4");
												numberEditor_5.bind("value").toDataColumn("column6");
												return numberEditor_5;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "column7";
											cell.control = (function(){
												var numberEditor_6 = new cpr.controls.NumberEditor("nbe6");
												numberEditor_6.bind("value").toDataColumn("column7");
												return numberEditor_6;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.columnName = "column8";
											cell.control = (function(){
												var numberEditor_7 = new cpr.controls.NumberEditor("nbe7");
												numberEditor_7.bind("value").toDataColumn("column8");
												return numberEditor_7;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.columnName = "column9";
											cell.control = (function(){
												var numberEditor_8 = new cpr.controls.NumberEditor("nbe8");
												numberEditor_8.bind("value").toDataColumn("column9");
												return numberEditor_8;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.columnName = "column10";
											cell.control = (function(){
												var dateInput_2 = new cpr.controls.DateInput("dti2");
												dateInput_2.calendarType = "yearmonth";
												dateInput_2.mask = "YYYY-MM";
												dateInput_2.bind("value").toDataColumn("column10");
												return dateInput_2;
											})();
											cell.controlConstraint = {
												"horizontalAlign": "fill",
												"width": 120
											};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.columnName = "column11";
											cell.control = (function(){
												var output_28 = new cpr.controls.Output();
												output_28.style.setClasses(["text-right"]);
												output_28.bind("value").toDataColumn("column11");
												return output_28;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 11},
										"configurator": function(cell){
											cell.columnName = "column12";
											cell.control = (function(){
												var output_29 = new cpr.controls.Output();
												output_29.bind("value").toDataColumn("column12");
												return output_29;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 12},
										"configurator": function(cell){
											cell.control = (function(){
												var output_30 = new cpr.controls.Output();
												return output_30;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 13},
										"configurator": function(cell){
											cell.control = (function(){
												var output_31 = new cpr.controls.Output();
												return output_31;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							},
							"footer": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 1, "colSpan": 3},
										"configurator": function(cell){
											cell.expr = "\"합계\"";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.expr = "getSum(\"column4\")";
											cell.control = (function(){
												var output_32 = new cpr.controls.Output();
												output_32.value = "Output";
												output_32.dataType = "number";
												output_32.format = "s#,##0";
												output_32.style.setClasses(["text-right"]);
												return output_32;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.expr = "getSum(\"column5\")";
											cell.control = (function(){
												var output_33 = new cpr.controls.Output();
												output_33.value = "Output";
												output_33.dataType = "number";
												output_33.format = "s#,##0";
												output_33.style.setClasses(["text-right"]);
												return output_33;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.expr = "getSum(\"column6\")";
											cell.control = (function(){
												var output_34 = new cpr.controls.Output();
												output_34.value = "Output";
												output_34.dataType = "number";
												output_34.format = "s#,##0";
												output_34.style.setClasses(["text-right"]);
												return output_34;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.expr = "getSum(\"column7\")";
											cell.control = (function(){
												var output_35 = new cpr.controls.Output();
												output_35.value = "Output";
												output_35.dataType = "number";
												output_35.format = "s#,##0";
												output_35.style.setClasses(["text-right"]);
												return output_35;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.expr = "getSum(\"column8\")";
											cell.control = (function(){
												var output_36 = new cpr.controls.Output();
												output_36.value = "Output";
												output_36.dataType = "number";
												output_36.format = "s#,##0";
												output_36.style.setClasses(["text-right"]);
												return output_36;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.expr = "getSum(\"column9\")";
											cell.control = (function(){
												var output_37 = new cpr.controls.Output();
												output_37.value = "Output";
												output_37.dataType = "number";
												output_37.format = "s#,##0";
												output_37.style.setClasses(["text-right"]);
												return output_37;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.expr = "\"\"";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.expr = "\"\"";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 11},
										"configurator": function(cell){
											cell.expr = "\"\"";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 12},
										"configurator": function(cell){
											cell.expr = "\"\"";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 13},
										"configurator": function(cell){
											cell.expr = "\"\"";
										}
									}
								]
							}
						});
						grid_1.style.setClasses(["list-normal"]);
						container.addChild(grid_1, {
							"width": "400px",
							"height": "498px"
						});
					})(group_15);
					container.addChild(group_15, {
						"autoSize": "height",
						"width": "1560px",
						"height": "537px"
					});
				})(group_14);
				container.addChild(group_14, {
					"autoSize": "height",
					"width": "1560px",
					"height": "537px"
				});
				var group_19 = new cpr.controls.Container();
				var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_10.spacing = 8;
				group_19.setLayout(verticalLayout_10);
				(function(container){
					var group_20 = new cpr.controls.Container("grp7");
					group_20.style.setClasses(["form-box"]);
					var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_11.scrollable = false;
					verticalLayout_11.spacing = 8;
					group_20.setLayout(verticalLayout_11);
					(function(container){
						var group_21 = new cpr.controls.Container("grp5");
						group_21.style.setClasses(["form-normal"]);
						var formLayout_8 = new cpr.controls.layouts.FormLayout();
						formLayout_8.scrollable = false;
						formLayout_8.topMargin = "2px";
						formLayout_8.rightMargin = "5px";
						formLayout_8.bottomMargin = "2px";
						formLayout_8.leftMargin = "5px";
						formLayout_8.horizontalSpacing = "11px";
						formLayout_8.verticalSpacing = "5px";
						formLayout_8.horizontalSeparatorWidth = 1;
						formLayout_8.verticalSeparatorWidth = 1;
						formLayout_8.setColumns(["230px", "1fr", "230px", "1fr"]);
						formLayout_8.setUseColumnShade(0, true);
						formLayout_8.setUseColumnShade(2, true);
						formLayout_8.setColumnAutoSizing(0, true);
						formLayout_8.setColumnAutoSizing(2, true);
						formLayout_8.setRows(["26px"]);
						group_21.setLayout(formLayout_8);
						(function(container){
							var output_38 = new cpr.controls.Output();
							output_38.value = "변경청약안내 등록일자";
							output_38.style.setClasses(["label"]);
							container.addChild(output_38, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var dateInput_3 = new cpr.controls.DateInput("dti6");
							dateInput_3.value = "20150319";
							container.addChild(dateInput_3, {
								"colIndex": 1,
								"rowIndex": 0,
								"horizontalAlign": "left",
								"width": 120
							});
							var output_39 = new cpr.controls.Output();
							output_39.value = "변경사유";
							output_39.style.setClasses(["label"]);
							container.addChild(output_39, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var inputBox_14 = new cpr.controls.InputBox("ipb4");
							container.addChild(inputBox_14, {
								"colIndex": 3,
								"rowIndex": 0,
								"colSpan": 1,
								"rowSpan": 1
							});
						})(group_21);
						container.addChild(group_21, {
							"autoSize": "height",
							"width": "2205px",
							"height": "33px"
						});
					})(group_20);
					container.addChild(group_20, {
						"autoSize": "height",
						"width": "2205px",
						"height": "38px"
					});
				})(group_19);
				container.addChild(group_19, {
					"autoSize": "height",
					"width": "1560px",
					"height": "38px"
				});
				var group_22 = new cpr.controls.Container();
				var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_12.spacing = 8;
				group_22.setLayout(verticalLayout_12);
				(function(container){
					var group_23 = new cpr.controls.Container("grp2");
					group_23.style.setClasses(["form-box"]);
					var verticalLayout_13 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_13.scrollable = false;
					verticalLayout_13.spacing = 8;
					group_23.setLayout(verticalLayout_13);
					(function(container){
						var group_24 = new cpr.controls.Container("grp3");
						group_24.style.setClasses(["form-normal"]);
						var formLayout_9 = new cpr.controls.layouts.FormLayout();
						formLayout_9.scrollable = false;
						formLayout_9.topMargin = "2px";
						formLayout_9.rightMargin = "5px";
						formLayout_9.bottomMargin = "2px";
						formLayout_9.leftMargin = "5px";
						formLayout_9.horizontalSpacing = "11px";
						formLayout_9.verticalSpacing = "5px";
						formLayout_9.horizontalSeparatorWidth = 1;
						formLayout_9.verticalSeparatorWidth = 1;
						formLayout_9.setColumns(["230px", "1fr", "230px", "1fr"]);
						formLayout_9.setUseColumnShade(0, true);
						formLayout_9.setUseColumnShade(2, true);
						formLayout_9.setColumnAutoSizing(0, true);
						formLayout_9.setColumnAutoSizing(2, true);
						formLayout_9.setRows(["26px"]);
						group_24.setLayout(formLayout_9);
						(function(container){
							var output_40 = new cpr.controls.Output();
							output_40.value = "사원번호";
							output_40.style.setClasses(["label"]);
							container.addChild(output_40, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var inputBox_15 = new cpr.controls.InputBox("ipb7");
							inputBox_15.value = "1000";
							container.addChild(inputBox_15, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_41 = new cpr.controls.Output();
							output_41.value = "비밀번호";
							output_41.style.setClasses(["label", "required"]);
							container.addChild(output_41, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var inputBox_16 = new cpr.controls.InputBox("ipb6");
							inputBox_16.value = "******";
							container.addChild(inputBox_16, {
								"colIndex": 3,
								"rowIndex": 0,
								"colSpan": 1,
								"rowSpan": 1
							});
						})(group_24);
						container.addChild(group_24, {
							"autoSize": "height",
							"width": "2168px",
							"height": "33px"
						});
					})(group_23);
					container.addChild(group_23, {
						"autoSize": "height",
						"width": "2168px",
						"height": "38px"
					});
					var group_25 = new cpr.controls.Container("grp1");
					group_25.style.setClasses(["button-table-area"]);
					var formLayout_10 = new cpr.controls.layouts.FormLayout();
					formLayout_10.scrollable = false;
					formLayout_10.topMargin = "0px";
					formLayout_10.rightMargin = "0px";
					formLayout_10.bottomMargin = "0px";
					formLayout_10.leftMargin = "0px";
					formLayout_10.horizontalSpacing = "0px";
					formLayout_10.verticalSpacing = "0px";
					formLayout_10.setColumns(["1fr", "43px", "1fr"]);
					formLayout_10.setColumnAutoSizing(1, true);
					formLayout_10.setRows(["1fr"]);
					group_25.setLayout(formLayout_10);
					(function(container){
						var group_26 = new cpr.controls.Container("grp4");
						group_26.style.setClasses(["button-table-bottom-left-area"]);
						var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
						flowLayout_4.scrollable = false;
						flowLayout_4.horizontalSpacing = 10;
						flowLayout_4.verticalSpacing = 0;
						flowLayout_4.lineWrap = false;
						group_26.setLayout(flowLayout_4);
						container.addChild(group_26, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_27 = new cpr.controls.Container("grp6");
						group_27.style.setClasses(["button-table-bottom-center-area"]);
						var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
						flowLayout_5.scrollable = false;
						flowLayout_5.horizontalSpacing = 10;
						flowLayout_5.verticalSpacing = 0;
						flowLayout_5.horizontalAlign = "center";
						group_27.setLayout(flowLayout_5);
						container.addChild(group_27, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var group_28 = new cpr.controls.Container("grp8");
						group_28.style.setClasses(["button-table-bottom-right-area"]);
						var flowLayout_6 = new cpr.controls.layouts.FlowLayout();
						flowLayout_6.scrollable = false;
						flowLayout_6.horizontalSpacing = 10;
						flowLayout_6.verticalSpacing = 0;
						flowLayout_6.horizontalAlign = "right";
						flowLayout_6.lineWrap = false;
						group_28.setLayout(flowLayout_6);
						(function(container){
							var button_2 = new cpr.controls.Button("btn6");
							button_2.value = "보험료계산";
							button_2.style.setClasses(["btn-primary04"]);
							container.addChild(button_2, {
								"autoSize": "width",
								"width": "80px",
								"height": "30px"
							});
							var button_3 = new cpr.controls.Button("btn7");
							button_3.value = "저장";
							button_3.style.setClasses(["btn-primary03"]);
							container.addChild(button_3, {
								"autoSize": "width",
								"width": "60px",
								"height": "30px"
							});
							var button_4 = new cpr.controls.Button("btn8");
							button_4.value = "삭제";
							button_4.style.setClasses(["btn-primary03"]);
							container.addChild(button_4, {
								"autoSize": "width",
								"width": "60px",
								"height": "30px"
							});
						})(group_28);
						container.addChild(group_28, {
							"colIndex": 2,
							"rowIndex": 0
						});
					})(group_25);
					container.addChild(group_25, {
						"autoSize": "height",
						"width": "1560px",
						"height": "30px"
					});
				})(group_22);
				container.addChild(group_22, {
					"autoSize": "height",
					"width": "2168px",
					"height": "76px"
				});
			})(group_7);
			container.addChild(group_7, {
				"autoSize": "height",
				"width": "1560px",
				"height": "826px"
			});
		}
	});
	app.title = "변경청약안내";
	cpr.core.Platform.INSTANCE.register(app);
})();
