/*
 * App URI: sfa/신계약+UW/보험계약 비교 안내문
 * Source Location: sfa/신계약+UW/보험계약 비교 안내문.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("sfa/신계약+UW/보험계약 비교 안내문", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * ${filename}
			 * Created at ${date} ${time}.
			 *
			 * @author ${user}
			 ************************************************/
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["pop-content-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpBody");
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 15;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("grpData");
				group_2.style.setClasses(["form-box", "box-spacing-free"]);
				var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_3.spacing = 8;
				group_2.setLayout(verticalLayout_3);
				(function(container){
					var hTMLSnippet_1 = new cpr.controls.HTMLSnippet();
					hTMLSnippet_1.value = "<p>HTML Snippet<\/p>";
					container.addChild(hTMLSnippet_1, {
						"autoSize": "height",
						"width": "984px",
						"height": "643px"
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "729px",
					"height": "643px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "729px",
				"height": "643px"
			});
		}
	});
	app.title = "보험계약 비교 안내문";
	cpr.core.Platform.INSTANCE.register(app);
})();
