/*
 * App URI: pb/layout/ControlLayout
 * Source Location: pb/layout/ControlLayout.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("pb/layout/ControlLayout", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * ControlLayout.js
			 * Created at 2022. 10. 5. 오후 3:09:13.
			 *
			 * @author ryu
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["pb-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 14;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.setClasses(["pb-content"]);
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.scrollable = false;
			verticalLayout_2.spacing = 20;
			verticalLayout_2.leftMargin = 50;
			verticalLayout_2.rightMargin = 50;
			verticalLayout_2.topMargin = 0;
			verticalLayout_2.bottomMargin = 20;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var userDefinedControl_1 = new udc.hk.pb.Breadcrumbs();
				container.addChild(userDefinedControl_1, {
					"autoSize": "height",
					"width": "1544px",
					"height": "174px"
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "\u203b 레이아웃의 여백과 간격을 표시하기 위해 실제 사용되는 레이아웃이 아닌 XY레이아웃이 사용되었으므로 실제 사용 시에는 수치만 참고하시기 바랍니다.";
				output_1.style.setClasses(["text-red"]);
				container.addChild(output_1, {
					"autoSize": "height",
					"width": "100px",
					"height": "20px",
					"minHeight": 20
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1520px",
				"height": "250px"
			});
			
			var group_2 = new cpr.controls.Container();
			group_2.style.setClasses(["pb-content"]);
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.scrollable = false;
			verticalLayout_3.spacing = 40;
			verticalLayout_3.leftMargin = 50;
			verticalLayout_3.rightMargin = 50;
			verticalLayout_3.topMargin = 50;
			verticalLayout_3.bottomMargin = 50;
			group_2.setLayout(verticalLayout_3);
			(function(container){
				var group_3 = new cpr.controls.Container();
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.scrollable = false;
				verticalLayout_4.spacing = 14;
				group_3.setLayout(verticalLayout_4);
				(function(container){
					var userDefinedControl_2 = new udc.hk.pb.SectionTitle();
					userDefinedControl_2.title = "가이드라인";
					container.addChild(userDefinedControl_2, {
						"autoSize": "none",
						"width": "1544px",
						"height": "29px"
					});
					var group_4 = new cpr.controls.Container();
					group_4.style.setClasses(["pb-table"]);
					var formLayout_1 = new cpr.controls.layouts.FormLayout();
					formLayout_1.scrollable = false;
					formLayout_1.topMargin = "4px";
					formLayout_1.rightMargin = "4px";
					formLayout_1.bottomMargin = "4px";
					formLayout_1.leftMargin = "4px";
					formLayout_1.horizontalSpacing = "8px";
					formLayout_1.verticalSpacing = "8px";
					formLayout_1.horizontalSeparatorWidth = 1;
					formLayout_1.verticalSeparatorWidth = 1;
					formLayout_1.setColumns(["150px", "40px", "1fr"]);
					formLayout_1.setUseColumnShade(0, true);
					formLayout_1.setRows(["28px", "26px", "26px", "26px", "26px"]);
					formLayout_1.setUseRowShade(0, true);
					formLayout_1.setRowAutoSizing(1, true);
					formLayout_1.setRowAutoSizing(2, true);
					formLayout_1.setRowAutoSizing(3, true);
					formLayout_1.setRowAutoSizing(4, true);
					group_4.setLayout(formLayout_1);
					(function(container){
						var output_2 = new cpr.controls.Output();
						output_2.value = "종류";
						output_2.style.setClasses(["label"]);
						container.addChild(output_2, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var output_3 = new cpr.controls.Output();
						output_3.value = "적용";
						output_3.style.setClasses(["label"]);
						container.addChild(output_3, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var output_4 = new cpr.controls.Output();
						output_4.value = "내용";
						output_4.style.setClasses(["label"]);
						container.addChild(output_4, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var output_5 = new cpr.controls.Output();
						output_5.value = "여백";
						output_5.unselectable = false;
						output_5.style.setClasses(["label"]);
						container.addChild(output_5, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var output_6 = new cpr.controls.Output();
						output_6.value = "0";
						output_6.style.setClasses(["pb-guideline", "guideline-green"]);
						container.addChild(output_6, {
							"colIndex": 1,
							"rowIndex": 1
						});
						var output_7 = new cpr.controls.Output();
						output_7.value = "= margin";
						container.addChild(output_7, {
							"colIndex": 2,
							"rowIndex": 1
						});
						var output_8 = new cpr.controls.Output();
						output_8.value = "간격";
						output_8.unselectable = false;
						output_8.style.setClasses(["label"]);
						container.addChild(output_8, {
							"colIndex": 0,
							"rowIndex": 2
						});
						var output_9 = new cpr.controls.Output();
						output_9.value = "0";
						output_9.style.setClasses(["pb-guideline", "guideline-orange"]);
						container.addChild(output_9, {
							"colIndex": 1,
							"rowIndex": 2
						});
						var output_10 = new cpr.controls.Output();
						output_10.value = "= spacing";
						container.addChild(output_10, {
							"colIndex": 2,
							"rowIndex": 2
						});
						var output_11 = new cpr.controls.Output();
						output_11.value = "세부 간격";
						output_11.unselectable = false;
						output_11.style.setClasses(["label"]);
						container.addChild(output_11, {
							"colIndex": 0,
							"rowIndex": 3
						});
						var output_12 = new cpr.controls.Output();
						output_12.value = "0";
						output_12.style.setClasses(["pb-guideline", "guideline-blue"]);
						container.addChild(output_12, {
							"colIndex": 1,
							"rowIndex": 3
						});
						var output_13 = new cpr.controls.Output();
						output_13.value = "간격 표시를 구분할 때 사용 ";
						container.addChild(output_13, {
							"colIndex": 2,
							"rowIndex": 3
						});
						var output_14 = new cpr.controls.Output();
						output_14.value = "기타";
						output_14.unselectable = false;
						output_14.style.setClasses(["label"]);
						container.addChild(output_14, {
							"colIndex": 0,
							"rowIndex": 4
						});
						var output_15 = new cpr.controls.Output();
						output_15.value = "0";
						output_15.style.setClasses(["pb-guideline", "guideline-purple"]);
						container.addChild(output_15, {
							"colIndex": 1,
							"rowIndex": 4
						});
						var output_16 = new cpr.controls.Output();
						output_16.value = "컨텐트 표시";
						container.addChild(output_16, {
							"colIndex": 2,
							"rowIndex": 4
						});
					})(group_4);
					container.addChild(group_4, {
						"autoSize": "height",
						"width": "400px",
						"height": "174px"
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "height",
					"width": "1420px",
					"height": "225px"
				});
			})(group_2);
			container.addChild(group_2, {
				"autoSize": "height",
				"width": "1520px",
				"height": "300px"
			});
			
			var group_5 = new cpr.controls.Container();
			group_5.style.setClasses(["pb-content"]);
			var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_5.scrollable = false;
			verticalLayout_5.spacing = 40;
			verticalLayout_5.leftMargin = 50;
			verticalLayout_5.rightMargin = 50;
			verticalLayout_5.topMargin = 50;
			verticalLayout_5.bottomMargin = 50;
			group_5.setLayout(verticalLayout_5);
			(function(container){
				var group_6 = new cpr.controls.Container();
				group_6.clipContent = false;
				var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_6.scrollable = false;
				verticalLayout_6.spacing = 14;
				group_6.setLayout(verticalLayout_6);
				(function(container){
					var userDefinedControl_3 = new udc.hk.pb.SectionTitle();
					userDefinedControl_3.title = "조회 영역 및 조회 영역 내 컨트롤";
					userDefinedControl_3.subText = "메인 환경에서 간격이 맞도록 작성되었으니 이 점 참고바랍니다.";
					userDefinedControl_3.subTextStyle = "text-blue";
					container.addChild(userDefinedControl_3, {
						"width": "1544px",
						"height": "29px"
					});
					var group_7 = new cpr.controls.Container("grpBody");
					var xYLayout_1 = new cpr.controls.layouts.XYLayout();
					xYLayout_1.scrollable = false;
					group_7.setLayout(xYLayout_1);
					(function(container){
						var output_17 = new cpr.controls.Output("optTitle");
						output_17.value = "대타이틀";
						output_17.style.setClasses(["navi-left"]);
						container.addChild(output_17, {
							"top": "20px",
							"right": "245px",
							"left": "20px",
							"height": "17px"
						});
						var group_8 = new cpr.controls.Container();
						group_8.clipContent = false;
						var xYLayout_2 = new cpr.controls.layouts.XYLayout();
						xYLayout_2.scrollable = false;
						group_8.setLayout(xYLayout_2);
						(function(container){
							var group_9 = new cpr.controls.Container("grpTopSearch");
							var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
							verticalLayout_7.scrollable = false;
							verticalLayout_7.spacing = 10;
							group_9.setLayout(verticalLayout_7);
							(function(container){
								var group_10 = new cpr.controls.Container();
								group_10.style.setClasses(["search-box"]);
								var formLayout_2 = new cpr.controls.layouts.FormLayout();
								formLayout_2.scrollable = false;
								formLayout_2.topMargin = "6px";
								formLayout_2.rightMargin = "20px";
								formLayout_2.bottomMargin = "6px";
								formLayout_2.leftMargin = "20px";
								formLayout_2.horizontalSpacing = "20px";
								formLayout_2.verticalSpacing = "8px";
								formLayout_2.setColumns(["0px", "1fr", "0px", "1fr", "0px", "1fr", "0px", "1fr", "0px", "1fr", "63px"]);
								formLayout_2.setColumnAutoSizing(0, true);
								formLayout_2.setColumnAutoSizing(2, true);
								formLayout_2.setColumnAutoSizing(4, true);
								formLayout_2.setColumnAutoSizing(6, true);
								formLayout_2.setColumnAutoSizing(8, true);
								formLayout_2.setColumnAutoSizing(10, true);
								formLayout_2.setRows(["26px", "26px"]);
								group_10.setLayout(formLayout_2);
								(function(container){
									var output_18 = new cpr.controls.Output();
									output_18.value = "항목";
									output_18.style.setClasses(["label"]);
									container.addChild(output_18, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var inputBox_1 = new cpr.controls.InputBox();
									container.addChild(inputBox_1, {
										"colIndex": 1,
										"rowIndex": 0
									});
									var output_19 = new cpr.controls.Output();
									output_19.value = "항목";
									output_19.style.setClasses(["label"]);
									container.addChild(output_19, {
										"colIndex": 2,
										"rowIndex": 0
									});
									var comboBox_1 = new cpr.controls.ComboBox();
									(function(comboBox_1){
									})(comboBox_1);
									container.addChild(comboBox_1, {
										"colIndex": 3,
										"rowIndex": 0
									});
									var output_20 = new cpr.controls.Output();
									output_20.value = "항목";
									output_20.style.setClasses(["label"]);
									container.addChild(output_20, {
										"colIndex": 4,
										"rowIndex": 0
									});
									var searchInput_1 = new cpr.controls.SearchInput();
									container.addChild(searchInput_1, {
										"colIndex": 5,
										"rowIndex": 0
									});
									var output_21 = new cpr.controls.Output();
									output_21.value = "항목";
									output_21.style.setClasses(["label"]);
									container.addChild(output_21, {
										"colIndex": 6,
										"rowIndex": 0
									});
									var dateInput_1 = new cpr.controls.DateInput();
									container.addChild(dateInput_1, {
										"colIndex": 7,
										"rowIndex": 0
									});
									var output_22 = new cpr.controls.Output();
									output_22.value = "항목";
									output_22.style.setClasses(["label"]);
									container.addChild(output_22, {
										"colIndex": 8,
										"rowIndex": 0
									});
									var group_11 = new cpr.controls.Container();
									group_11.style.setClasses(["form-inside"]);
									var formLayout_3 = new cpr.controls.layouts.FormLayout();
									formLayout_3.scrollable = false;
									formLayout_3.topMargin = "0px";
									formLayout_3.rightMargin = "0px";
									formLayout_3.bottomMargin = "0px";
									formLayout_3.leftMargin = "0px";
									formLayout_3.horizontalSpacing = "0px";
									formLayout_3.verticalSpacing = "5px";
									formLayout_3.setColumns(["80px", "5px", "1fr"]);
									formLayout_3.setRows(["1fr"]);
									group_11.setLayout(formLayout_3);
									(function(container){
										var inputBox_2 = new cpr.controls.InputBox();
										container.addChild(inputBox_2, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var output_23 = new cpr.controls.Output();
										output_23.value = "5";
										output_23.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_23, {
											"colIndex": 1,
											"rowIndex": 0
										});
										var searchInput_2 = new cpr.controls.SearchInput();
										searchInput_2.enabled = false;
										container.addChild(searchInput_2, {
											"colIndex": 2,
											"rowIndex": 0
										});
									})(group_11);
									container.addChild(group_11, {
										"colIndex": 9,
										"rowIndex": 0
									});
									var output_24 = new cpr.controls.Output();
									output_24.value = "항목";
									output_24.style.setClasses(["label"]);
									container.addChild(output_24, {
										"colIndex": 0,
										"rowIndex": 1
									});
									var inputBox_3 = new cpr.controls.InputBox();
									container.addChild(inputBox_3, {
										"colIndex": 1,
										"rowIndex": 1
									});
									var output_25 = new cpr.controls.Output();
									output_25.value = "항목";
									output_25.style.setClasses(["label"]);
									container.addChild(output_25, {
										"colIndex": 2,
										"rowIndex": 1
									});
									var group_12 = new cpr.controls.Container();
									group_12.style.setClasses(["form-inside"]);
									var formLayout_4 = new cpr.controls.layouts.FormLayout();
									formLayout_4.scrollable = false;
									formLayout_4.topMargin = "0px";
									formLayout_4.rightMargin = "0px";
									formLayout_4.bottomMargin = "0px";
									formLayout_4.leftMargin = "0px";
									formLayout_4.horizontalSpacing = "0px";
									formLayout_4.verticalSpacing = "0px";
									formLayout_4.setColumns(["1fr", "10px", "1fr"]);
									formLayout_4.setRows(["1fr"]);
									group_12.setLayout(formLayout_4);
									(function(container){
										var dateInput_2 = new cpr.controls.DateInput();
										container.addChild(dateInput_2, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var dateInput_3 = new cpr.controls.DateInput();
										container.addChild(dateInput_3, {
											"colIndex": 2,
											"rowIndex": 0
										});
										var output_26 = new cpr.controls.Output();
										output_26.value = "-";
										output_26.style.setClasses(["text-center"]);
										container.addChild(output_26, {
											"colIndex": 1,
											"rowIndex": 0
										});
										var output_27 = new cpr.controls.Output();
										output_27.value = "10";
										output_27.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_27, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_12);
									container.addChild(group_12, {
										"colIndex": 3,
										"rowIndex": 1
									});
									var output_28 = new cpr.controls.Output();
									output_28.value = "항목";
									output_28.style.setClasses(["label"]);
									container.addChild(output_28, {
										"colIndex": 4,
										"rowIndex": 1
									});
									var group_13 = new cpr.controls.Container();
									group_13.style.setClasses(["form-inside"]);
									var formLayout_5 = new cpr.controls.layouts.FormLayout();
									formLayout_5.scrollable = false;
									formLayout_5.topMargin = "0px";
									formLayout_5.rightMargin = "0px";
									formLayout_5.bottomMargin = "0px";
									formLayout_5.leftMargin = "0px";
									formLayout_5.horizontalSpacing = "0px";
									formLayout_5.verticalSpacing = "0px";
									formLayout_5.setColumns(["1fr", "5px", "1fr"]);
									formLayout_5.setRows(["1fr"]);
									group_13.setLayout(formLayout_5);
									(function(container){
										var comboBox_2 = new cpr.controls.ComboBox();
										(function(comboBox_2){
										})(comboBox_2);
										container.addChild(comboBox_2, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var output_29 = new cpr.controls.Output();
										output_29.value = "5";
										output_29.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_29, {
											"colIndex": 1,
											"rowIndex": 0
										});
										var comboBox_3 = new cpr.controls.ComboBox();
										(function(comboBox_3){
										})(comboBox_3);
										container.addChild(comboBox_3, {
											"colIndex": 2,
											"rowIndex": 0
										});
									})(group_13);
									container.addChild(group_13, {
										"colIndex": 5,
										"rowIndex": 1
									});
									var output_30 = new cpr.controls.Output();
									output_30.value = "항목";
									output_30.style.setClasses(["label"]);
									container.addChild(output_30, {
										"colIndex": 6,
										"rowIndex": 1
									});
									var inputBox_4 = new cpr.controls.InputBox();
									container.addChild(inputBox_4, {
										"colIndex": 7,
										"rowIndex": 1
									});
									var output_31 = new cpr.controls.Output();
									output_31.value = "항목";
									output_31.style.setClasses(["label"]);
									container.addChild(output_31, {
										"colIndex": 8,
										"rowIndex": 1
									});
									var checkBox_1 = new cpr.controls.CheckBox();
									checkBox_1.text = "";
									container.addChild(checkBox_1, {
										"colIndex": 9,
										"rowIndex": 1
									});
									var group_14 = new cpr.controls.Container();
									group_14.style.setClasses(["btn-flow-area"]);
									var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
									flowLayout_1.scrollable = false;
									flowLayout_1.verticalSpacing = 0;
									flowLayout_1.horizontalAlign = "right";
									flowLayout_1.lineWrap = false;
									flowLayout_1.leftMargin = 20;
									group_14.setLayout(flowLayout_1);
									(function(container){
										var button_1 = new cpr.controls.Button();
										button_1.value = "조회";
										button_1.style.setClasses(["btn-search"]);
										container.addChild(button_1, {
											"width": "49px",
											"height": "26px"
										});
										var button_2 = new cpr.controls.Button();
										button_2.value = "";
										button_2.style.setClasses(["btn-reset"]);
										container.addChild(button_2, {
											"width": "26px",
											"height": "26px"
										});
									})(group_14);
									container.addChild(group_14, {
										"colIndex": 10,
										"rowIndex": 0,
										"colSpan": 1,
										"rowSpan": 2,
										"verticalAlign": "center",
										"height": 26
									});
								})(group_10);
								container.addChild(group_10, {
									"autoSize": "height",
									"width": "1380px",
									"height": "74px"
								});
							})(group_9);
							container.addChild(group_9, {
								"top": "0px",
								"right": "0px",
								"left": "0px",
								"height": "74px"
							});
							var output_32 = new cpr.controls.Output();
							output_32.value = "20";
							output_32.style.setClasses(["pb-guideline", "guideline-green"]);
							container.addChild(output_32, {
								"top": "1px",
								"bottom": "1px",
								"left": "1px",
								"width": "20px"
							});
							var output_33 = new cpr.controls.Output();
							output_33.value = "20";
							output_33.style.setClasses(["pb-guideline", "guideline-green"]);
							container.addChild(output_33, {
								"top": "1px",
								"right": "1px",
								"bottom": "1px",
								"width": "20px"
							});
							var output_34 = new cpr.controls.Output();
							output_34.value = "6";
							output_34.style.setClasses(["pb-guideline", "guideline-green"]);
							container.addChild(output_34, {
								"top": "1px",
								"right": "0px",
								"left": "0px",
								"height": "6px"
							});
							var output_35 = new cpr.controls.Output();
							output_35.value = "6";
							output_35.style.setClasses(["pb-guideline", "guideline-green"]);
							container.addChild(output_35, {
								"right": "1px",
								"bottom": "1px",
								"left": "1px",
								"height": "6px"
							});
							var output_36 = new cpr.controls.Output();
							output_36.value = "20";
							output_36.style.setClasses(["pb-guideline", "guideline-orange"]);
							if(typeof onOutputClick == "function") {
								output_36.addEventListener("click", onOutputClick);
							}
							container.addChild(output_36, {
								"top": "7px",
								"bottom": "7px",
								"left": "44px",
								"width": "20px"
							});
							var output_37 = new cpr.controls.Output();
							output_37.value = "40";
							output_37.style.setClasses(["pb-guideline", "guideline-orange"]);
							container.addChild(output_37, {
								"top": "7px",
								"bottom": "7px",
								"left": "257px",
								"width": "40px"
							});
							var output_38 = new cpr.controls.Output();
							output_38.value = "20";
							output_38.style.setClasses(["pb-guideline", "guideline-orange"]);
							container.addChild(output_38, {
								"top": "7px",
								"right": "102px",
								"bottom": "7px",
								"width": "20px"
							});
							var output_39 = new cpr.controls.Output();
							output_39.value = "20";
							output_39.style.setClasses(["pb-guideline", "guideline-orange"]);
							container.addChild(output_39, {
								"top": "7px",
								"right": "123px",
								"bottom": "7px",
								"width": "20px"
							});
						})(group_8);
						container.addChild(group_8, {
							"top": "49px",
							"right": "20px",
							"left": "20px",
							"height": "74px"
						});
						var group_15 = new cpr.controls.Container("grpBodyGroundGrid");
						var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_8.spacing = 4;
						group_15.setLayout(verticalLayout_8);
						(function(container){
							var group_16 = new cpr.controls.Container();
							var formLayout_6 = new cpr.controls.layouts.FormLayout();
							formLayout_6.scrollable = false;
							formLayout_6.topMargin = "0px";
							formLayout_6.rightMargin = "0px";
							formLayout_6.bottomMargin = "0px";
							formLayout_6.leftMargin = "0px";
							formLayout_6.horizontalSpacing = "0px";
							formLayout_6.verticalSpacing = "0px";
							formLayout_6.setColumns(["0px", "1fr"]);
							formLayout_6.setColumnAutoSizing(0, true);
							formLayout_6.setRows(["1fr"]);
							group_16.setLayout(formLayout_6);
							(function(container){
								var group_17 = new cpr.controls.Container("grpGridTitle");
								group_17.style.setClasses(["grid-title-box"]);
								var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
								verticalLayout_9.spacing = 0;
								group_17.setLayout(verticalLayout_9);
								(function(container){
									var output_40 = new cpr.controls.Output("optGrildTitle");
									output_40.value = "그리드 타이틀";
									output_40.style.setClasses(["grid-title"]);
									container.addChild(output_40, {
										"autoSize": "none",
										"width": "300px",
										"height": "26px"
									});
								})(group_17);
								container.addChild(group_17, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var group_18 = new cpr.controls.Container("grpGridTTitleInfo");
								group_18.style.setClasses(["button-table-top-area"]);
								var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
								flowLayout_2.scrollable = false;
								flowLayout_2.horizontalAlign = "right";
								group_18.setLayout(flowLayout_2);
								(function(container){
									var output_41 = new cpr.controls.Output();
									output_41.value = "\u203b 지시문을 입력하세요.";
									output_41.style.setClasses(["info-caption"]);
									container.addChild(output_41, {
										"autoSize": "width",
										"width": "120px",
										"height": "26px"
									});
									var comboBox_4 = new cpr.controls.ComboBox();
									(function(comboBox_4){
									})(comboBox_4);
									container.addChild(comboBox_4, {
										"width": "100px",
										"height": "26px"
									});
									var button_3 = new cpr.controls.Button();
									button_3.value = "Button";
									button_3.style.setClasses(["btn-primary04"]);
									container.addChild(button_3, {
										"autoSize": "width",
										"width": "54px",
										"height": "26px"
									});
									var button_4 = new cpr.controls.Button();
									button_4.value = "Button";
									button_4.style.setClasses(["btn-secondary01"]);
									container.addChild(button_4, {
										"autoSize": "width",
										"width": "54px",
										"height": "26px"
									});
								})(group_18);
								container.addChild(group_18, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_16);
							container.addChild(group_16, {
								"autoSize": "height",
								"width": "400px",
								"height": "26px"
							});
							var grid_1 = new cpr.controls.Grid("grd1");
							grid_1.init({
								"columns": [
									{"width": "100px"},
									{"width": "100px"},
									{"width": "100px"},
									{"width": "100px"},
									{"width": "100px"}
								],
								"header": {
									"rows": [{"height": "31px"}],
									"cells": [
										{
											"constraint": {"rowIndex": 0, "colIndex": 0},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 1},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 2},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 3},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 4},
											"configurator": function(cell){
											}
										}
									]
								},
								"detail": {
									"rows": [{"height": "31px"}],
									"cells": [
										{
											"constraint": {"rowIndex": 0, "colIndex": 0},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 1},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 2},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 3},
											"configurator": function(cell){
											}
										},
										{
											"constraint": {"rowIndex": 0, "colIndex": 4},
											"configurator": function(cell){
											}
										}
									]
								}
							});
							container.addChild(grid_1, {
								"width": "400px",
								"height": "300px"
							});
						})(group_15);
						container.addChild(group_15, {
							"top": "130px",
							"right": "20px",
							"left": "20px",
							"height": "330px"
						});
						var group_19 = new cpr.controls.Container();
						group_19.style.setClasses(["button-table-area"]);
						var formLayout_7 = new cpr.controls.layouts.FormLayout();
						formLayout_7.scrollable = false;
						formLayout_7.topMargin = "0px";
						formLayout_7.rightMargin = "0px";
						formLayout_7.bottomMargin = "0px";
						formLayout_7.leftMargin = "0px";
						formLayout_7.horizontalSpacing = "0px";
						formLayout_7.verticalSpacing = "0px";
						formLayout_7.setColumns(["1fr", "43px", "1fr"]);
						formLayout_7.setColumnAutoSizing(1, true);
						formLayout_7.setRows(["1fr"]);
						group_19.setLayout(formLayout_7);
						(function(container){
							var group_20 = new cpr.controls.Container();
							group_20.style.setClasses(["button-table-bottom-left-area"]);
							var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
							flowLayout_3.scrollable = false;
							flowLayout_3.horizontalSpacing = 10;
							flowLayout_3.verticalSpacing = 0;
							flowLayout_3.lineWrap = false;
							group_20.setLayout(flowLayout_3);
							(function(container){
								var button_5 = new cpr.controls.Button();
								button_5.value = "Button";
								button_5.style.setClasses(["btn-primary04", "btn-md"]);
								container.addChild(button_5, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
								var button_6 = new cpr.controls.Button();
								button_6.value = "Button";
								button_6.style.setClasses(["btn-primary04", "btn-md"]);
								container.addChild(button_6, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
							})(group_20);
							container.addChild(group_20, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var group_21 = new cpr.controls.Container();
							group_21.style.setClasses(["button-table-bottom-right-area"]);
							var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
							flowLayout_4.scrollable = false;
							flowLayout_4.horizontalSpacing = 10;
							flowLayout_4.verticalSpacing = 0;
							flowLayout_4.horizontalAlign = "right";
							flowLayout_4.lineWrap = false;
							group_21.setLayout(flowLayout_4);
							(function(container){
								var button_7 = new cpr.controls.Button();
								button_7.value = "Button";
								button_7.style.setClasses(["btn-secondary01", "btn-md"]);
								container.addChild(button_7, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
								var button_8 = new cpr.controls.Button();
								button_8.value = "Button";
								button_8.style.setClasses(["btn-secondary01", "btn-md"]);
								container.addChild(button_8, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
							})(group_21);
							container.addChild(group_21, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var group_22 = new cpr.controls.Container();
							group_22.style.setClasses(["button-table-bottom-center-area"]);
							var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
							flowLayout_5.scrollable = false;
							flowLayout_5.horizontalSpacing = 10;
							flowLayout_5.verticalSpacing = 0;
							flowLayout_5.horizontalAlign = "center";
							group_22.setLayout(flowLayout_5);
							(function(container){
								var button_9 = new cpr.controls.Button();
								button_9.value = "Button";
								button_9.style.setClasses(["btn-primary03", "btn-md"]);
								container.addChild(button_9, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
							})(group_22);
							container.addChild(group_22, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_19);
						container.addChild(group_19, {
							"top": "468px",
							"right": "20px",
							"left": "20px",
							"height": "30px"
						});
						var group_23 = new cpr.controls.Container("grpNavi");
						group_23.style.setClasses(["breadcrumbs"]);
						var flowLayout_6 = new cpr.controls.layouts.FlowLayout();
						flowLayout_6.scrollable = false;
						flowLayout_6.horizontalSpacing = 5;
						flowLayout_6.verticalSpacing = 0;
						flowLayout_6.horizontalAlign = "right";
						flowLayout_6.lineWrap = false;
						group_23.setLayout(flowLayout_6);
						(function(container){
							var group_24 = new cpr.controls.Container();
							var xYLayout_3 = new cpr.controls.layouts.XYLayout();
							xYLayout_3.scrollable = false;
							group_24.setLayout(xYLayout_3);
							(function(container){
								var image_1 = new cpr.controls.Image();
								image_1.src = "../theme/hk/images/com/main/ico-comm-map-home-10.png";
								(function(image_1){
								})(image_1);
								container.addChild(image_1, {
									"top": "4px",
									"width": "10px",
									"height": "10px",
									"left": "calc(50% - 5px)"
								});
							})(group_24);
							container.addChild(group_24, {
								"width": "10px",
								"height": "17px"
							});
							var output_42 = new cpr.controls.Output();
							output_42.value = "1Depth";
							output_42.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_42, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
							var output_43 = new cpr.controls.Output();
							output_43.value = "2Depth";
							output_43.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_43, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
							var output_44 = new cpr.controls.Output();
							output_44.value = "3Depth";
							output_44.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_44, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
							var output_45 = new cpr.controls.Output();
							output_45.value = "4Depth";
							output_45.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_45, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
						})(group_23);
						container.addChild(group_23, {
							"top": "20px",
							"right": "20px",
							"width": "225px",
							"height": "17px"
						});
					})(group_7);
					container.addChild(group_7, {
						"autoSize": "none",
						"width": "1420px",
						"height": "518px"
					});
				})(group_6);
				container.addChild(group_6, {
					"autoSize": "height",
					"width": "1544px",
					"height": "632px"
				});
			})(group_5);
			container.addChild(group_5, {
				"autoSize": "height",
				"width": "1520px",
				"height": "716px"
			});
			
			var group_25 = new cpr.controls.Container();
			group_25.style.setClasses(["pb-content"]);
			var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_10.scrollable = false;
			verticalLayout_10.spacing = 40;
			verticalLayout_10.leftMargin = 50;
			verticalLayout_10.rightMargin = 50;
			verticalLayout_10.topMargin = 50;
			verticalLayout_10.bottomMargin = 50;
			group_25.setLayout(verticalLayout_10);
			(function(container){
				var group_26 = new cpr.controls.Container();
				group_26.clipContent = false;
				var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_11.scrollable = false;
				verticalLayout_11.spacing = 14;
				group_26.setLayout(verticalLayout_11);
				(function(container){
					var userDefinedControl_4 = new udc.hk.pb.SectionTitle();
					userDefinedControl_4.title = "폼 및 폼 내 컨트롤";
					userDefinedControl_4.subText = "폼의 유형이 출력형인 경우과 입력형인 경우 여백과 간격이 다르게 적용됩니다.";
					userDefinedControl_4.subTextStyle = "text-red";
					container.addChild(userDefinedControl_4, {
						"width": "1544px",
						"height": "29px"
					});
					var group_27 = new cpr.controls.Container();
					var xYLayout_4 = new cpr.controls.layouts.XYLayout();
					xYLayout_4.scrollable = false;
					group_27.setLayout(xYLayout_4);
					(function(container){
						var output_46 = new cpr.controls.Output();
						output_46.value = "대타이틀";
						output_46.style.setClasses(["navi-left"]);
						container.addChild(output_46, {
							"top": "20px",
							"right": "245px",
							"left": "20px",
							"height": "17px"
						});
						var group_28 = new cpr.controls.Container();
						var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_12.spacing = 10;
						group_28.setLayout(verticalLayout_12);
						(function(container){
							var group_29 = new cpr.controls.Container();
							group_29.style.setClasses(["search-box"]);
							var formLayout_8 = new cpr.controls.layouts.FormLayout();
							formLayout_8.scrollable = false;
							formLayout_8.topMargin = "6px";
							formLayout_8.rightMargin = "20px";
							formLayout_8.bottomMargin = "6px";
							formLayout_8.leftMargin = "20px";
							formLayout_8.horizontalSpacing = "20px";
							formLayout_8.verticalSpacing = "8px";
							formLayout_8.setColumns(["0px", "1fr", "0px", "1fr", "0px", "1fr", "0px", "1fr", "0px", "1fr", "63px"]);
							formLayout_8.setColumnAutoSizing(0, true);
							formLayout_8.setColumnAutoSizing(2, true);
							formLayout_8.setColumnAutoSizing(4, true);
							formLayout_8.setColumnAutoSizing(6, true);
							formLayout_8.setColumnAutoSizing(8, true);
							formLayout_8.setColumnAutoSizing(10, true);
							formLayout_8.setRows(["26px", "26px"]);
							group_29.setLayout(formLayout_8);
							(function(container){
								var output_47 = new cpr.controls.Output();
								output_47.value = "항목";
								output_47.style.setClasses(["label"]);
								container.addChild(output_47, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var inputBox_5 = new cpr.controls.InputBox();
								container.addChild(inputBox_5, {
									"colIndex": 1,
									"rowIndex": 0
								});
								var output_48 = new cpr.controls.Output();
								output_48.value = "항목";
								output_48.style.setClasses(["label"]);
								container.addChild(output_48, {
									"colIndex": 2,
									"rowIndex": 0
								});
								var comboBox_5 = new cpr.controls.ComboBox();
								(function(comboBox_5){
								})(comboBox_5);
								container.addChild(comboBox_5, {
									"colIndex": 3,
									"rowIndex": 0
								});
								var output_49 = new cpr.controls.Output();
								output_49.value = "항목";
								output_49.style.setClasses(["label"]);
								container.addChild(output_49, {
									"colIndex": 4,
									"rowIndex": 0
								});
								var searchInput_3 = new cpr.controls.SearchInput();
								container.addChild(searchInput_3, {
									"colIndex": 5,
									"rowIndex": 0
								});
								var output_50 = new cpr.controls.Output();
								output_50.value = "항목";
								output_50.style.setClasses(["label"]);
								container.addChild(output_50, {
									"colIndex": 6,
									"rowIndex": 0
								});
								var dateInput_4 = new cpr.controls.DateInput();
								container.addChild(dateInput_4, {
									"colIndex": 7,
									"rowIndex": 0
								});
								var output_51 = new cpr.controls.Output();
								output_51.value = "항목";
								output_51.style.setClasses(["label"]);
								container.addChild(output_51, {
									"colIndex": 8,
									"rowIndex": 0
								});
								var group_30 = new cpr.controls.Container();
								group_30.style.setClasses(["form-inside"]);
								var formLayout_9 = new cpr.controls.layouts.FormLayout();
								formLayout_9.scrollable = false;
								formLayout_9.topMargin = "0px";
								formLayout_9.rightMargin = "0px";
								formLayout_9.bottomMargin = "0px";
								formLayout_9.leftMargin = "0px";
								formLayout_9.horizontalSpacing = "5px";
								formLayout_9.verticalSpacing = "5px";
								formLayout_9.setColumns(["80px", "1fr"]);
								formLayout_9.setRows(["1fr"]);
								group_30.setLayout(formLayout_9);
								(function(container){
									var inputBox_6 = new cpr.controls.InputBox();
									container.addChild(inputBox_6, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var searchInput_4 = new cpr.controls.SearchInput();
									searchInput_4.enabled = false;
									container.addChild(searchInput_4, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_30);
								container.addChild(group_30, {
									"colIndex": 9,
									"rowIndex": 0
								});
								var output_52 = new cpr.controls.Output();
								output_52.value = "항목";
								output_52.style.setClasses(["label"]);
								container.addChild(output_52, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var inputBox_7 = new cpr.controls.InputBox();
								container.addChild(inputBox_7, {
									"colIndex": 1,
									"rowIndex": 1
								});
								var output_53 = new cpr.controls.Output();
								output_53.value = "항목";
								output_53.style.setClasses(["label"]);
								container.addChild(output_53, {
									"colIndex": 2,
									"rowIndex": 1
								});
								var group_31 = new cpr.controls.Container();
								group_31.style.setClasses(["form-inside"]);
								var formLayout_10 = new cpr.controls.layouts.FormLayout();
								formLayout_10.scrollable = false;
								formLayout_10.topMargin = "0px";
								formLayout_10.rightMargin = "0px";
								formLayout_10.bottomMargin = "0px";
								formLayout_10.leftMargin = "0px";
								formLayout_10.horizontalSpacing = "0px";
								formLayout_10.verticalSpacing = "0px";
								formLayout_10.setColumns(["1fr", "10px", "1fr"]);
								formLayout_10.setRows(["1fr"]);
								group_31.setLayout(formLayout_10);
								(function(container){
									var dateInput_5 = new cpr.controls.DateInput();
									container.addChild(dateInput_5, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var dateInput_6 = new cpr.controls.DateInput();
									container.addChild(dateInput_6, {
										"colIndex": 2,
										"rowIndex": 0
									});
									var output_54 = new cpr.controls.Output();
									output_54.value = "-";
									output_54.style.setClasses(["text-center"]);
									container.addChild(output_54, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_31);
								container.addChild(group_31, {
									"colIndex": 3,
									"rowIndex": 1
								});
								var output_55 = new cpr.controls.Output();
								output_55.value = "항목";
								output_55.style.setClasses(["label"]);
								container.addChild(output_55, {
									"colIndex": 4,
									"rowIndex": 1
								});
								var group_32 = new cpr.controls.Container();
								group_32.style.setClasses(["form-inside"]);
								var formLayout_11 = new cpr.controls.layouts.FormLayout();
								formLayout_11.scrollable = false;
								formLayout_11.topMargin = "0px";
								formLayout_11.rightMargin = "0px";
								formLayout_11.bottomMargin = "0px";
								formLayout_11.leftMargin = "0px";
								formLayout_11.horizontalSpacing = "5px";
								formLayout_11.verticalSpacing = "5px";
								formLayout_11.setColumns(["1fr", "1fr"]);
								formLayout_11.setRows(["1fr"]);
								group_32.setLayout(formLayout_11);
								(function(container){
									var comboBox_6 = new cpr.controls.ComboBox();
									(function(comboBox_6){
									})(comboBox_6);
									container.addChild(comboBox_6, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var comboBox_7 = new cpr.controls.ComboBox();
									(function(comboBox_7){
									})(comboBox_7);
									container.addChild(comboBox_7, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_32);
								container.addChild(group_32, {
									"colIndex": 5,
									"rowIndex": 1
								});
								var output_56 = new cpr.controls.Output();
								output_56.value = "항목";
								output_56.style.setClasses(["label"]);
								container.addChild(output_56, {
									"colIndex": 6,
									"rowIndex": 1
								});
								var inputBox_8 = new cpr.controls.InputBox();
								container.addChild(inputBox_8, {
									"colIndex": 7,
									"rowIndex": 1
								});
								var output_57 = new cpr.controls.Output();
								output_57.value = "항목";
								output_57.style.setClasses(["label"]);
								container.addChild(output_57, {
									"colIndex": 8,
									"rowIndex": 1
								});
								var checkBox_2 = new cpr.controls.CheckBox();
								checkBox_2.text = "";
								container.addChild(checkBox_2, {
									"colIndex": 9,
									"rowIndex": 1
								});
								var group_33 = new cpr.controls.Container();
								group_33.style.setClasses(["btn-flow-area"]);
								var flowLayout_7 = new cpr.controls.layouts.FlowLayout();
								flowLayout_7.scrollable = false;
								flowLayout_7.verticalSpacing = 0;
								flowLayout_7.horizontalAlign = "right";
								flowLayout_7.lineWrap = false;
								flowLayout_7.leftMargin = 20;
								group_33.setLayout(flowLayout_7);
								(function(container){
									var button_10 = new cpr.controls.Button();
									button_10.value = "조회";
									button_10.style.setClasses(["btn-search"]);
									container.addChild(button_10, {
										"width": "49px",
										"height": "26px"
									});
									var button_11 = new cpr.controls.Button();
									button_11.value = "";
									button_11.style.setClasses(["btn-reset"]);
									container.addChild(button_11, {
										"width": "26px",
										"height": "26px"
									});
								})(group_33);
								container.addChild(group_33, {
									"colIndex": 10,
									"rowIndex": 0,
									"colSpan": 1,
									"rowSpan": 2,
									"verticalAlign": "center",
									"height": 26
								});
							})(group_29);
							container.addChild(group_29, {
								"autoSize": "height",
								"width": "1380px",
								"height": "74px"
							});
						})(group_28);
						container.addChild(group_28, {
							"top": "49px",
							"right": "20px",
							"left": "20px",
							"height": "74px"
						});
						var group_34 = new cpr.controls.Container();
						group_34.clipContent = false;
						var verticalLayout_13 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_13.scrollable = false;
						verticalLayout_13.spacing = 4;
						group_34.setLayout(verticalLayout_13);
						(function(container){
							var group_35 = new cpr.controls.Container();
							var formLayout_12 = new cpr.controls.layouts.FormLayout();
							formLayout_12.scrollable = false;
							formLayout_12.topMargin = "0px";
							formLayout_12.rightMargin = "0px";
							formLayout_12.bottomMargin = "0px";
							formLayout_12.leftMargin = "0px";
							formLayout_12.horizontalSpacing = "0px";
							formLayout_12.verticalSpacing = "0px";
							formLayout_12.setColumns(["0px", "1fr"]);
							formLayout_12.setColumnAutoSizing(0, true);
							formLayout_12.setRows(["1fr"]);
							group_35.setLayout(formLayout_12);
							(function(container){
								var group_36 = new cpr.controls.Container();
								group_36.style.setClasses(["form-title-box"]);
								var verticalLayout_14 = new cpr.controls.layouts.VerticalLayout();
								verticalLayout_14.spacing = 0;
								group_36.setLayout(verticalLayout_14);
								(function(container){
									var output_58 = new cpr.controls.Output();
									output_58.value = "폼 타이틀";
									output_58.style.setClasses(["form-title"]);
									container.addChild(output_58, {
										"autoSize": "none",
										"width": "300px",
										"height": "26px"
									});
								})(group_36);
								container.addChild(group_36, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var group_37 = new cpr.controls.Container();
								group_37.style.setClasses(["button-table-top-area"]);
								var flowLayout_8 = new cpr.controls.layouts.FlowLayout();
								flowLayout_8.scrollable = false;
								flowLayout_8.horizontalSpacing = 0;
								flowLayout_8.horizontalAlign = "right";
								group_37.setLayout(flowLayout_8);
								(function(container){
									var output_59 = new cpr.controls.Output();
									output_59.value = "\u203b 지시문을 입력하세요.";
									output_59.style.setClasses(["info-caption"]);
									container.addChild(output_59, {
										"autoSize": "width",
										"width": "120px",
										"height": "26px"
									});
									var output_60 = new cpr.controls.Output();
									output_60.value = "5";
									output_60.style.setClasses(["pb-guideline", "guideline-blue"]);
									container.addChild(output_60, {
										"autoSize": "none",
										"width": "5px",
										"height": "26px"
									});
									var comboBox_8 = new cpr.controls.ComboBox();
									(function(comboBox_8){
									})(comboBox_8);
									container.addChild(comboBox_8, {
										"width": "100px",
										"height": "26px"
									});
									var output_61 = new cpr.controls.Output();
									output_61.value = "5";
									output_61.style.setClasses(["pb-guideline", "guideline-blue"]);
									container.addChild(output_61, {
										"autoSize": "none",
										"width": "5px",
										"height": "26px"
									});
									var button_12 = new cpr.controls.Button();
									button_12.value = "Button";
									button_12.style.setClasses(["btn-primary04"]);
									container.addChild(button_12, {
										"autoSize": "width",
										"width": "54px",
										"height": "26px"
									});
									var output_62 = new cpr.controls.Output();
									output_62.value = "5";
									output_62.style.setClasses(["pb-guideline", "guideline-blue"]);
									container.addChild(output_62, {
										"autoSize": "none",
										"width": "5px",
										"height": "26px"
									});
									var button_13 = new cpr.controls.Button();
									button_13.value = "Button";
									button_13.style.setClasses(["btn-secondary01"]);
									container.addChild(button_13, {
										"autoSize": "width",
										"width": "54px",
										"height": "26px"
									});
								})(group_37);
								container.addChild(group_37, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_35);
							container.addChild(group_35, {
								"autoSize": "height",
								"width": "400px",
								"height": "26px"
							});
							var group_38 = new cpr.controls.Container();
							group_38.clipContent = false;
							var xYLayout_5 = new cpr.controls.layouts.XYLayout();
							xYLayout_5.scrollable = false;
							group_38.setLayout(xYLayout_5);
							(function(container){
								var group_39 = new cpr.controls.Container();
								group_39.style.setClasses(["form-normal", "cl-form-group"]);
								var formLayout_13 = new cpr.controls.layouts.FormLayout();
								formLayout_13.scrollable = false;
								formLayout_13.topMargin = "2px";
								formLayout_13.rightMargin = "5px";
								formLayout_13.bottomMargin = "2px";
								formLayout_13.leftMargin = "5px";
								formLayout_13.horizontalSpacing = "11px";
								formLayout_13.verticalSpacing = "5px";
								formLayout_13.horizontalSeparatorWidth = 1;
								formLayout_13.verticalSeparatorWidth = 1;
								formLayout_13.setColumns(["110px", "1fr", "110px", "1fr", "110px", "1fr"]);
								formLayout_13.setUseColumnShade(0, true);
								formLayout_13.setUseColumnShade(2, true);
								formLayout_13.setUseColumnShade(4, true);
								formLayout_13.setColumnAutoSizing(0, true);
								formLayout_13.setColumnAutoSizing(2, true);
								formLayout_13.setColumnAutoSizing(4, true);
								formLayout_13.setRows(["26px", "1fr"]);
								formLayout_13.setRowAutoSizing(0, true);
								group_39.setLayout(formLayout_13);
								(function(container){
									var output_63 = new cpr.controls.Output();
									output_63.value = "항목";
									output_63.style.setClasses(["label"]);
									container.addChild(output_63, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var output_64 = new cpr.controls.Output();
									output_64.value = "문장 또는 상품명은 왼쪽 정렬입니다.";
									container.addChild(output_64, {
										"colIndex": 1,
										"rowIndex": 0
									});
									var output_65 = new cpr.controls.Output();
									output_65.value = "항목";
									output_65.style.setClasses(["label"]);
									container.addChild(output_65, {
										"colIndex": 2,
										"rowIndex": 0
									});
									var group_40 = new cpr.controls.Container();
									group_40.style.setClasses(["form-inside"]);
									var flowLayout_9 = new cpr.controls.layouts.FlowLayout();
									flowLayout_9.scrollable = false;
									flowLayout_9.horizontalSpacing = 0;
									flowLayout_9.verticalSpacing = 8;
									flowLayout_9.horizontalAlign = "center";
									group_40.setLayout(flowLayout_9);
									(function(container){
										var output_66 = new cpr.controls.Output();
										output_66.value = "단락";
										container.addChild(output_66, {
											"autoSize": "both",
											"width": "100px",
											"height": "26px",
											"minHeight": 26
										});
										var output_67 = new cpr.controls.Output();
										output_67.value = "20";
										output_67.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_67, {
											"autoSize": "none",
											"width": "20px",
											"height": "26px"
										});
										var output_68 = new cpr.controls.Output();
										output_68.value = "단락 사이 간격";
										container.addChild(output_68, {
											"autoSize": "both",
											"width": "100px",
											"height": "26px",
											"minHeight": 26
										});
									})(group_40);
									container.addChild(group_40, {
										"colIndex": 3,
										"rowIndex": 0
									});
									var output_69 = new cpr.controls.Output();
									output_69.value = "항목";
									output_69.style.setClasses(["label"]);
									container.addChild(output_69, {
										"colIndex": 4,
										"rowIndex": 0
									});
									var output_70 = new cpr.controls.Output();
									output_70.value = "단어";
									output_70.style.setClasses(["text-center"]);
									container.addChild(output_70, {
										"colIndex": 5,
										"rowIndex": 0
									});
									var output_71 = new cpr.controls.Output();
									output_71.value = "항목";
									output_71.style.setClasses(["label"]);
									container.addChild(output_71, {
										"colIndex": 0,
										"rowIndex": 1
									});
									var group_41 = new cpr.controls.Container();
									group_41.childCombinatorClass = "form-inner-spacing";
									group_41.style.setClasses(["form-inside"]);
									var flowLayout_10 = new cpr.controls.layouts.FlowLayout();
									flowLayout_10.scrollable = false;
									flowLayout_10.horizontalSpacing = 20;
									flowLayout_10.verticalSpacing = 8;
									group_41.setLayout(flowLayout_10);
									(function(container){
										var output_72 = new cpr.controls.Output();
										output_72.value = "불릿이 있을 경우";
										output_72.style.setClasses(["blt-txt"]);
										container.addChild(output_72, {
											"autoSize": "both",
											"width": "100px",
											"height": "26px"
										});
										var output_73 = new cpr.controls.Output();
										output_73.value = "불릿이 있을 경우";
										output_73.style.setClasses(["blt-txt"]);
										container.addChild(output_73, {
											"autoSize": "both",
											"width": "100px",
											"height": "26px"
										});
									})(group_41);
									container.addChild(group_41, {
										"colIndex": 1,
										"rowIndex": 1
									});
									var output_74 = new cpr.controls.Output();
									output_74.value = "항목";
									output_74.style.setClasses(["label"]);
									container.addChild(output_74, {
										"colIndex": 2,
										"rowIndex": 1
									});
									var group_42 = new cpr.controls.Container();
									group_42.childCombinatorClass = "form-inner-spacing";
									group_42.style.setClasses(["form-inside"]);
									var verticalLayout_15 = new cpr.controls.layouts.VerticalLayout();
									verticalLayout_15.spacing = 0;
									group_42.setLayout(verticalLayout_15);
									(function(container){
										var output_75 = new cpr.controls.Output();
										output_75.value = "데이터가 문단으로 이루어질 경우입니다.";
										container.addChild(output_75, {
											"autoSize": "height",
											"width": "521px",
											"height": "14px"
										});
										var output_76 = new cpr.controls.Output();
										output_76.value = "8";
										output_76.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_76, {
											"autoSize": "none",
											"width": "20px",
											"height": "8px"
										});
										var output_77 = new cpr.controls.Output();
										output_77.value = "데이터가 문단으로 이루어질 경우입니다.";
										container.addChild(output_77, {
											"autoSize": "height",
											"width": "521px",
											"height": "14px"
										});
									})(group_42);
									container.addChild(group_42, {
										"colIndex": 3,
										"rowIndex": 1
									});
									var output_78 = new cpr.controls.Output();
									output_78.value = "항목";
									output_78.style.setClasses(["label"]);
									container.addChild(output_78, {
										"colIndex": 4,
										"rowIndex": 1
									});
									var output_79 = new cpr.controls.Output();
									output_79.value = "단어";
									output_79.style.setClasses(["text-center"]);
									container.addChild(output_79, {
										"colIndex": 5,
										"rowIndex": 1
									});
								})(group_39);
								container.addChild(group_39, {
									"top": "0px",
									"right": "0px",
									"left": "0px",
									"height": "86px"
								});
								var group_43 = new cpr.controls.Container();
								group_43.style.setClasses(["form-normal", "cl-form-group"]);
								var formLayout_14 = new cpr.controls.layouts.FormLayout();
								formLayout_14.scrollable = false;
								formLayout_14.topMargin = "2px";
								formLayout_14.rightMargin = "5px";
								formLayout_14.bottomMargin = "2px";
								formLayout_14.leftMargin = "5px";
								formLayout_14.horizontalSpacing = "11px";
								formLayout_14.verticalSpacing = "5px";
								formLayout_14.horizontalSeparatorWidth = 1;
								formLayout_14.verticalSeparatorWidth = 1;
								formLayout_14.setColumns(["110px", "1fr", "110px", "1fr", "110px", "1fr"]);
								formLayout_14.setUseColumnShade(0, true);
								formLayout_14.setUseColumnShade(2, true);
								formLayout_14.setUseColumnShade(4, true);
								formLayout_14.setColumnAutoSizing(0, true);
								formLayout_14.setColumnAutoSizing(2, true);
								formLayout_14.setColumnAutoSizing(4, true);
								formLayout_14.setRows(["26px", "26px", "26px", "26px"]);
								group_43.setLayout(formLayout_14);
								(function(container){
									var output_80 = new cpr.controls.Output();
									output_80.value = "항목";
									output_80.style.setClasses(["label"]);
									container.addChild(output_80, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var inputBox_9 = new cpr.controls.InputBox();
									container.addChild(inputBox_9, {
										"colIndex": 1,
										"rowIndex": 0
									});
									var output_81 = new cpr.controls.Output();
									output_81.value = "항목";
									output_81.style.setClasses(["label"]);
									container.addChild(output_81, {
										"colIndex": 2,
										"rowIndex": 0
									});
									var output_82 = new cpr.controls.Output();
									output_82.value = "항목";
									output_82.style.setClasses(["label"]);
									container.addChild(output_82, {
										"colIndex": 4,
										"rowIndex": 0
									});
									var output_83 = new cpr.controls.Output();
									output_83.value = "항목";
									output_83.style.setClasses(["label"]);
									container.addChild(output_83, {
										"colIndex": 0,
										"rowIndex": 1
									});
									var searchInput_5 = new cpr.controls.SearchInput();
									container.addChild(searchInput_5, {
										"colIndex": 1,
										"rowIndex": 1
									});
									var output_84 = new cpr.controls.Output();
									output_84.value = "항목";
									output_84.style.setClasses(["label"]);
									container.addChild(output_84, {
										"colIndex": 2,
										"rowIndex": 1
									});
									var dateInput_7 = new cpr.controls.DateInput();
									container.addChild(dateInput_7, {
										"colIndex": 3,
										"rowIndex": 1,
										"horizontalAlign": "left",
										"width": 120
									});
									var output_85 = new cpr.controls.Output();
									output_85.value = "항목";
									output_85.style.setClasses(["label"]);
									container.addChild(output_85, {
										"colIndex": 4,
										"rowIndex": 1
									});
									var group_44 = new cpr.controls.Container();
									group_44.style.setClasses(["form-inside"]);
									var formLayout_15 = new cpr.controls.layouts.FormLayout();
									formLayout_15.scrollable = false;
									formLayout_15.topMargin = "0px";
									formLayout_15.rightMargin = "0px";
									formLayout_15.bottomMargin = "0px";
									formLayout_15.leftMargin = "0px";
									formLayout_15.horizontalSpacing = "0px";
									formLayout_15.verticalSpacing = "0px";
									formLayout_15.setColumns(["1fr", "10px", "1fr"]);
									formLayout_15.setRows(["1fr"]);
									group_44.setLayout(formLayout_15);
									(function(container){
										var output_86 = new cpr.controls.Output();
										output_86.value = "-";
										output_86.style.setClasses(["text-center"]);
										container.addChild(output_86, {
											"colIndex": 1,
											"rowIndex": 0
										});
										var dateInput_8 = new cpr.controls.DateInput();
										container.addChild(dateInput_8, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var dateInput_9 = new cpr.controls.DateInput();
										container.addChild(dateInput_9, {
											"colIndex": 2,
											"rowIndex": 0
										});
										var output_87 = new cpr.controls.Output();
										output_87.value = "10";
										output_87.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_87, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_44);
									container.addChild(group_44, {
										"colIndex": 5,
										"rowIndex": 1
									});
									var output_88 = new cpr.controls.Output();
									output_88.value = "항목";
									output_88.style.setClasses(["label"]);
									container.addChild(output_88, {
										"colIndex": 4,
										"rowIndex": 2
									});
									var output_89 = new cpr.controls.Output();
									output_89.value = "항목";
									output_89.style.setClasses(["label"]);
									container.addChild(output_89, {
										"colIndex": 4,
										"rowIndex": 3
									});
									var output_90 = new cpr.controls.Output();
									output_90.value = "항목";
									output_90.style.setClasses(["label"]);
									container.addChild(output_90, {
										"colIndex": 2,
										"rowIndex": 2
									});
									var output_91 = new cpr.controls.Output();
									output_91.value = "항목";
									output_91.style.setClasses(["label"]);
									container.addChild(output_91, {
										"colIndex": 2,
										"rowIndex": 3
									});
									var output_92 = new cpr.controls.Output();
									output_92.value = "항목";
									output_92.style.setClasses(["label"]);
									container.addChild(output_92, {
										"colIndex": 0,
										"rowIndex": 3
									});
									var output_93 = new cpr.controls.Output();
									output_93.value = "항목";
									output_93.style.setClasses(["label"]);
									container.addChild(output_93, {
										"colIndex": 0,
										"rowIndex": 2
									});
									var checkBoxGroup_1 = new cpr.controls.CheckBoxGroup();
									checkBoxGroup_1.colCount = -1;
									(function(checkBoxGroup_1){
										checkBoxGroup_1.addItem(new cpr.controls.Item("아이템", "value1"));
										checkBoxGroup_1.addItem(new cpr.controls.Item("아이템", "value2"));
										checkBoxGroup_1.addItem(new cpr.controls.Item("아이템", "value3"));
									})(checkBoxGroup_1);
									container.addChild(checkBoxGroup_1, {
										"colIndex": 1,
										"rowIndex": 2
									});
									var radioButton_1 = new cpr.controls.RadioButton();
									(function(radioButton_1){
										radioButton_1.addItem(new cpr.controls.Item("아이템", "value1"));
										radioButton_1.addItem(new cpr.controls.Item("아이템", "value2"));
										radioButton_1.addItem(new cpr.controls.Item("아이템", "value3"));
									})(radioButton_1);
									container.addChild(radioButton_1, {
										"colIndex": 3,
										"rowIndex": 2
									});
									var group_45 = new cpr.controls.Container();
									group_45.style.setClasses(["form-inside"]);
									var flowLayout_11 = new cpr.controls.layouts.FlowLayout();
									flowLayout_11.scrollable = false;
									flowLayout_11.horizontalSpacing = 0;
									flowLayout_11.verticalSpacing = 2;
									group_45.setLayout(flowLayout_11);
									(function(container){
										var checkBoxGroup_2 = new cpr.controls.CheckBoxGroup();
										checkBoxGroup_2.colCount = -1;
										(function(checkBoxGroup_2){
											checkBoxGroup_2.addItem(new cpr.controls.Item("아이템", "value1"));
											checkBoxGroup_2.addItem(new cpr.controls.Item("아이템", "value2"));
										})(checkBoxGroup_2);
										container.addChild(checkBoxGroup_2, {
											"autoSize": "both",
											"width": "120px",
											"height": "26px",
											"minHeight": 26
										});
										var output_94 = new cpr.controls.Output();
										output_94.value = "40";
										output_94.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_94, {
											"autoSize": "none",
											"width": "40px",
											"height": "26px"
										});
										var radioButton_2 = new cpr.controls.RadioButton();
										(function(radioButton_2){
											radioButton_2.addItem(new cpr.controls.Item("아이템", "value1"));
											radioButton_2.addItem(new cpr.controls.Item("아이템", "value2"));
										})(radioButton_2);
										container.addChild(radioButton_2, {
											"autoSize": "both",
											"width": "120px",
											"height": "26px",
											"minHeight": 26
										});
									})(group_45);
									container.addChild(group_45, {
										"colIndex": 5,
										"rowIndex": 2
									});
									var group_46 = new cpr.controls.Container();
									group_46.style.setClasses(["form-inside"]);
									var flowLayout_12 = new cpr.controls.layouts.FlowLayout();
									flowLayout_12.scrollable = false;
									flowLayout_12.horizontalSpacing = 20;
									flowLayout_12.verticalSpacing = 2;
									group_46.setLayout(flowLayout_12);
									(function(container){
										var output_95 = new cpr.controls.Output();
										output_95.value = "텍스트";
										container.addChild(output_95, {
											"autoSize": "width",
											"width": "100px",
											"height": "26px"
										});
										var checkBoxGroup_3 = new cpr.controls.CheckBoxGroup();
										checkBoxGroup_3.colCount = -1;
										(function(checkBoxGroup_3){
											checkBoxGroup_3.addItem(new cpr.controls.Item("아이템", "value1"));
											checkBoxGroup_3.addItem(new cpr.controls.Item("아이템", "value2"));
											checkBoxGroup_3.addItem(new cpr.controls.Item("아이템", "value3"));
										})(checkBoxGroup_3);
										container.addChild(checkBoxGroup_3, {
											"autoSize": "both",
											"width": "200px",
											"height": "26px",
											"minHeight": 26
										});
									})(group_46);
									container.addChild(group_46, {
										"colIndex": 1,
										"rowIndex": 3
									});
									var group_47 = new cpr.controls.Container();
									group_47.style.setClasses(["form-inside"]);
									var flowLayout_13 = new cpr.controls.layouts.FlowLayout();
									flowLayout_13.scrollable = false;
									flowLayout_13.horizontalSpacing = 0;
									flowLayout_13.verticalSpacing = 2;
									group_47.setLayout(flowLayout_13);
									(function(container){
										var output_96 = new cpr.controls.Output();
										output_96.value = "텍스트";
										container.addChild(output_96, {
											"autoSize": "width",
											"width": "100px",
											"height": "26px"
										});
										var output_97 = new cpr.controls.Output();
										output_97.value = "10";
										output_97.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_97, {
											"autoSize": "none",
											"width": "10px",
											"height": "26px"
										});
										var button_14 = new cpr.controls.Button();
										button_14.value = "Button";
										button_14.style.setClasses(["btn-primary03"]);
										container.addChild(button_14, {
											"autoSize": "width",
											"width": "58px",
											"height": "26px"
										});
									})(group_47);
									container.addChild(group_47, {
										"colIndex": 3,
										"rowIndex": 3
									});
									var group_48 = new cpr.controls.Container();
									group_48.style.setClasses(["form-inside"]);
									var flowLayout_14 = new cpr.controls.layouts.FlowLayout();
									flowLayout_14.scrollable = false;
									flowLayout_14.horizontalSpacing = 0;
									flowLayout_14.verticalSpacing = 2;
									group_48.setLayout(flowLayout_14);
									(function(container){
										var group_49 = new cpr.controls.Container();
										group_49.style.setClasses(["form-inside"]);
										var flowLayout_15 = new cpr.controls.layouts.FlowLayout();
										flowLayout_15.scrollable = false;
										flowLayout_15.horizontalSpacing = 0;
										flowLayout_15.verticalSpacing = 0;
										flowLayout_15.lineWrap = false;
										group_49.setLayout(flowLayout_15);
										(function(container){
											var button_15 = new cpr.controls.Button();
											button_15.value = "Button";
											button_15.style.setClasses(["btn-primary03"]);
											container.addChild(button_15, {
												"autoSize": "width",
												"width": "58px",
												"height": "26px"
											});
											var output_98 = new cpr.controls.Output();
											output_98.value = "5";
											output_98.style.setClasses(["pb-guideline", "guideline-blue"]);
											container.addChild(output_98, {
												"autoSize": "none",
												"width": "5px",
												"height": "26px"
											});
											var button_16 = new cpr.controls.Button();
											button_16.value = "Button";
											button_16.style.setClasses(["btn-primary03"]);
											container.addChild(button_16, {
												"autoSize": "width",
												"width": "58px",
												"height": "26px"
											});
										})(group_49);
										container.addChild(group_49, {
											"autoSize": "both",
											"width": "121px",
											"height": "26px"
										});
										var output_99 = new cpr.controls.Output();
										output_99.value = "20";
										output_99.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_99, {
											"autoSize": "none",
											"width": "20px",
											"height": "26px"
										});
										var group_50 = new cpr.controls.Container();
										group_50.style.setClasses(["form-inside"]);
										var flowLayout_16 = new cpr.controls.layouts.FlowLayout();
										flowLayout_16.scrollable = false;
										flowLayout_16.horizontalSpacing = 0;
										flowLayout_16.verticalSpacing = 0;
										flowLayout_16.lineWrap = false;
										group_50.setLayout(flowLayout_16);
										(function(container){
											var button_17 = new cpr.controls.Button();
											button_17.value = "Button";
											button_17.style.setClasses(["btn-primary04"]);
											container.addChild(button_17, {
												"autoSize": "width",
												"width": "58px",
												"height": "26px"
											});
											var output_100 = new cpr.controls.Output();
											output_100.value = "5";
											output_100.style.setClasses(["pb-guideline", "guideline-blue"]);
											container.addChild(output_100, {
												"autoSize": "none",
												"width": "5px",
												"height": "26px"
											});
											var button_18 = new cpr.controls.Button();
											button_18.value = "Button";
											button_18.style.setClasses(["btn-primary04"]);
											container.addChild(button_18, {
												"autoSize": "width",
												"width": "58px",
												"height": "26px"
											});
										})(group_50);
										container.addChild(group_50, {
											"autoSize": "both",
											"width": "121px",
											"height": "26px"
										});
									})(group_48);
									container.addChild(group_48, {
										"colIndex": 5,
										"rowIndex": 3
									});
									var group_51 = new cpr.controls.Container();
									var formLayout_16 = new cpr.controls.layouts.FormLayout();
									formLayout_16.scrollable = false;
									formLayout_16.topMargin = "0px";
									formLayout_16.rightMargin = "0px";
									formLayout_16.bottomMargin = "0px";
									formLayout_16.leftMargin = "0px";
									formLayout_16.horizontalSpacing = "5px";
									formLayout_16.verticalSpacing = "5px";
									formLayout_16.setColumns(["1fr", "58px"]);
									formLayout_16.setRows(["1fr"]);
									group_51.setLayout(formLayout_16);
									(function(container){
										var comboBox_9 = new cpr.controls.ComboBox();
										(function(comboBox_9){
										})(comboBox_9);
										container.addChild(comboBox_9, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var button_19 = new cpr.controls.Button();
										button_19.value = "Button";
										button_19.style.setClasses(["btn-primary03"]);
										container.addChild(button_19, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_51);
									container.addChild(group_51, {
										"colIndex": 5,
										"rowIndex": 0
									});
									var group_52 = new cpr.controls.Container();
									var formLayout_17 = new cpr.controls.layouts.FormLayout();
									formLayout_17.scrollable = false;
									formLayout_17.topMargin = "0px";
									formLayout_17.rightMargin = "0px";
									formLayout_17.bottomMargin = "0px";
									formLayout_17.leftMargin = "0px";
									formLayout_17.horizontalSpacing = "0px";
									formLayout_17.verticalSpacing = "0px";
									formLayout_17.setColumns(["1fr", "5px", "1fr"]);
									formLayout_17.setRows(["1fr"]);
									group_52.setLayout(formLayout_17);
									(function(container){
										var comboBox_10 = new cpr.controls.ComboBox();
										(function(comboBox_10){
										})(comboBox_10);
										container.addChild(comboBox_10, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var comboBox_11 = new cpr.controls.ComboBox();
										(function(comboBox_11){
										})(comboBox_11);
										container.addChild(comboBox_11, {
											"colIndex": 2,
											"rowIndex": 0
										});
										var output_101 = new cpr.controls.Output();
										output_101.value = "5";
										output_101.style.setClasses(["pb-guideline", "guideline-blue"]);
										container.addChild(output_101, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_52);
									container.addChild(group_52, {
										"colIndex": 3,
										"rowIndex": 0
									});
								})(group_43);
								container.addChild(group_43, {
									"top": "94px",
									"right": "0px",
									"left": "0px",
									"height": "126px"
								});
								var output_102 = new cpr.controls.Output();
								output_102.value = "5";
								output_102.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_102, {
									"top": "0px",
									"left": "1px",
									"width": "5px",
									"height": "86px"
								});
								var output_103 = new cpr.controls.Output();
								output_103.value = "2";
								output_103.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_103, {
									"top": "2px",
									"right": "0px",
									"left": "0px",
									"height": "2px"
								});
								var output_104 = new cpr.controls.Output();
								output_104.value = "5";
								output_104.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_104, {
									"top": "0px",
									"right": "1px",
									"width": "5px",
									"height": "86px"
								});
								var output_105 = new cpr.controls.Output();
								output_105.value = "2";
								output_105.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_105, {
									"top": "83px",
									"right": "0px",
									"left": "0px",
									"height": "2px"
								});
								var output_106 = new cpr.controls.Output();
								output_106.value = "5";
								output_106.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_106, {
									"top": "84px",
									"bottom": "0px",
									"left": "1px",
									"width": "5px"
								});
								var output_107 = new cpr.controls.Output();
								output_107.value = "5";
								output_107.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_107, {
									"top": "94px",
									"right": "1px",
									"bottom": "0px",
									"width": "5px"
								});
								var output_108 = new cpr.controls.Output();
								output_108.value = "2";
								output_108.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_108, {
									"top": "96px",
									"right": "0px",
									"left": "0px",
									"height": "2px"
								});
								var output_109 = new cpr.controls.Output();
								output_109.value = "2";
								output_109.style.setClasses(["pb-guideline", "guideline-green"]);
								container.addChild(output_109, {
									"right": "0px",
									"bottom": "1px",
									"left": "0px",
									"height": "2px"
								});
								var output_110 = new cpr.controls.Output();
								output_110.value = "10";
								output_110.style.setClasses(["pb-guideline", "guideline-orange"]);
								container.addChild(output_110, {
									"top": "0px",
									"left": "116px",
									"width": "10px",
									"height": "86px"
								});
								var output_111 = new cpr.controls.Output();
								output_111.value = "5";
								output_111.style.setClasses(["pb-guideline", "guideline-orange"]);
								container.addChild(output_111, {
									"top": "30px",
									"right": "0px",
									"left": "0px",
									"height": "5px"
								});
								var output_112 = new cpr.controls.Output();
								output_112.value = "5";
								output_112.style.setClasses(["pb-guideline", "guideline-orange"]);
								container.addChild(output_112, {
									"top": "124px",
									"right": "0px",
									"left": "0px",
									"height": "5px"
								});
								var output_113 = new cpr.controls.Output();
								output_113.value = "10";
								output_113.style.setClasses(["pb-guideline", "guideline-orange"]);
								container.addChild(output_113, {
									"top": "95px",
									"bottom": "0px",
									"left": "116px",
									"width": "10px"
								});
								var output_114 = new cpr.controls.Output();
								output_114.value = "W110";
								output_114.style.setClasses(["pb-guideline", "guideline-purple"]);
								container.addChild(output_114, {
									"top": "4px",
									"left": "6px",
									"width": "110px",
									"height": "78px"
								});
								var output_115 = new cpr.controls.Output();
								output_115.value = "W110";
								output_115.style.setClasses(["pb-guideline", "guideline-purple"]);
								container.addChild(output_115, {
									"top": "88px",
									"bottom": "3px",
									"left": "6px",
									"width": "110px"
								});
								var output_116 = new cpr.controls.Output();
								output_116.value = "20";
								output_116.style.setClasses(["pb-guideline", "guideline-blue"]);
								container.addChild(output_116, {
									"top": "158px",
									"left": "178px",
									"width": "20px",
									"height": "31px"
								});
								var output_117 = new cpr.controls.Output();
								output_117.value = "20";
								output_117.style.setClasses(["pb-guideline", "guideline-blue"]);
								container.addChild(output_117, {
									"top": "188px",
									"left": "160px",
									"width": "20px",
									"height": "31px"
								});
								var output_118 = new cpr.controls.Output();
								output_118.value = "5";
								output_118.style.setClasses(["pb-guideline", "guideline-blue"]);
								container.addChild(output_118, {
									"top": "98px",
									"right": "64px",
									"width": "5px",
									"height": "26px"
								});
								var output_119 = new cpr.controls.Output();
								output_119.value = "7 (실제 간격)";
								output_119.style.setClasses(["pb-guideline", "guideline-purple"]);
								container.addChild(output_119, {
									"top": "33px",
									"right": "475px",
									"width": "200px",
									"height": "7px"
								});
							})(group_38);
							container.addChild(group_38, {
								"autoSize": "none",
								"width": "1380px",
								"height": "220px"
							});
						})(group_34);
						container.addChild(group_34, {
							"top": "130px",
							"right": "20px",
							"left": "20px",
							"height": "250px"
						});
						var group_53 = new cpr.controls.Container();
						group_53.style.setClasses(["button-table-area"]);
						var formLayout_18 = new cpr.controls.layouts.FormLayout();
						formLayout_18.scrollable = false;
						formLayout_18.topMargin = "0px";
						formLayout_18.rightMargin = "0px";
						formLayout_18.bottomMargin = "0px";
						formLayout_18.leftMargin = "0px";
						formLayout_18.horizontalSpacing = "0px";
						formLayout_18.verticalSpacing = "0px";
						formLayout_18.setColumns(["1fr", "43px", "1fr"]);
						formLayout_18.setColumnAutoSizing(1, true);
						formLayout_18.setRows(["1fr"]);
						group_53.setLayout(formLayout_18);
						(function(container){
							var group_54 = new cpr.controls.Container();
							group_54.style.setClasses(["button-table-bottom-left-area"]);
							var flowLayout_17 = new cpr.controls.layouts.FlowLayout();
							flowLayout_17.scrollable = false;
							flowLayout_17.horizontalSpacing = 0;
							flowLayout_17.verticalSpacing = 0;
							flowLayout_17.lineWrap = false;
							group_54.setLayout(flowLayout_17);
							(function(container){
								var button_20 = new cpr.controls.Button();
								button_20.value = "Button";
								button_20.style.setClasses(["btn-primary04", "btn-md"]);
								container.addChild(button_20, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
								var output_120 = new cpr.controls.Output();
								output_120.value = "10";
								output_120.style.setClasses(["pb-guideline", "guideline-blue"]);
								container.addChild(output_120, {
									"autoSize": "none",
									"width": "10px",
									"height": "30px"
								});
								var button_21 = new cpr.controls.Button();
								button_21.value = "Button";
								button_21.style.setClasses(["btn-primary04", "btn-md"]);
								container.addChild(button_21, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
							})(group_54);
							container.addChild(group_54, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var group_55 = new cpr.controls.Container();
							group_55.style.setClasses(["button-table-bottom-right-area"]);
							var flowLayout_18 = new cpr.controls.layouts.FlowLayout();
							flowLayout_18.scrollable = false;
							flowLayout_18.horizontalSpacing = 0;
							flowLayout_18.verticalSpacing = 0;
							flowLayout_18.horizontalAlign = "right";
							flowLayout_18.lineWrap = false;
							group_55.setLayout(flowLayout_18);
							(function(container){
								var button_22 = new cpr.controls.Button();
								button_22.value = "Button";
								button_22.style.setClasses(["btn-secondary01", "btn-md"]);
								container.addChild(button_22, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
								var output_121 = new cpr.controls.Output();
								output_121.value = "10";
								output_121.style.setClasses(["pb-guideline", "guideline-blue"]);
								container.addChild(output_121, {
									"autoSize": "none",
									"width": "10px",
									"height": "30px"
								});
								var button_23 = new cpr.controls.Button();
								button_23.value = "Button";
								button_23.style.setClasses(["btn-secondary01", "btn-md"]);
								container.addChild(button_23, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
							})(group_55);
							container.addChild(group_55, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var group_56 = new cpr.controls.Container();
							group_56.style.setClasses(["button-table-bottom-center-area"]);
							var flowLayout_19 = new cpr.controls.layouts.FlowLayout();
							flowLayout_19.scrollable = false;
							flowLayout_19.horizontalSpacing = 0;
							flowLayout_19.verticalSpacing = 0;
							flowLayout_19.horizontalAlign = "center";
							group_56.setLayout(flowLayout_19);
							(function(container){
								var button_24 = new cpr.controls.Button();
								button_24.value = "Button";
								button_24.style.setClasses(["btn-primary03", "btn-md"]);
								container.addChild(button_24, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
								var output_122 = new cpr.controls.Output();
								output_122.value = "10";
								output_122.style.setClasses(["pb-guideline", "guideline-blue"]);
								container.addChild(output_122, {
									"autoSize": "none",
									"width": "10px",
									"height": "30px"
								});
								var button_25 = new cpr.controls.Button();
								button_25.value = "Button";
								button_25.style.setClasses(["btn-primary03", "btn-md"]);
								container.addChild(button_25, {
									"autoSize": "width",
									"width": "60px",
									"height": "30px"
								});
							})(group_56);
							container.addChild(group_56, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_53);
						container.addChild(group_53, {
							"top": "390px",
							"right": "20px",
							"left": "20px",
							"height": "30px"
						});
						var group_57 = new cpr.controls.Container();
						group_57.style.setClasses(["breadcrumbs"]);
						var flowLayout_20 = new cpr.controls.layouts.FlowLayout();
						flowLayout_20.scrollable = false;
						flowLayout_20.horizontalSpacing = 5;
						flowLayout_20.verticalSpacing = 0;
						flowLayout_20.horizontalAlign = "right";
						flowLayout_20.lineWrap = false;
						group_57.setLayout(flowLayout_20);
						(function(container){
							var group_58 = new cpr.controls.Container();
							var xYLayout_6 = new cpr.controls.layouts.XYLayout();
							xYLayout_6.scrollable = false;
							group_58.setLayout(xYLayout_6);
							(function(container){
								var image_2 = new cpr.controls.Image();
								image_2.src = "../theme/hk/images/com/main/ico-comm-map-home-10.png";
								(function(image_2){
								})(image_2);
								container.addChild(image_2, {
									"top": "4px",
									"width": "10px",
									"height": "10px",
									"left": "calc(50% - 5px)"
								});
							})(group_58);
							container.addChild(group_58, {
								"width": "10px",
								"height": "17px"
							});
							var output_123 = new cpr.controls.Output();
							output_123.value = "1Depth";
							output_123.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_123, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
							var output_124 = new cpr.controls.Output();
							output_124.value = "2Depth";
							output_124.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_124, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
							var output_125 = new cpr.controls.Output();
							output_125.value = "3Depth";
							output_125.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_125, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
							var output_126 = new cpr.controls.Output();
							output_126.value = "4Depth";
							output_126.style.setClasses(["breadcrumb-item"]);
							container.addChild(output_126, {
								"autoSize": "width",
								"width": "48px",
								"height": "17px"
							});
						})(group_57);
						container.addChild(group_57, {
							"top": "20px",
							"right": "20px",
							"width": "225px",
							"height": "17px"
						});
					})(group_27);
					container.addChild(group_27, {
						"autoSize": "none",
						"width": "1420px",
						"height": "440px"
					});
				})(group_26);
				container.addChild(group_26, {
					"autoSize": "height",
					"width": "1544px",
					"height": "486px"
				});
			})(group_25);
			container.addChild(group_25, {
				"autoSize": "height",
				"width": "1520px",
				"height": "589px"
			});
		}
	});
	app.title = "[레이아웃] 컨트롤 레이아웃";
	cpr.core.Platform.INSTANCE.register(app);
})();
