/*
 * App URI: app/240228/UW009_P1
 * Source Location: app/240228/UW009_P1.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("app/240228/UW009_P1", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * UW009_P1.js
			 * Created at 2024. 2. 28. 오후 2:15:46.
			 *
			 * @author syj66
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["pop-content-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 15;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container();
				group_2.style.setClasses(["form-box", "box-spacing-free"]);
				var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_3.spacing = 8;
				group_2.setLayout(verticalLayout_3);
				(function(container){
					var group_3 = new cpr.controls.Container("grp2");
					group_3.style.setClasses(["form-normal"]);
					var formLayout_1 = new cpr.controls.layouts.FormLayout();
					formLayout_1.scrollable = false;
					formLayout_1.topMargin = "2px";
					formLayout_1.rightMargin = "5px";
					formLayout_1.bottomMargin = "2px";
					formLayout_1.leftMargin = "5px";
					formLayout_1.horizontalSpacing = "11px";
					formLayout_1.verticalSpacing = "5px";
					formLayout_1.horizontalSeparatorWidth = 1;
					formLayout_1.verticalSeparatorWidth = 1;
					formLayout_1.setColumns(["80px", "1fr", "80px", "1fr"]);
					formLayout_1.setUseColumnShade(0, true);
					formLayout_1.setUseColumnShade(2, true);
					formLayout_1.setColumnAutoSizing(0, true);
					formLayout_1.setColumnAutoSizing(2, true);
					formLayout_1.setRows(["26px", "26px", "60px"]);
					group_3.setLayout(formLayout_1);
					(function(container){
						var output_1 = new cpr.controls.Output();
						output_1.value = "등록설계번호";
						output_1.style.setClasses(["label"]);
						container.addChild(output_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var output_2 = new cpr.controls.Output();
						output_2.value = "등록일자";
						output_2.style.setClasses(["label"]);
						container.addChild(output_2, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var output_3 = new cpr.controls.Output();
						output_3.value = "해제일자";
						output_3.style.setClasses(["label"]);
						container.addChild(output_3, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var dateInput_1 = new cpr.controls.DateInput("dti1");
						dateInput_1.value = "99991231";
						container.addChild(dateInput_1, {
							"colIndex": 1,
							"rowIndex": 1,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_4 = new cpr.controls.Output();
						output_4.value = "등록자";
						output_4.style.setClasses(["label"]);
						container.addChild(output_4, {
							"colIndex": 2,
							"rowIndex": 1
						});
						var output_5 = new cpr.controls.Output();
						output_5.value = "내용";
						output_5.style.setClasses(["label"]);
						container.addChild(output_5, {
							"colIndex": 0,
							"rowIndex": 2
						});
						var textArea_1 = new cpr.controls.TextArea("txa1");
						container.addChild(textArea_1, {
							"colIndex": 1,
							"rowIndex": 2,
							"colSpan": 3,
							"rowSpan": 1
						});
						var inputBox_1 = new cpr.controls.InputBox("ipb1");
						inputBox_1.enabled = false;
						inputBox_1.value = "20221200000811";
						container.addChild(inputBox_1, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var inputBox_2 = new cpr.controls.InputBox("ipb3");
						inputBox_2.enabled = false;
						inputBox_2.value = "유주영(2601275)";
						container.addChild(inputBox_2, {
							"colIndex": 3,
							"rowIndex": 1
						});
						var dateInput_2 = new cpr.controls.DateInput("dti2");
						dateInput_2.enabled = false;
						dateInput_2.value = "20221218";
						container.addChild(dateInput_2, {
							"colIndex": 3,
							"rowIndex": 0,
							"horizontalAlign": "left",
							"width": 120
						});
					})(group_3);
					container.addChild(group_3, {
						"autoSize": "height",
						"width": "729px",
						"height": "129px"
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "729px",
					"height": "129px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "729px",
				"height": "179px"
			});
			
			var group_4 = new cpr.controls.Container("grp1");
			group_4.style.setClasses(["button-table-area"]);
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.scrollable = false;
			formLayout_2.topMargin = "0px";
			formLayout_2.rightMargin = "0px";
			formLayout_2.bottomMargin = "0px";
			formLayout_2.leftMargin = "0px";
			formLayout_2.horizontalSpacing = "0px";
			formLayout_2.verticalSpacing = "0px";
			formLayout_2.setColumns(["1fr", "43px", "1fr"]);
			formLayout_2.setColumnAutoSizing(1, true);
			formLayout_2.setRows(["1fr"]);
			group_4.setLayout(formLayout_2);
			(function(container){
				var group_5 = new cpr.controls.Container("grp3");
				group_5.style.setClasses(["button-table-bottom-center-area"]);
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 10;
				flowLayout_1.verticalSpacing = 0;
				flowLayout_1.horizontalAlign = "center";
				group_5.setLayout(flowLayout_1);
				(function(container){
					var button_1 = new cpr.controls.Button("btn3");
					button_1.value = "입력";
					button_1.style.setClasses(["btn-primary01", "btn-md"]);
					container.addChild(button_1, {
						"autoSize": "width",
						"width": "43px",
						"height": "30px"
					});
					var button_2 = new cpr.controls.Button("btn4");
					button_2.value = "닫기";
					button_2.style.setClasses(["btn-primary04", "btn-md"]);
					container.addChild(button_2, {
						"autoSize": "width",
						"width": "43px",
						"height": "30px"
					});
				})(group_5);
				container.addChild(group_5, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var group_6 = new cpr.controls.Container("grp4");
				group_6.style.setClasses(["button-table-bottom-left-area"]);
				var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
				flowLayout_2.scrollable = false;
				flowLayout_2.horizontalSpacing = 10;
				flowLayout_2.verticalSpacing = 0;
				flowLayout_2.lineWrap = false;
				group_6.setLayout(flowLayout_2);
				container.addChild(group_6, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_7 = new cpr.controls.Container("grp5");
				group_7.style.setClasses(["button-table-bottom-right-area"]);
				var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
				flowLayout_3.scrollable = false;
				flowLayout_3.horizontalSpacing = 10;
				flowLayout_3.verticalSpacing = 0;
				flowLayout_3.horizontalAlign = "right";
				flowLayout_3.lineWrap = false;
				group_7.setLayout(flowLayout_3);
				container.addChild(group_7, {
					"colIndex": 2,
					"rowIndex": 0
				});
			})(group_4);
			container.addChild(group_4, {
				"autoSize": "height",
				"width": "729px",
				"height": "30px"
			});
		}
	});
	app.title = "RISK 등록";
	cpr.core.Platform.INSTANCE.register(app);
})();
