/*
 * App URI: sfa/영업/SLEA02M1_2
 * Source Location: sfa/영업/SLEA02M1_2.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("sfa/영업/SLEA02M1_2", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * SLEA02M1.js
			 * Created at 2024. 4. 2. 오전 11:29:39.
			 *
			 * @author User
			 ************************************************/

			/*
			 * "이전" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				var button = e.control;
				//화면이동(현재 화면에서 리로드)
				var host = app.getHost(); // 부모 임베디드 앱
				cpr.core.App.load("sfa/영업/SLEA02M1_1", function(loadedApp) {
				    if (loadedApp) {
				        host.app = loadedApp;
				        host.initValue = {
				            "param": "param"
				        }
				    }
				});
			}

			/*
			 * "다음" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick3(e){
				var button = e.control;
				//화면이동(현재 화면에서 리로드)
				var host = app.getHost(); // 부모 임베디드 앱
				cpr.core.App.load("sfa/영업/SLEA02M1_3", function(loadedApp) {
				    if (loadedApp) {
				        host.app = loadedApp;
				        host.initValue = {
				            "param": "param"
				        }
				    }
				});
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsSet1");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{
						"name": "column2",
						"info": ""
					},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"}
				],
				"rows": [
					{"column1": "소속", "column2": "000111", "column3": "노*지점", "column4": "20220703", "column5": "99991231", "column6": "temp", "column7": "", "column8": "", "column9": ""},
					{"column1": "대리점", "column2": "", "column3": "", "column4": "", "column5": "", "column6": "", "column7": "", "column8": "", "column9": ""},
					{"column1": "CBM", "column2": "", "column3": "", "column4": "", "column5": "", "column6": "", "column7": "", "column8": "", "column9": ""},
					{"column1": "흡수", "column2": "", "column3": "", "column4": "", "column5": "", "column6": "", "column7": "", "column8": "", "column9": ""},
					{"column1": "분할", "column2": "", "column3": "", "column4": "", "column5": "", "column6": "", "column7": "", "column8": "", "column9": ""},
					{"column1": "발의부서", "column2": "008001", "column3": "노*지점", "column4": "20220703", "column5": "99991231", "column6": "temp", "column7": "", "column8": "", "column9": ""},
					{"column1": "현지지급", "column2": "310007", "column3": "노*CS브랜치", "column4": "20230415", "column5": "20230422", "column6": "temp", "column7": "", "column8": "", "column9": ""},
					{"column1": "채널", "column2": "", "column3": "", "column4": "", "column5": "", "column6": "", "column7": "", "column8": "", "column9": ""},
					{"column1": "현지변경", "column2": "326007", "column3": "원격지원", "column4": "20190705", "column5": "99991231", "column6": "temp", "column7": "", "column8": "", "column9": ""}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["grid-window-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 0;
			verticalLayout_1.leftMargin = 20;
			verticalLayout_1.rightMargin = 20;
			verticalLayout_1.topMargin = 20;
			verticalLayout_1.bottomMargin = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpAppTitle");
			group_1.style.setClasses(["app-title"]);
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr", "1fr"]);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output("optTitle2");
				output_1.value = "기본사항처리";
				output_1.style.setClasses(["navi-left"]);
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_2 = new cpr.controls.Container("grpNavi2");
				group_2.style.setClasses(["breadcrumbs"]);
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 5;
				flowLayout_1.verticalSpacing = 0;
				flowLayout_1.horizontalAlign = "right";
				flowLayout_1.verticalAlign = "middle";
				flowLayout_1.lineWrap = false;
				group_2.setLayout(flowLayout_1);
				(function(container){
					var button_1 = new cpr.controls.Button();
					button_1.value = "이전";
					button_1.style.setClasses(["btn-primary04", "btn-md"]);
					if(typeof onButtonClick2 == "function") {
						button_1.addEventListener("click", onButtonClick2);
					}
					container.addChild(button_1, {
						"autoSize": "width",
						"width": "49px",
						"height": "26px"
					});
					var button_2 = new cpr.controls.Button();
					button_2.value = "다음";
					button_2.style.setClasses(["btn-primary04", "btn-md"]);
					if(typeof onButtonClick == "function") {
						button_2.addEventListener("click", onButtonClick);
					}
					if(typeof onButtonClick3 == "function") {
						button_2.addEventListener("click", onButtonClick3);
					}
					container.addChild(button_2, {
						"autoSize": "width",
						"width": "49px",
						"height": "26px"
					});
				})(group_2);
				container.addChild(group_2, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1560px",
				"height": "35px"
			});
			
			var group_3 = new cpr.controls.Container("grpTopSearch");
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 12;
			group_3.setLayout(verticalLayout_2);
			(function(container){
				var group_4 = new cpr.controls.Container("grpTopSearchBox");
				group_4.style.setClasses(["search-box"]);
				var formLayout_2 = new cpr.controls.layouts.FormLayout();
				formLayout_2.scrollable = false;
				formLayout_2.topMargin = "6px";
				formLayout_2.rightMargin = "20px";
				formLayout_2.bottomMargin = "6px";
				formLayout_2.leftMargin = "20px";
				formLayout_2.horizontalSpacing = "20px";
				formLayout_2.verticalSpacing = "8px";
				formLayout_2.setColumns(["0px", "1fr", "0px", "2fr", "0px", "3fr", "63px"]);
				formLayout_2.setColumnAutoSizing(0, true);
				formLayout_2.setColumnAutoSizing(2, true);
				formLayout_2.setColumnAutoSizing(4, true);
				formLayout_2.setColumnAutoSizing(6, true);
				formLayout_2.setRows(["26px"]);
				group_4.setLayout(formLayout_2);
				(function(container){
					var output_2 = new cpr.controls.Output();
					output_2.value = "업무구분";
					output_2.style.setClasses(["label", "required"]);
					container.addChild(output_2, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var comboBox_1 = new cpr.controls.ComboBox("cmb1");
					comboBox_1.value = "value1";
					comboBox_1.style.css({
						"border-right-style" : "dashed",
						"border-top-width" : "3px",
						"border-bottom-color" : "red",
						"border-left-style" : "dashed",
						"border-right-width" : "3px",
						"border-bottom-width" : "3px",
						"border-left-color" : "red",
						"border-top-color" : "red",
						"border-bottom-style" : "dashed",
						"border-right-color" : "red",
						"border-left-width" : "3px",
						"border-top-style" : "dashed"
					});
					(function(comboBox_1){
						comboBox_1.addItem(new cpr.controls.Item("점포조회", "value1"));
					})(comboBox_1);
					container.addChild(comboBox_1, {
						"colIndex": 1,
						"rowIndex": 0
					});
					var output_3 = new cpr.controls.Output();
					output_3.value = "조직번호";
					output_3.style.setClasses(["label", "required"]);
					container.addChild(output_3, {
						"colIndex": 2,
						"rowIndex": 0
					});
					var group_5 = new cpr.controls.Container("grp17");
					group_5.style.setClasses(["form-inside"]);
					var formLayout_3 = new cpr.controls.layouts.FormLayout();
					formLayout_3.scrollable = false;
					formLayout_3.topMargin = "0px";
					formLayout_3.rightMargin = "0px";
					formLayout_3.bottomMargin = "0px";
					formLayout_3.leftMargin = "0px";
					formLayout_3.horizontalSpacing = "5px";
					formLayout_3.verticalSpacing = "5px";
					formLayout_3.setColumns(["120px", "1fr"]);
					formLayout_3.setRows(["1fr"]);
					group_5.setLayout(formLayout_3);
					(function(container){
						var searchInput_1 = new cpr.controls.SearchInput();
						searchInput_1.value = "0001120372";
						container.addChild(searchInput_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var inputBox_1 = new cpr.controls.InputBox("ipb2");
						inputBox_1.enabled = false;
						inputBox_1.value = "노원지점";
						container.addChild(inputBox_1, {
							"colIndex": 1,
							"rowIndex": 0
						});
					})(group_5);
					container.addChild(group_5, {
						"colIndex": 3,
						"rowIndex": 0
					});
					var group_6 = new cpr.controls.Container("grp18");
					group_6.style.setClasses(["btn-flow-area"]);
					var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
					flowLayout_2.scrollable = false;
					flowLayout_2.verticalSpacing = 0;
					flowLayout_2.horizontalAlign = "right";
					flowLayout_2.lineWrap = false;
					flowLayout_2.leftMargin = 20;
					group_6.setLayout(flowLayout_2);
					(function(container){
						var button_3 = new cpr.controls.Button("btn11");
						button_3.value = "조회";
						button_3.style.setClasses(["btn-search"]);
						container.addChild(button_3, {
							"width": "49px",
							"height": "26px"
						});
						var button_4 = new cpr.controls.Button("btn12");
						button_4.value = "";
						button_4.style.setClasses(["btn-reset"]);
						container.addChild(button_4, {
							"width": "26px",
							"height": "26px"
						});
					})(group_6);
					container.addChild(group_6, {
						"colIndex": 6,
						"rowIndex": 0,
						"colSpan": 1,
						"rowSpan": 1,
						"verticalAlign": "center",
						"height": 26
					});
				})(group_4);
				container.addChild(group_4, {
					"autoSize": "height",
					"width": "1420px",
					"height": "40px"
				});
			})(group_3);
			container.addChild(group_3, {
				"autoSize": "height",
				"width": "1560px",
				"height": "40px"
			});
			
			var group_7 = new cpr.controls.Container("grpBody");
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.spacing = 7;
			group_7.setLayout(verticalLayout_3);
			(function(container){
				var group_8 = new cpr.controls.Container();
				group_8.style.setClasses(["form-box"]);
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.scrollable = false;
				verticalLayout_4.spacing = 8;
				group_8.setLayout(verticalLayout_4);
				(function(container){
					var group_9 = new cpr.controls.Container("grp3");
					group_9.style.setClasses(["form-title-box"]);
					var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
					group_9.setLayout(verticalLayout_5);
					(function(container){
						var output_4 = new cpr.controls.Output();
						output_4.value = "조직기본사항";
						output_4.style.setClasses(["form-title"]);
						container.addChild(output_4, {
							"autoSize": "height",
							"width": "300px",
							"height": "17px"
						});
					})(group_9);
					container.addChild(group_9, {
						"autoSize": "height",
						"width": "300px",
						"height": "17px"
					});
					var group_10 = new cpr.controls.Container("grp16");
					group_10.style.setClasses(["form-normal"]);
					var formLayout_4 = new cpr.controls.layouts.FormLayout();
					formLayout_4.scrollable = false;
					formLayout_4.topMargin = "2px";
					formLayout_4.rightMargin = "5px";
					formLayout_4.bottomMargin = "2px";
					formLayout_4.leftMargin = "5px";
					formLayout_4.horizontalSpacing = "11px";
					formLayout_4.verticalSpacing = "5px";
					formLayout_4.horizontalSeparatorWidth = 1;
					formLayout_4.verticalSeparatorWidth = 1;
					formLayout_4.setColumns(["110px", "3fr", "110px", "2fr", "110px", "2fr", "110px", "2fr"]);
					formLayout_4.setUseColumnShade(0, true);
					formLayout_4.setUseColumnShade(2, true);
					formLayout_4.setUseColumnShade(4, true);
					formLayout_4.setUseColumnShade(6, true);
					formLayout_4.setColumnAutoSizing(0, true);
					formLayout_4.setColumnAutoSizing(2, true);
					formLayout_4.setColumnAutoSizing(4, true);
					formLayout_4.setColumnAutoSizing(6, true);
					formLayout_4.setRows(["26px", "26px", "26px", "26px", "26px", "26px", "26px"]);
					group_10.setLayout(formLayout_4);
					(function(container){
						var output_5 = new cpr.controls.Output();
						output_5.value = "조직명";
						output_5.style.setClasses(["label"]);
						container.addChild(output_5, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var inputBox_2 = new cpr.controls.InputBox("ipb1");
						inputBox_2.value = "노원지점";
						container.addChild(inputBox_2, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var output_6 = new cpr.controls.Output();
						output_6.value = "조직축약명";
						output_6.style.setClasses(["label"]);
						container.addChild(output_6, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var inputBox_3 = new cpr.controls.InputBox("ipb3");
						inputBox_3.value = "노원";
						container.addChild(inputBox_3, {
							"colIndex": 3,
							"rowIndex": 0
						});
						var output_7 = new cpr.controls.Output();
						output_7.value = "조직명변경일";
						output_7.style.setClasses(["label"]);
						container.addChild(output_7, {
							"colIndex": 4,
							"rowIndex": 0
						});
						var dateInput_1 = new cpr.controls.DateInput("dti1");
						dateInput_1.value = "20180102";
						container.addChild(dateInput_1, {
							"colIndex": 5,
							"rowIndex": 0,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_8 = new cpr.controls.Output();
						output_8.value = "조직영문명";
						output_8.style.setClasses(["label"]);
						container.addChild(output_8, {
							"colIndex": 6,
							"rowIndex": 0
						});
						var inputBox_4 = new cpr.controls.InputBox("ipb4");
						container.addChild(inputBox_4, {
							"colIndex": 7,
							"rowIndex": 0
						});
						var output_9 = new cpr.controls.Output();
						output_9.value = "개시일자";
						output_9.style.setClasses(["label"]);
						container.addChild(output_9, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var dateInput_2 = new cpr.controls.DateInput("dti2");
						dateInput_2.value = "20180102";
						container.addChild(dateInput_2, {
							"colIndex": 1,
							"rowIndex": 1,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_10 = new cpr.controls.Output();
						output_10.value = "폐쇄일자";
						output_10.style.setClasses(["label"]);
						container.addChild(output_10, {
							"colIndex": 2,
							"rowIndex": 1
						});
						var dateInput_3 = new cpr.controls.DateInput("dti3");
						dateInput_3.value = "99991231";
						container.addChild(dateInput_3, {
							"colIndex": 3,
							"rowIndex": 1,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_11 = new cpr.controls.Output();
						output_11.value = "조직유형";
						output_11.style.setClasses(["label"]);
						container.addChild(output_11, {
							"colIndex": 4,
							"rowIndex": 1
						});
						var comboBox_2 = new cpr.controls.ComboBox("cmb2");
						comboBox_2.value = "value1";
						comboBox_2.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						(function(comboBox_2){
							comboBox_2.addItem(new cpr.controls.Item("영업소", "value1"));
						})(comboBox_2);
						container.addChild(comboBox_2, {
							"colIndex": 5,
							"rowIndex": 1
						});
						var output_12 = new cpr.controls.Output();
						output_12.value = "유형시행일";
						output_12.style.setClasses(["label"]);
						container.addChild(output_12, {
							"colIndex": 6,
							"rowIndex": 1
						});
						var dateInput_4 = new cpr.controls.DateInput("dti6");
						dateInput_4.value = "20180102";
						container.addChild(dateInput_4, {
							"colIndex": 7,
							"rowIndex": 1,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_13 = new cpr.controls.Output();
						output_13.value = "조직속성";
						output_13.style.setClasses(["label"]);
						container.addChild(output_13, {
							"colIndex": 0,
							"rowIndex": 2
						});
						var comboBox_3 = new cpr.controls.ComboBox("cmb9");
						comboBox_3.value = "value1";
						comboBox_3.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						(function(comboBox_3){
							comboBox_3.addItem(new cpr.controls.Item("영업지점", "value1"));
						})(comboBox_3);
						container.addChild(comboBox_3, {
							"colIndex": 1,
							"rowIndex": 2
						});
						var output_14 = new cpr.controls.Output();
						output_14.value = "속성시행일";
						output_14.style.setClasses(["label"]);
						container.addChild(output_14, {
							"colIndex": 2,
							"rowIndex": 2
						});
						var dateInput_5 = new cpr.controls.DateInput("dti4");
						dateInput_5.value = "20180102";
						container.addChild(dateInput_5, {
							"colIndex": 3,
							"rowIndex": 2,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_15 = new cpr.controls.Output();
						output_15.value = "조직특성";
						output_15.style.setClasses(["label"]);
						container.addChild(output_15, {
							"colIndex": 4,
							"rowIndex": 2
						});
						var comboBox_4 = new cpr.controls.ComboBox("cmb3");
						comboBox_4.value = "value1";
						(function(comboBox_4){
							comboBox_4.addItem(new cpr.controls.Item("미부여", "value1"));
						})(comboBox_4);
						container.addChild(comboBox_4, {
							"colIndex": 5,
							"rowIndex": 2
						});
						var output_16 = new cpr.controls.Output();
						output_16.value = "특성시행일";
						output_16.style.setClasses(["label"]);
						container.addChild(output_16, {
							"colIndex": 6,
							"rowIndex": 2
						});
						var dateInput_6 = new cpr.controls.DateInput("dti7");
						dateInput_6.value = "20180102";
						container.addChild(dateInput_6, {
							"colIndex": 7,
							"rowIndex": 2,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_17 = new cpr.controls.Output();
						output_17.value = "조직규모";
						output_17.style.setClasses(["label"]);
						container.addChild(output_17, {
							"colIndex": 0,
							"rowIndex": 3
						});
						var comboBox_5 = new cpr.controls.ComboBox("cmb10");
						comboBox_5.value = "value1";
						(function(comboBox_5){
							comboBox_5.addItem(new cpr.controls.Item("해당없음", "value1"));
						})(comboBox_5);
						container.addChild(comboBox_5, {
							"colIndex": 1,
							"rowIndex": 3
						});
						var output_18 = new cpr.controls.Output();
						output_18.value = "규모시행일";
						output_18.style.setClasses(["label"]);
						container.addChild(output_18, {
							"colIndex": 2,
							"rowIndex": 3
						});
						var dateInput_7 = new cpr.controls.DateInput("dti5");
						dateInput_7.value = "20180102";
						container.addChild(dateInput_7, {
							"colIndex": 3,
							"rowIndex": 3,
							"horizontalAlign": "left",
							"width": 120
						});
						var output_19 = new cpr.controls.Output();
						output_19.value = "광역시도구분";
						output_19.style.setClasses(["label"]);
						container.addChild(output_19, {
							"colIndex": 4,
							"rowIndex": 3
						});
						var comboBox_6 = new cpr.controls.ComboBox("cmb4");
						comboBox_6.value = "value1";
						(function(comboBox_6){
							comboBox_6.addItem(new cpr.controls.Item("서울", "value1"));
						})(comboBox_6);
						container.addChild(comboBox_6, {
							"colIndex": 5,
							"rowIndex": 3
						});
						var output_20 = new cpr.controls.Output();
						output_20.value = "지역구분";
						output_20.style.setClasses(["label"]);
						container.addChild(output_20, {
							"colIndex": 6,
							"rowIndex": 3
						});
						var comboBox_7 = new cpr.controls.ComboBox("cmb6");
						comboBox_7.value = "value1";
						(function(comboBox_7){
							comboBox_7.addItem(new cpr.controls.Item("서울", "value1"));
						})(comboBox_7);
						container.addChild(comboBox_7, {
							"colIndex": 7,
							"rowIndex": 3
						});
						var output_21 = new cpr.controls.Output();
						output_21.value = "육성운영구분";
						output_21.style.setClasses(["label"]);
						container.addChild(output_21, {
							"colIndex": 0,
							"rowIndex": 4
						});
						var comboBox_8 = new cpr.controls.ComboBox("cmb11");
						comboBox_8.value = "value1";
						(function(comboBox_8){
							comboBox_8.addItem(new cpr.controls.Item("통합운영", "value1"));
						})(comboBox_8);
						container.addChild(comboBox_8, {
							"colIndex": 1,
							"rowIndex": 4
						});
						var output_22 = new cpr.controls.Output();
						output_22.value = "외각점포여부";
						output_22.style.setClasses(["label"]);
						container.addChild(output_22, {
							"colIndex": 2,
							"rowIndex": 4
						});
						var comboBox_9 = new cpr.controls.ComboBox("cmb8");
						comboBox_9.value = "value1";
						(function(comboBox_9){
							comboBox_9.addItem(new cpr.controls.Item("N", "value1"));
						})(comboBox_9);
						container.addChild(comboBox_9, {
							"colIndex": 3,
							"rowIndex": 4
						});
						var output_23 = new cpr.controls.Output();
						output_23.value = "조직종류";
						output_23.style.setClasses(["label"]);
						container.addChild(output_23, {
							"colIndex": 4,
							"rowIndex": 4
						});
						var comboBox_10 = new cpr.controls.ComboBox("cmb5");
						comboBox_10.value = "value1";
						(function(comboBox_10){
							comboBox_10.addItem(new cpr.controls.Item("개인", "value1"));
						})(comboBox_10);
						container.addChild(comboBox_10, {
							"colIndex": 5,
							"rowIndex": 4
						});
						var output_24 = new cpr.controls.Output();
						output_24.value = "사업부문";
						output_24.style.setClasses(["label"]);
						container.addChild(output_24, {
							"colIndex": 6,
							"rowIndex": 4
						});
						var comboBox_11 = new cpr.controls.ComboBox("cmb7");
						comboBox_11.value = "value1";
						comboBox_11.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						(function(comboBox_11){
							comboBox_11.addItem(new cpr.controls.Item("FP", "value1"));
						})(comboBox_11);
						container.addChild(comboBox_11, {
							"colIndex": 7,
							"rowIndex": 4
						});
						var output_25 = new cpr.controls.Output();
						output_25.value = "구분";
						output_25.style.setClasses(["label"]);
						container.addChild(output_25, {
							"colIndex": 0,
							"rowIndex": 5
						});
						var checkBoxGroup_1 = new cpr.controls.CheckBoxGroup("cbg1");
						checkBoxGroup_1.values = ["value1", "value2", "value3"];
						(function(checkBoxGroup_1){
							checkBoxGroup_1.addItem(new cpr.controls.Item("창구여부", "value1"));
							checkBoxGroup_1.addItem(new cpr.controls.Item("점포여부", "value2"));
							checkBoxGroup_1.addItem(new cpr.controls.Item("사용여부", "value3"));
							checkBoxGroup_1.addItem(new cpr.controls.Item("재런칭", "value4"));
						})(checkBoxGroup_1);
						container.addChild(checkBoxGroup_1, {
							"colIndex": 1,
							"rowIndex": 5
						});
						var output_26 = new cpr.controls.Output();
						output_26.value = "생보협지사번호";
						output_26.style.setClasses(["label"]);
						container.addChild(output_26, {
							"colIndex": 2,
							"rowIndex": 5
						});
						var inputBox_5 = new cpr.controls.InputBox("ipb5");
						container.addChild(inputBox_5, {
							"colIndex": 3,
							"rowIndex": 5
						});
						var output_27 = new cpr.controls.Output();
						output_27.value = "대리점등록번호";
						output_27.style.setClasses(["label"]);
						container.addChild(output_27, {
							"colIndex": 4,
							"rowIndex": 5
						});
						var inputBox_6 = new cpr.controls.InputBox("ipb6");
						container.addChild(inputBox_6, {
							"colIndex": 5,
							"rowIndex": 5
						});
						var output_28 = new cpr.controls.Output();
						output_28.value = "사업자등록번호";
						output_28.style.setClasses(["label"]);
						container.addChild(output_28, {
							"colIndex": 6,
							"rowIndex": 5
						});
						var inputBox_7 = new cpr.controls.InputBox("ipb7");
						container.addChild(inputBox_7, {
							"colIndex": 7,
							"rowIndex": 5
						});
						var output_29 = new cpr.controls.Output();
						output_29.value = "제휴BM";
						output_29.style.setClasses(["label"]);
						container.addChild(output_29, {
							"colIndex": 0,
							"rowIndex": 6
						});
						var group_11 = new cpr.controls.Container("grp4");
						group_11.style.setClasses(["form-inside"]);
						var formLayout_5 = new cpr.controls.layouts.FormLayout();
						formLayout_5.scrollable = false;
						formLayout_5.topMargin = "0px";
						formLayout_5.rightMargin = "0px";
						formLayout_5.bottomMargin = "0px";
						formLayout_5.leftMargin = "0px";
						formLayout_5.horizontalSpacing = "5px";
						formLayout_5.verticalSpacing = "0px";
						formLayout_5.setColumns(["1fr", "1fr"]);
						formLayout_5.setRows(["1fr"]);
						group_11.setLayout(formLayout_5);
						(function(container){
							var searchInput_2 = new cpr.controls.SearchInput();
							container.addChild(searchInput_2, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var inputBox_8 = new cpr.controls.InputBox("ipb8");
							container.addChild(inputBox_8, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_11);
						container.addChild(group_11, {
							"colIndex": 1,
							"rowIndex": 6
						});
						var output_30 = new cpr.controls.Output();
						output_30.value = "관리BM";
						output_30.style.setClasses(["label"]);
						container.addChild(output_30, {
							"colIndex": 2,
							"rowIndex": 6
						});
						var group_12 = new cpr.controls.Container("grp5");
						group_12.style.setClasses(["form-inside"]);
						var formLayout_6 = new cpr.controls.layouts.FormLayout();
						formLayout_6.scrollable = false;
						formLayout_6.topMargin = "0px";
						formLayout_6.rightMargin = "0px";
						formLayout_6.bottomMargin = "0px";
						formLayout_6.leftMargin = "0px";
						formLayout_6.horizontalSpacing = "5px";
						formLayout_6.verticalSpacing = "0px";
						formLayout_6.setColumns(["1fr", "1fr"]);
						formLayout_6.setRows(["1fr"]);
						group_12.setLayout(formLayout_6);
						(function(container){
							var searchInput_3 = new cpr.controls.SearchInput();
							container.addChild(searchInput_3, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var inputBox_9 = new cpr.controls.InputBox("ipb9");
							container.addChild(inputBox_9, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_12);
						container.addChild(group_12, {
							"colIndex": 3,
							"rowIndex": 6,
							"colSpan": 5,
							"rowSpan": 1,
							"horizontalAlign": "left",
							"width": 300
						});
					})(group_10);
					container.addChild(group_10, {
						"autoSize": "height",
						"width": "1772px",
						"height": "219px"
					});
				})(group_8);
				container.addChild(group_8, {
					"autoSize": "height",
					"width": "1160px",
					"height": "249px"
				});
				var group_13 = new cpr.controls.Container();
				group_13.style.setClasses(["form-box"]);
				var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_6.scrollable = false;
				verticalLayout_6.spacing = 8;
				group_13.setLayout(verticalLayout_6);
				(function(container){
					var group_14 = new cpr.controls.Container();
					group_14.style.setClasses(["form-normal"]);
					var formLayout_7 = new cpr.controls.layouts.FormLayout();
					formLayout_7.scrollable = false;
					formLayout_7.topMargin = "2px";
					formLayout_7.rightMargin = "5px";
					formLayout_7.bottomMargin = "2px";
					formLayout_7.leftMargin = "5px";
					formLayout_7.horizontalSpacing = "11px";
					formLayout_7.verticalSpacing = "5px";
					formLayout_7.horizontalSeparatorWidth = 1;
					formLayout_7.verticalSeparatorWidth = 1;
					formLayout_7.setColumns(["110px", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr"]);
					formLayout_7.setUseColumnShade(0, true);
					formLayout_7.setColumnAutoSizing(0, true);
					formLayout_7.setColumnMinWidth(6, 50);
					formLayout_7.setRows(["26px", "26px", "26px", "26px", "26px", "26px", "26px", "26px", "26px", "26px"]);
					formLayout_7.setUseRowShade(0, true);
					group_14.setLayout(formLayout_7);
					(function(container){
						var output_31 = new cpr.controls.Output();
						output_31.value = "관계정보";
						output_31.style.setClasses(["label"]);
						container.addChild(output_31, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var output_32 = new cpr.controls.Output();
						output_32.value = "조직관계";
						output_32.style.setClasses(["label"]);
						container.addChild(output_32, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var output_33 = new cpr.controls.Output();
						output_33.value = "점포명";
						output_33.style.setClasses(["label"]);
						container.addChild(output_33, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var output_34 = new cpr.controls.Output();
						output_34.value = "유효게시일";
						output_34.style.setClasses(["label"]);
						container.addChild(output_34, {
							"colIndex": 3,
							"rowIndex": 0
						});
						var output_35 = new cpr.controls.Output();
						output_35.value = "유효종료일";
						output_35.style.setClasses(["label"]);
						container.addChild(output_35, {
							"colIndex": 4,
							"rowIndex": 0
						});
						var output_36 = new cpr.controls.Output();
						output_36.value = "처리구분";
						output_36.style.setClasses(["label"]);
						container.addChild(output_36, {
							"colIndex": 5,
							"rowIndex": 0
						});
						var output_37 = new cpr.controls.Output();
						output_37.value = "관계정보";
						output_37.style.setClasses(["label"]);
						container.addChild(output_37, {
							"colIndex": 6,
							"rowIndex": 0
						});
						var output_38 = new cpr.controls.Output();
						output_38.value = "유효게시일";
						output_38.style.setClasses(["label"]);
						container.addChild(output_38, {
							"colIndex": 7,
							"rowIndex": 0
						});
						var output_39 = new cpr.controls.Output();
						output_39.value = "유효종료일";
						output_39.style.setClasses(["label"]);
						container.addChild(output_39, {
							"colIndex": 8,
							"rowIndex": 0
						});
						var inputBox_10 = new cpr.controls.InputBox("ipb17");
						inputBox_10.value = "";
						container.addChild(inputBox_10, {
							"colIndex": 1,
							"rowIndex": 2
						});
						var output_40 = new cpr.controls.Output();
						output_40.value = "대리점";
						output_40.style.setClasses(["label"]);
						container.addChild(output_40, {
							"colIndex": 0,
							"rowIndex": 2
						});
						var output_41 = new cpr.controls.Output();
						output_41.value = "CBM";
						output_41.style.setClasses(["label"]);
						container.addChild(output_41, {
							"colIndex": 0,
							"rowIndex": 3
						});
						var output_42 = new cpr.controls.Output();
						output_42.value = "흡수";
						output_42.style.setClasses(["label"]);
						container.addChild(output_42, {
							"colIndex": 0,
							"rowIndex": 4
						});
						var output_43 = new cpr.controls.Output();
						output_43.value = "분할";
						output_43.style.setClasses(["label"]);
						container.addChild(output_43, {
							"colIndex": 0,
							"rowIndex": 5
						});
						var output_44 = new cpr.controls.Output();
						output_44.value = "발의부서";
						output_44.style.setClasses(["label"]);
						if(typeof onOutputValueChange == "function") {
							output_44.addEventListener("value-change", onOutputValueChange);
						}
						container.addChild(output_44, {
							"colIndex": 0,
							"rowIndex": 6
						});
						var output_45 = new cpr.controls.Output();
						output_45.value = "현지지급";
						output_45.style.setClasses(["label"]);
						container.addChild(output_45, {
							"colIndex": 0,
							"rowIndex": 7
						});
						var output_46 = new cpr.controls.Output();
						output_46.value = "채널";
						output_46.style.setClasses(["label"]);
						container.addChild(output_46, {
							"colIndex": 0,
							"rowIndex": 8
						});
						var output_47 = new cpr.controls.Output();
						output_47.value = "현지변경";
						output_47.style.setClasses(["label"]);
						container.addChild(output_47, {
							"colIndex": 0,
							"rowIndex": 9
						});
						var inputBox_11 = new cpr.controls.InputBox("ipb18");
						inputBox_11.value = "";
						container.addChild(inputBox_11, {
							"colIndex": 2,
							"rowIndex": 2
						});
						var inputBox_12 = new cpr.controls.InputBox("ipb24");
						inputBox_12.value = "";
						container.addChild(inputBox_12, {
							"colIndex": 2,
							"rowIndex": 3
						});
						var inputBox_13 = new cpr.controls.InputBox("ipb16");
						inputBox_13.value = "";
						container.addChild(inputBox_13, {
							"colIndex": 1,
							"rowIndex": 3
						});
						var inputBox_14 = new cpr.controls.InputBox("ipb15");
						inputBox_14.value = "";
						container.addChild(inputBox_14, {
							"colIndex": 1,
							"rowIndex": 4
						});
						var inputBox_15 = new cpr.controls.InputBox("ipb21");
						inputBox_15.value = "";
						container.addChild(inputBox_15, {
							"colIndex": 2,
							"rowIndex": 4
						});
						var inputBox_16 = new cpr.controls.InputBox("ipb23");
						inputBox_16.value = "";
						container.addChild(inputBox_16, {
							"colIndex": 2,
							"rowIndex": 5
						});
						var inputBox_17 = new cpr.controls.InputBox("ipb14");
						inputBox_17.value = "";
						container.addChild(inputBox_17, {
							"colIndex": 1,
							"rowIndex": 5
						});
						var inputBox_18 = new cpr.controls.InputBox("ipb13");
						inputBox_18.value = "008001";
						container.addChild(inputBox_18, {
							"colIndex": 1,
							"rowIndex": 6
						});
						var inputBox_19 = new cpr.controls.InputBox("ipb12");
						inputBox_19.value = "310007";
						if(typeof onIpb12ValueChange == "function") {
							inputBox_19.addEventListener("value-change", onIpb12ValueChange);
						}
						container.addChild(inputBox_19, {
							"colIndex": 1,
							"rowIndex": 7
						});
						var inputBox_20 = new cpr.controls.InputBox("ipb26");
						inputBox_20.value = "노*B***";
						container.addChild(inputBox_20, {
							"colIndex": 2,
							"rowIndex": 7
						});
						var inputBox_21 = new cpr.controls.InputBox("ipb25");
						inputBox_21.value = "노*지점";
						container.addChild(inputBox_21, {
							"colIndex": 2,
							"rowIndex": 6
						});
						var inputBox_22 = new cpr.controls.InputBox("ipb27");
						inputBox_22.value = "";
						container.addChild(inputBox_22, {
							"colIndex": 1,
							"rowIndex": 8
						});
						var inputBox_23 = new cpr.controls.InputBox("ipb28");
						inputBox_23.value = "326007";
						container.addChild(inputBox_23, {
							"colIndex": 1,
							"rowIndex": 9
						});
						var inputBox_24 = new cpr.controls.InputBox("ipb29");
						inputBox_24.value = "원격지원";
						container.addChild(inputBox_24, {
							"colIndex": 2,
							"rowIndex": 9
						});
						var inputBox_25 = new cpr.controls.InputBox("ipb30");
						inputBox_25.value = "";
						container.addChild(inputBox_25, {
							"colIndex": 2,
							"rowIndex": 8
						});
						var dateInput_8 = new cpr.controls.DateInput("dti9");
						dateInput_8.value = "20180702";
						container.addChild(dateInput_8, {
							"colIndex": 3,
							"rowIndex": 6
						});
						var dateInput_9 = new cpr.controls.DateInput("dti11");
						dateInput_9.value = "20190415";
						container.addChild(dateInput_9, {
							"colIndex": 3,
							"rowIndex": 7
						});
						var dateInput_10 = new cpr.controls.DateInput("dti12");
						dateInput_10.value = "20150705";
						container.addChild(dateInput_10, {
							"colIndex": 3,
							"rowIndex": 9
						});
						var comboBox_12 = new cpr.controls.ComboBox("cmb13");
						comboBox_12.value = "value1";
						(function(comboBox_12){
							comboBox_12.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_12);
						container.addChild(comboBox_12, {
							"colIndex": 5,
							"rowIndex": 6
						});
						var comboBox_13 = new cpr.controls.ComboBox("cmb14");
						comboBox_13.value = "value1";
						(function(comboBox_13){
							comboBox_13.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_13);
						container.addChild(comboBox_13, {
							"colIndex": 5,
							"rowIndex": 7
						});
						var comboBox_14 = new cpr.controls.ComboBox("cmb15");
						comboBox_14.value = "value1";
						(function(comboBox_14){
							comboBox_14.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_14);
						container.addChild(comboBox_14, {
							"colIndex": 5,
							"rowIndex": 9
						});
						var searchInput_4 = new cpr.controls.SearchInput();
						container.addChild(searchInput_4, {
							"colIndex": 6,
							"rowIndex": 6
						});
						var searchInput_5 = new cpr.controls.SearchInput();
						container.addChild(searchInput_5, {
							"colIndex": 6,
							"rowIndex": 7
						});
						var searchInput_6 = new cpr.controls.SearchInput();
						container.addChild(searchInput_6, {
							"colIndex": 6,
							"rowIndex": 9
						});
						var searchInput_7 = new cpr.controls.SearchInput();
						container.addChild(searchInput_7, {
							"colIndex": 6,
							"rowIndex": 3
						});
						var searchInput_8 = new cpr.controls.SearchInput();
						container.addChild(searchInput_8, {
							"colIndex": 6,
							"rowIndex": 5
						});
						var searchInput_9 = new cpr.controls.SearchInput();
						container.addChild(searchInput_9, {
							"colIndex": 6,
							"rowIndex": 4
						});
						var searchInput_10 = new cpr.controls.SearchInput();
						container.addChild(searchInput_10, {
							"colIndex": 6,
							"rowIndex": 2
						});
						var searchInput_11 = new cpr.controls.SearchInput();
						container.addChild(searchInput_11, {
							"colIndex": 6,
							"rowIndex": 8
						});
						var comboBox_15 = new cpr.controls.ComboBox("cmb16");
						comboBox_15.value = "value1";
						(function(comboBox_15){
							comboBox_15.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_15);
						container.addChild(comboBox_15, {
							"colIndex": 5,
							"rowIndex": 3
						});
						var comboBox_16 = new cpr.controls.ComboBox("cmb17");
						comboBox_16.value = "value1";
						(function(comboBox_16){
							comboBox_16.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_16);
						container.addChild(comboBox_16, {
							"colIndex": 5,
							"rowIndex": 4
						});
						var comboBox_17 = new cpr.controls.ComboBox("cmb18");
						comboBox_17.value = "value1";
						(function(comboBox_17){
							comboBox_17.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_17);
						container.addChild(comboBox_17, {
							"colIndex": 5,
							"rowIndex": 2
						});
						var comboBox_18 = new cpr.controls.ComboBox("cmb19");
						comboBox_18.value = "value1";
						(function(comboBox_18){
							comboBox_18.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_18);
						container.addChild(comboBox_18, {
							"colIndex": 5,
							"rowIndex": 5
						});
						var comboBox_19 = new cpr.controls.ComboBox("cmb20");
						comboBox_19.value = "value1";
						(function(comboBox_19){
							comboBox_19.addItem(new cpr.controls.Item("선택", "value1"));
						})(comboBox_19);
						container.addChild(comboBox_19, {
							"colIndex": 5,
							"rowIndex": 8
						});
						var dateInput_11 = new cpr.controls.DateInput("dti15");
						dateInput_11.value = "99991231";
						container.addChild(dateInput_11, {
							"colIndex": 4,
							"rowIndex": 6
						});
						var dateInput_12 = new cpr.controls.DateInput("dti17");
						dateInput_12.value = "";
						container.addChild(dateInput_12, {
							"colIndex": 4,
							"rowIndex": 2
						});
						var dateInput_13 = new cpr.controls.DateInput("dti18");
						dateInput_13.value = "";
						container.addChild(dateInput_13, {
							"colIndex": 3,
							"rowIndex": 2
						});
						var dateInput_14 = new cpr.controls.DateInput("dti19");
						dateInput_14.value = "";
						container.addChild(dateInput_14, {
							"colIndex": 3,
							"rowIndex": 3
						});
						var dateInput_15 = new cpr.controls.DateInput("dti20");
						dateInput_15.value = "";
						container.addChild(dateInput_15, {
							"colIndex": 3,
							"rowIndex": 4
						});
						var dateInput_16 = new cpr.controls.DateInput("dti21");
						dateInput_16.value = "";
						container.addChild(dateInput_16, {
							"colIndex": 4,
							"rowIndex": 5
						});
						var dateInput_17 = new cpr.controls.DateInput("dti22");
						dateInput_17.value = "";
						container.addChild(dateInput_17, {
							"colIndex": 4,
							"rowIndex": 4
						});
						var dateInput_18 = new cpr.controls.DateInput("dti23");
						dateInput_18.value = "";
						container.addChild(dateInput_18, {
							"colIndex": 4,
							"rowIndex": 3
						});
						var dateInput_19 = new cpr.controls.DateInput("dti24");
						dateInput_19.value = "";
						container.addChild(dateInput_19, {
							"colIndex": 3,
							"rowIndex": 5
						});
						var dateInput_20 = new cpr.controls.DateInput("dti25");
						dateInput_20.value = "";
						container.addChild(dateInput_20, {
							"colIndex": 4,
							"rowIndex": 8
						});
						var dateInput_21 = new cpr.controls.DateInput("dti26");
						dateInput_21.value = "";
						container.addChild(dateInput_21, {
							"colIndex": 3,
							"rowIndex": 8
						});
						var dateInput_22 = new cpr.controls.DateInput("dti14");
						dateInput_22.value = "99991231";
						container.addChild(dateInput_22, {
							"colIndex": 4,
							"rowIndex": 9
						});
						var dateInput_23 = new cpr.controls.DateInput("dti13");
						dateInput_23.value = "20190422";
						container.addChild(dateInput_23, {
							"colIndex": 4,
							"rowIndex": 7
						});
						var dateInput_24 = new cpr.controls.DateInput("dti28");
						dateInput_24.value = "";
						container.addChild(dateInput_24, {
							"colIndex": 7,
							"rowIndex": 2
						});
						var dateInput_25 = new cpr.controls.DateInput("dti29");
						dateInput_25.value = "";
						container.addChild(dateInput_25, {
							"colIndex": 7,
							"rowIndex": 3
						});
						var dateInput_26 = new cpr.controls.DateInput("dti32");
						dateInput_26.value = "";
						container.addChild(dateInput_26, {
							"colIndex": 7,
							"rowIndex": 8
						});
						var dateInput_27 = new cpr.controls.DateInput("dti30");
						dateInput_27.value = "";
						container.addChild(dateInput_27, {
							"colIndex": 7,
							"rowIndex": 5
						});
						var dateInput_28 = new cpr.controls.DateInput("dti33");
						dateInput_28.value = "";
						container.addChild(dateInput_28, {
							"colIndex": 7,
							"rowIndex": 4
						});
						var dateInput_29 = new cpr.controls.DateInput("dti31");
						dateInput_29.value = "";
						container.addChild(dateInput_29, {
							"colIndex": 7,
							"rowIndex": 7
						});
						var dateInput_30 = new cpr.controls.DateInput("dti34");
						dateInput_30.value = "";
						container.addChild(dateInput_30, {
							"colIndex": 7,
							"rowIndex": 9
						});
						var dateInput_31 = new cpr.controls.DateInput("dti35");
						dateInput_31.value = "";
						container.addChild(dateInput_31, {
							"colIndex": 8,
							"rowIndex": 9
						});
						var dateInput_32 = new cpr.controls.DateInput("dti36");
						dateInput_32.value = "";
						container.addChild(dateInput_32, {
							"colIndex": 8,
							"rowIndex": 6
						});
						var dateInput_33 = new cpr.controls.DateInput("dti39");
						dateInput_33.value = "";
						container.addChild(dateInput_33, {
							"colIndex": 8,
							"rowIndex": 3
						});
						var dateInput_34 = new cpr.controls.DateInput("dti40");
						dateInput_34.value = "";
						container.addChild(dateInput_34, {
							"colIndex": 8,
							"rowIndex": 2
						});
						var dateInput_35 = new cpr.controls.DateInput("dti37");
						dateInput_35.value = "";
						container.addChild(dateInput_35, {
							"colIndex": 8,
							"rowIndex": 5
						});
						var dateInput_36 = new cpr.controls.DateInput("dti41");
						dateInput_36.value = "";
						container.addChild(dateInput_36, {
							"colIndex": 8,
							"rowIndex": 4
						});
						var dateInput_37 = new cpr.controls.DateInput("dti42");
						dateInput_37.value = "";
						container.addChild(dateInput_37, {
							"colIndex": 8,
							"rowIndex": 7
						});
						var dateInput_38 = new cpr.controls.DateInput("dti43");
						dateInput_38.value = "";
						container.addChild(dateInput_38, {
							"colIndex": 8,
							"rowIndex": 8
						});
						var dateInput_39 = new cpr.controls.DateInput("dti44");
						dateInput_39.value = "";
						container.addChild(dateInput_39, {
							"colIndex": 7,
							"rowIndex": 6
						});
						var group_15 = new cpr.controls.Container();
						group_15.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "3px",
							"border-bottom-color" : "blue",
							"border-left-style" : "solid",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "blue",
							"border-top-color" : "blue",
							"border-bottom-style" : "solid",
							"border-right-color" : "blue",
							"border-left-width" : "3px",
							"border-top-style" : "solid"
						});
						var formLayout_8 = new cpr.controls.layouts.FormLayout();
						formLayout_8.scrollable = false;
						formLayout_8.horizontalSpacing = "11px";
						formLayout_8.verticalSpacing = "5px";
						formLayout_8.setColumns(["110px", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr"]);
						formLayout_8.setUseColumnShade(0, true);
						formLayout_8.setColumnAutoSizing(0, true);
						formLayout_8.setColumnMinWidth(6, 50);
						formLayout_8.setRows(["26px"]);
						group_15.setLayout(formLayout_8);
						(function(container){
							var inputBox_26 = new cpr.controls.InputBox("ipb10");
							inputBox_26.value = "000111";
							container.addChild(inputBox_26, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var inputBox_27 = new cpr.controls.InputBox("ipb11");
							inputBox_27.value = "노*지점";
							container.addChild(inputBox_27, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var dateInput_40 = new cpr.controls.DateInput("dti8");
							dateInput_40.value = "20180703";
							container.addChild(dateInput_40, {
								"colIndex": 3,
								"rowIndex": 0
							});
							var dateInput_41 = new cpr.controls.DateInput("dti16");
							dateInput_41.value = "99991231";
							container.addChild(dateInput_41, {
								"colIndex": 4,
								"rowIndex": 0
							});
							var comboBox_20 = new cpr.controls.ComboBox("cmb12");
							comboBox_20.value = "value1";
							(function(comboBox_20){
								comboBox_20.addItem(new cpr.controls.Item("선택", "value1"));
							})(comboBox_20);
							container.addChild(comboBox_20, {
								"colIndex": 5,
								"rowIndex": 0
							});
							var searchInput_12 = new cpr.controls.SearchInput();
							container.addChild(searchInput_12, {
								"colIndex": 6,
								"rowIndex": 0
							});
							var dateInput_42 = new cpr.controls.DateInput("dti27");
							dateInput_42.value = "";
							container.addChild(dateInput_42, {
								"colIndex": 7,
								"rowIndex": 0
							});
							var dateInput_43 = new cpr.controls.DateInput("dti38");
							dateInput_43.value = "";
							container.addChild(dateInput_43, {
								"colIndex": 8,
								"rowIndex": 0
							});
							var output_48 = new cpr.controls.Output();
							output_48.value = "소속";
							output_48.style.setClasses(["label"]);
							container.addChild(output_48, {
								"colIndex": 0,
								"rowIndex": 0
							});
						})(group_15);
						container.addChild(group_15, {
							"colIndex": 0,
							"rowIndex": 1,
							"colSpan": 9,
							"rowSpan": 1
						});
					})(group_14);
					container.addChild(group_14, {
						"autoSize": "height",
						"width": "1600px",
						"height": "316px"
					});
					var group_16 = new cpr.controls.Container("grp1");
					group_16.style.setClasses(["form-box"]);
					var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_7.scrollable = false;
					verticalLayout_7.spacing = 8;
					group_16.setLayout(verticalLayout_7);
					(function(container){
						var group_17 = new cpr.controls.Container("grp2");
						group_17.style.setClasses(["form-box"]);
						var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_8.scrollable = false;
						verticalLayout_8.spacing = 8;
						group_17.setLayout(verticalLayout_8);
						(function(container){
							var group_18 = new cpr.controls.Container();
							group_18.style.setClasses(["form-normal"]);
							var formLayout_9 = new cpr.controls.layouts.FormLayout();
							formLayout_9.scrollable = false;
							formLayout_9.topMargin = "2px";
							formLayout_9.rightMargin = "5px";
							formLayout_9.bottomMargin = "2px";
							formLayout_9.leftMargin = "5px";
							formLayout_9.horizontalSpacing = "11px";
							formLayout_9.verticalSpacing = "5px";
							formLayout_9.horizontalSeparatorWidth = 1;
							formLayout_9.verticalSeparatorWidth = 1;
							formLayout_9.setColumns(["150px", "3fr", "230px", "1fr"]);
							formLayout_9.setUseColumnShade(0, true);
							formLayout_9.setUseColumnShade(2, true);
							formLayout_9.setColumnAutoSizing(0, true);
							formLayout_9.setColumnAutoSizing(2, true);
							formLayout_9.setRows(["26px"]);
							group_18.setLayout(formLayout_9);
							(function(container){
								var output_49 = new cpr.controls.Output();
								output_49.value = "흡수점포";
								output_49.style.setClasses(["label"]);
								container.addChild(output_49, {
									"colIndex": 0,
									"rowIndex": 0,
									"colSpan": 1,
									"rowSpan": 1
								});
								var group_19 = new cpr.controls.Container();
								group_19.childCombinatorClass = "first-control-spacing";
								group_19.style.setClasses(["form-inside"]);
								var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
								flowLayout_3.scrollable = false;
								flowLayout_3.horizontalSpacing = 20;
								flowLayout_3.verticalSpacing = 2;
								group_19.setLayout(flowLayout_3);
								(function(container){
									var group_20 = new cpr.controls.Container();
									var formLayout_10 = new cpr.controls.layouts.FormLayout();
									formLayout_10.scrollable = false;
									formLayout_10.topMargin = "0px";
									formLayout_10.rightMargin = "0px";
									formLayout_10.bottomMargin = "0px";
									formLayout_10.leftMargin = "0px";
									formLayout_10.horizontalSpacing = "5px";
									formLayout_10.verticalSpacing = "0px";
									formLayout_10.setColumns(["120px", "150px", "200px"]);
									formLayout_10.setUseColumnShade(0, true);
									formLayout_10.setRows(["1fr"]);
									group_20.setLayout(formLayout_10);
									(function(container){
										var output_50 = new cpr.controls.Output();
										output_50.value = "대표흡수점포";
										output_50.style.setClasses(["label"]);
										container.addChild(output_50, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var inputBox_28 = new cpr.controls.InputBox("ipb19");
										inputBox_28.value = "";
										container.addChild(inputBox_28, {
											"colIndex": 1,
											"rowIndex": 0
										});
										var inputBox_29 = new cpr.controls.InputBox("ipb20");
										inputBox_29.value = "";
										container.addChild(inputBox_29, {
											"colIndex": 2,
											"rowIndex": 0
										});
									})(group_20);
									container.addChild(group_20, {
										"autoSize": "width",
										"width": "500px",
										"height": "26px"
									});
									var inputBox_30 = new cpr.controls.InputBox("ipb22");
									inputBox_30.value = "";
									container.addChild(inputBox_30, {
										"autoSize": "none",
										"width": "185px",
										"height": "26px"
									});
								})(group_19);
								container.addChild(group_19, {
									"colIndex": 1,
									"rowIndex": 0,
									"width": 203,
									"height": 25
								});
								var output_51 = new cpr.controls.Output();
								output_51.value = "점포등급";
								output_51.style.setClasses(["label"]);
								container.addChild(output_51, {
									"colIndex": 2,
									"rowIndex": 0
								});
								var numberEditor_1 = new cpr.controls.NumberEditor("nbe1");
								numberEditor_1.value = "5";
								container.addChild(numberEditor_1, {
									"colIndex": 3,
									"rowIndex": 0
								});
							})(group_18);
							container.addChild(group_18, {
								"autoSize": "height",
								"width": "1366px",
								"height": "33px"
							});
						})(group_17);
						container.addChild(group_17, {
							"autoSize": "height",
							"width": "1560px",
							"height": "38px"
						});
					})(group_16);
					container.addChild(group_16, {
						"autoSize": "height",
						"width": "1600px",
						"height": "38px"
					});
					var group_21 = new cpr.controls.Container();
					group_21.style.setClasses(["commentary"]);
					var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_9.scrollable = false;
					verticalLayout_9.spacing = 8;
					verticalLayout_9.leftMargin = 10;
					verticalLayout_9.rightMargin = 10;
					verticalLayout_9.topMargin = 10;
					verticalLayout_9.bottomMargin = 10;
					group_21.setLayout(verticalLayout_9);
					(function(container){
						var output_52 = new cpr.controls.Output();
						output_52.value = "- '조직관계' 항목의 추가, 변경은 '관계점포'를 먼저 선택하면 해당 항목이 활성화 되어 입력가능합니다 ('일반변경' 및 '점포폐쇄-대표흡수점포' 업무 수행시)\r\n- '점포폐쇄' 작업시, '조직관계'의 '흡수-점포' 설정하면 해당 '흡수-점포'가 자동으로 '대표 흡수 점포'로 셋팅 됩니다.\r\n- '점포신설' 시 조직번호는 직접 입력 하거나 입력하지 않으면 자동채번으로 반영됩니다.";
						container.addChild(output_52, {
							"autoSize": "height",
							"width": "904px",
							"height": "24px"
						});
					})(group_21);
					container.addChild(group_21, {
						"autoSize": "height",
						"width": "1560px",
						"height": "46px"
					});
					var group_22 = new cpr.controls.Container();
					group_22.style.setClasses(["button-table-area"]);
					var formLayout_11 = new cpr.controls.layouts.FormLayout();
					formLayout_11.scrollable = false;
					formLayout_11.topMargin = "0px";
					formLayout_11.rightMargin = "0px";
					formLayout_11.bottomMargin = "0px";
					formLayout_11.leftMargin = "0px";
					formLayout_11.horizontalSpacing = "0px";
					formLayout_11.verticalSpacing = "0px";
					formLayout_11.setColumns(["1fr", "43px", "1fr"]);
					formLayout_11.setColumnAutoSizing(1, true);
					formLayout_11.setRows(["1fr"]);
					group_22.setLayout(formLayout_11);
					(function(container){
						var group_23 = new cpr.controls.Container("grp6");
						group_23.style.setClasses(["button-table-bottom-left-area"]);
						var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
						flowLayout_4.scrollable = false;
						flowLayout_4.horizontalSpacing = 10;
						flowLayout_4.verticalSpacing = 0;
						flowLayout_4.lineWrap = false;
						group_23.setLayout(flowLayout_4);
						(function(container){
							var button_5 = new cpr.controls.Button("btn1");
							button_5.value = "기본사항조";
							button_5.style.setClasses(["btn-primary04", "btn-md"]);
							container.addChild(button_5, {
								"autoSize": "width",
								"width": "90px",
								"height": "30px"
							});
							var button_6 = new cpr.controls.Button("btn2");
							button_6.value = "조직건재변경";
							button_6.style.setClasses(["btn-primary04", "btn-md"]);
							container.addChild(button_6, {
								"autoSize": "width",
								"width": "90px",
								"height": "30px"
							});
						})(group_23);
						container.addChild(group_23, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_24 = new cpr.controls.Container("grp7");
						group_24.style.setClasses(["button-table-bottom-center-area"]);
						var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
						flowLayout_5.scrollable = false;
						flowLayout_5.horizontalSpacing = 10;
						flowLayout_5.verticalSpacing = 0;
						flowLayout_5.horizontalAlign = "center";
						group_24.setLayout(flowLayout_5);
						container.addChild(group_24, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var group_25 = new cpr.controls.Container("grp8");
						group_25.style.setClasses(["button-table-bottom-right-area"]);
						var flowLayout_6 = new cpr.controls.layouts.FlowLayout();
						flowLayout_6.scrollable = false;
						flowLayout_6.horizontalSpacing = 10;
						flowLayout_6.verticalSpacing = 0;
						flowLayout_6.horizontalAlign = "right";
						flowLayout_6.lineWrap = false;
						group_25.setLayout(flowLayout_6);
						(function(container){
							var button_7 = new cpr.controls.Button("btn4");
							button_7.value = "저장";
							button_7.style.setClasses(["btn-primary03", "btn-md"]);
							container.addChild(button_7, {
								"autoSize": "width",
								"width": "60px",
								"height": "30px"
							});
						})(group_25);
						container.addChild(group_25, {
							"colIndex": 2,
							"rowIndex": 0
						});
					})(group_22);
					container.addChild(group_22, {
						"autoSize": "height",
						"width": "1560px",
						"height": "30px"
					});
				})(group_13);
				container.addChild(group_13, {
					"autoSize": "height",
					"width": "1560px",
					"height": "425px"
				});
			})(group_7);
			container.addChild(group_7, {
				"autoSize": "height",
				"width": "1366px",
				"height": "727px"
			});
		}
	});
	app.title = "기본사항처리";
	cpr.core.Platform.INSTANCE.register(app);
})();
