/*
 * App URI: sfa/영업/SLFD01M2
 * Source Location: sfa/영업/SLFD01M2.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("sfa/영업/SLFD01M2", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * ${filename}
			 * Created at ${date} ${time}.
			 *
			 * @author ${user}
			 ************************************************/

			/*
			 * "이전" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var button = e.control;
				//화면이동(현재 화면에서 리로드)
				var host = app.getHost(); // 부모 임베디드 앱
				cpr.core.App.load("sfa/영업/SLFC03M0", function(loadedApp) {
				    if (loadedApp) {
				        host.app = loadedApp;
				        host.initValue = {
				            "param": "param"
				        }
				    }
				});
			}

			/*
			 * "다음" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				var button = e.control;
				//화면이동(현재 화면에서 리로드)
				var host = app.getHost(); // 부모 임베디드 앱
				cpr.core.App.load("sfa/영업/SLFE04M0", function(loadedApp) {
				    if (loadedApp) {
				        host.app = loadedApp;
				        host.initValue = {
				            "param": "param"
				        }
				    }
				});
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column12"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"}
				],
				"rows": [
					{"column1": "000000", "column12": "전사", "column2": "1731109", "column3": "1587983", "column4": "1265977", "column5": "111942", "column6": "1377919", "column7": "556", "column8": "3535", "column9": "205973", "column10": "0", "column11": "12181"},
					{"column1": "000000", "column12": "전사", "column2": "226888458", "column3": "206188874", "column4": "152952504", "column5": "14827567", "column6": "167780072", "column7": "94824", "column8": "628809", "column9": "37685169", "column10": "4832690", "column11": "8876280"},
					{"column1": "000803", "column12": "TM채널", "column2": "482293", "column3": "455373", "column4": "392903", "column5": "25109", "column6": "418012", "column7": "67", "column8": "1107", "column9": "36187", "column10": "0", "column11": "2970"},
					{"column1": "000803", "column12": "TM채널", "column2": "36192759", "column3": "33033134", "column4": "24358064", "column5": "1697270", "column6": "26055334", "column7": "12277", "column8": "75899", "column9": "6889623", "column10": "565515", "column11": "503836"},
					{"column1": "000502", "column12": "TM**본부", "column2": "476890", "column3": "450277", "column4": "388002", "column5": "24935", "column6": "412937", "column7": "67", "column8": "1107", "column9": "36166", "column10": "0", "column11": "2959"},
					{"column1": "000502", "column12": "TM**본부", "column2": "36015739", "column3": "32858971", "column4": "24193987", "column5": "1692957", "column6": "25886945", "column7": "12277", "column8": "75899", "column9": "6883848", "column10": "559635", "column11": "503779"},
					{"column1": "000551", "column12": "행*지점", "column2": "26804", "column3": "26740", "column4": "23022", "column5": "1697", "column6": "24719", "column7": "5", "column8": "47", "column9": "1969", "column10": "0", "column11": "274"},
					{"column1": "000551", "column12": "행*지점", "column2": "2335310", "column3": "2160363", "column4": "1666720", "column5": "146820", "column6": "1813541", "column7": "685", "column8": "2553", "column9": "343582", "column10": "9810", "column11": "23769"},
					{"column1": "000552", "column12": "보*지점", "column2": "40141", "column3": "41105", "column4": "35246", "column5": "2495", "column6": "37741", "column7": "5", "column8": "37", "column9": "3322", "column10": "0", "column11": "400"},
					{"column1": "000552", "column12": "보*지점", "column2": "3465622", "column3": "3233458", "column4": "2424510", "column5": "182138", "column6": "2606648", "column7": "907", "column8": "2332", "column9": "623570", "column10": "37156", "column11": "38020"},
					{"column1": "000992", "column12": "미*지점", "column2": "84802", "column3": "82700", "column4": "70468", "column5": "4656", "column6": "75124", "column7": "11", "column8": "84", "column9": "7481", "column10": "0", "column11": "308"},
					{"column1": "000992", "column12": "미*지점", "column2": "84802", "column3": "82700", "column4": "70468", "column5": "4656", "column6": "75124", "column7": "11", "column8": "84", "column9": "7481", "column10": "0", "column11": "308"},
					{"column1": "000997", "column12": "우*지점", "column2": "0", "column3": "0", "column4": "0", "column5": "0", "column6": "0", "column7": "0", "column8": "0", "column9": "0", "column10": "0", "column11": "0"},
					{"column1": "000997", "column12": "우*지점", "column2": "0", "column3": "0", "column4": "0", "column5": "0", "column6": "0", "column7": "0", "column8": "0", "column9": "0", "column10": "0", "column11": "0"},
					{"column1": "000893", "column12": "VIP**지점", "column2": "36694", "column3": "36941", "column4": "30566", "column5": "1768", "column6": "32334", "column7": "8", "column8": "0", "column9": "4599", "column10": "0", "column11": "697"},
					{"column1": "000893", "column12": "VIP**지점", "column2": "3139194", "column3": "2964486", "column4": "2055576", "column5": "120997", "column6": "2176574", "column7": "2415", "column8": "0", "column9": "785496", "column10": "69422", "column11": "205695"},
					{"column1": "000899", "column12": "스타**지점", "column2": "18276", "column3": "18651", "column4": "15662", "column5": "954", "column6": "16616", "column7": "4", "column8": "8", "column9": "2023", "column10": "0", "column11": "38"},
					{"column1": "000899", "column12": "스타**지점", "column2": "1645977", "column3": "1587128", "column4": "1142506", "column5": "67041", "column6": "1209547", "column7": "438", "column8": "1239", "column9": "375903", "column10": "17600", "column11": "11880"},
					{"column1": "000849", "column12": "광주**지점", "column2": "21152", "column3": "21091", "column4": "17866", "column5": "957", "column6": "18823", "column7": "0", "column8": "0", "column9": "2268", "column10": "0", "column11": "437"},
					{"column1": "000849", "column12": "광주**지점", "column2": "1775002", "column3": "1662364", "column4": "1214795", "column5": "61792", "column6": "1276587", "column7": "0", "column8": "0", "column9": "385776", "column10": "39945", "column11": "107503"},
					{"column1": "000895", "column12": "부산**지점", "column2": "24064", "column3": "23461", "column4": "20029", "column5": "1092", "column6": "21121", "column7": "6", "column8": "0", "column9": "2334", "column10": "0", "column11": "7"},
					{"column1": "000895", "column12": "부산**지점", "column2": "2130220", "column3": "1953256", "column4": "1387426", "column5": "77388", "column6": "1464814", "column7": "791", "column8": "0", "column9": "487649", "column10": "30200", "column11": "383"}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 3160px)", "Hlicp-WIDE");
			app.supportMedia("all and (min-width: 1600px) and (max-width: 3159px)", "Hlicp-FULL");
			app.supportMedia("all and (min-width: 790px) and (max-width: 1599px)", "Hlicp-DIV");
			app.supportMedia("all and (max-width: 789px)", "Hlicp-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["grid-window-body"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 0;
			verticalLayout_1.leftMargin = 20;
			verticalLayout_1.rightMargin = 20;
			verticalLayout_1.topMargin = 20;
			verticalLayout_1.bottomMargin = 10;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpAppTitle");
			group_1.style.setClasses(["app-title"]);
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr", "1fr"]);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output("optTitle2");
				output_1.value = "조직별계속보험료";
				output_1.style.setClasses(["navi-left"]);
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_2 = new cpr.controls.Container("grpNavi2");
				group_2.style.setClasses(["breadcrumbs"]);
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 5;
				flowLayout_1.verticalSpacing = 0;
				flowLayout_1.horizontalAlign = "right";
				flowLayout_1.verticalAlign = "middle";
				flowLayout_1.lineWrap = false;
				group_2.setLayout(flowLayout_1);
				(function(container){
					var button_1 = new cpr.controls.Button();
					button_1.value = "이전";
					button_1.style.setClasses(["btn-primary04", "btn-md"]);
					if(typeof onButtonClick == "function") {
						button_1.addEventListener("click", onButtonClick);
					}
					container.addChild(button_1, {
						"autoSize": "width",
						"width": "49px",
						"height": "26px"
					});
					var button_2 = new cpr.controls.Button();
					button_2.value = "다음";
					button_2.style.setClasses(["btn-primary04", "btn-md"]);
					if(typeof onButtonClick2 == "function") {
						button_2.addEventListener("click", onButtonClick2);
					}
					container.addChild(button_2, {
						"autoSize": "width",
						"width": "49px",
						"height": "26px"
					});
				})(group_2);
				container.addChild(group_2, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1600px",
				"height": "35px"
			});
			
			var group_3 = new cpr.controls.Container("grpBody");
			group_3.style.setClasses(["grid-content-body"]);
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 7;
			group_3.setLayout(verticalLayout_2);
			(function(container){
				var group_4 = new cpr.controls.Container("grpTopSearch");
				var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_3.spacing = 12;
				group_4.setLayout(verticalLayout_3);
				(function(container){
					var group_5 = new cpr.controls.Container();
					group_5.style.setClasses(["search-box"]);
					var formLayout_2 = new cpr.controls.layouts.FormLayout();
					formLayout_2.scrollable = false;
					formLayout_2.topMargin = "6px";
					formLayout_2.rightMargin = "20px";
					formLayout_2.bottomMargin = "6px";
					formLayout_2.leftMargin = "20px";
					formLayout_2.horizontalSpacing = "20px";
					formLayout_2.verticalSpacing = "8px";
					formLayout_2.setColumns(["0px", "1fr", "0px", "1fr", "50px", "1fr", "50px", "1fr", "63px"]);
					formLayout_2.setColumnAutoSizing(0, true);
					formLayout_2.setColumnAutoSizing(2, true);
					formLayout_2.setColumnAutoSizing(4, true);
					formLayout_2.setColumnAutoSizing(6, true);
					formLayout_2.setColumnAutoSizing(8, true);
					formLayout_2.setRows(["26px"]);
					group_5.setLayout(formLayout_2);
					(function(container){
						var output_2 = new cpr.controls.Output();
						output_2.value = "조회구분";
						output_2.style.setClasses(["label", "required"]);
						container.addChild(output_2, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_6 = new cpr.controls.Container();
						group_6.style.setClasses(["form-inside"]);
						var formLayout_3 = new cpr.controls.layouts.FormLayout();
						formLayout_3.scrollable = false;
						formLayout_3.topMargin = "0px";
						formLayout_3.rightMargin = "0px";
						formLayout_3.bottomMargin = "0px";
						formLayout_3.leftMargin = "0px";
						formLayout_3.horizontalSpacing = "5px";
						formLayout_3.verticalSpacing = "5px";
						formLayout_3.setColumns(["120px", "1fr"]);
						formLayout_3.setRows(["1fr"]);
						group_6.setLayout(formLayout_3);
						(function(container){
							var searchInput_1 = new cpr.controls.SearchInput();
							searchInput_1.value = "005553";
							searchInput_1.style.css({
								"border-right-style" : "dashed",
								"border-top-width" : "3px",
								"border-bottom-color" : "red",
								"border-left-style" : "dashed",
								"border-right-width" : "3px",
								"border-bottom-width" : "3px",
								"border-left-color" : "red",
								"border-top-color" : "red",
								"border-bottom-style" : "dashed",
								"border-right-color" : "red",
								"border-left-width" : "3px",
								"border-top-style" : "dashed"
							});
							container.addChild(searchInput_1, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var inputBox_1 = new cpr.controls.InputBox("ipb2");
							inputBox_1.value = "서*1";
							container.addChild(inputBox_1, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_6);
						container.addChild(group_6, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var output_3 = new cpr.controls.Output();
						output_3.value = "마감년월";
						output_3.style.setClasses(["label", "required"]);
						container.addChild(output_3, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var dateInput_1 = new cpr.controls.DateInput("dti1");
						dateInput_1.value = "202404";
						dateInput_1.calendarType = "yearmonth";
						dateInput_1.mask = "YYYY-MM";
						dateInput_1.format = "YYYYMM";
						dateInput_1.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						container.addChild(dateInput_1, {
							"colIndex": 3,
							"rowIndex": 0
						});
						var output_4 = new cpr.controls.Output();
						output_4.value = "모집구분";
						output_4.style.setClasses(["label", "required"]);
						container.addChild(output_4, {
							"colIndex": 4,
							"rowIndex": 0
						});
						var radioButton_1 = new cpr.controls.RadioButton("rdb1");
						radioButton_1.value = "value1";
						radioButton_1.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						(function(radioButton_1){
							radioButton_1.addItem(new cpr.controls.Item("일반모집", "value1"));
							radioButton_1.addItem(new cpr.controls.Item("CAP계약", "value2"));
						})(radioButton_1);
						container.addChild(radioButton_1, {
							"colIndex": 5,
							"rowIndex": 0
						});
						var output_5 = new cpr.controls.Output();
						output_5.value = "지점구분";
						output_5.style.setClasses(["label", "required"]);
						container.addChild(output_5, {
							"colIndex": 6,
							"rowIndex": 0
						});
						var radioButton_2 = new cpr.controls.RadioButton("rdb3");
						radioButton_2.value = "value1";
						radioButton_2.style.css({
							"border-right-style" : "dashed",
							"border-top-width" : "3px",
							"border-bottom-color" : "red",
							"border-left-style" : "dashed",
							"border-right-width" : "3px",
							"border-bottom-width" : "3px",
							"border-left-color" : "red",
							"border-top-color" : "red",
							"border-bottom-style" : "dashed",
							"border-right-color" : "red",
							"border-left-width" : "3px",
							"border-top-style" : "dashed"
						});
						(function(radioButton_2){
							radioButton_2.addItem(new cpr.controls.Item("소속별", "value1"));
							radioButton_2.addItem(new cpr.controls.Item("관리지점별", "value2"));
						})(radioButton_2);
						container.addChild(radioButton_2, {
							"colIndex": 7,
							"rowIndex": 0
						});
						var group_7 = new cpr.controls.Container();
						group_7.style.setClasses(["btn-flow-area"]);
						var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
						flowLayout_2.scrollable = false;
						flowLayout_2.verticalSpacing = 0;
						flowLayout_2.horizontalAlign = "right";
						flowLayout_2.lineWrap = false;
						flowLayout_2.leftMargin = 20;
						group_7.setLayout(flowLayout_2);
						(function(container){
							var button_3 = new cpr.controls.Button();
							button_3.value = "조회";
							button_3.style.setClasses(["btn-search"]);
							container.addChild(button_3, {
								"width": "49px",
								"height": "26px"
							});
							var button_4 = new cpr.controls.Button();
							button_4.value = "";
							button_4.style.setClasses(["btn-reset"]);
							container.addChild(button_4, {
								"width": "26px",
								"height": "26px"
							});
						})(group_7);
						container.addChild(group_7, {
							"colIndex": 8,
							"rowIndex": 0,
							"colSpan": 1,
							"rowSpan": 1,
							"verticalAlign": "center",
							"height": 26
						});
					})(group_5);
					container.addChild(group_5, {
						"autoSize": "none",
						"width": "4236px",
						"height": "40px"
					});
				})(group_4);
				container.addChild(group_4, {
					"autoSize": "height",
					"width": "4236px",
					"height": "40px"
				});
				var group_8 = new cpr.controls.Container();
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 8;
				group_8.setLayout(verticalLayout_4);
				(function(container){
					var group_9 = new cpr.controls.Container("grpBodyGroundGrid");
					group_9.style.setClasses(["grid-box"]);
					var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_5.spacing = 8;
					group_9.setLayout(verticalLayout_5);
					(function(container){
						var grid_1 = new cpr.controls.Grid("grd1");
						grid_1.readOnly = true;
						grid_1.init({
							"dataSet": app.lookup("ds1"),
							"columnMovable": true,
							"resizableColumns": "all",
							"suppressedCellType": "merged",
							"columns": [
								{"width": "100px"},
								{"width": "150px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"},
								{"width": "100px"}
							],
							"header": {
								"rows": [
									{"height": "31px"},
									{"height": "31px"}
								],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 2, "colSpan": 2},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column1";
											cell.text = "소속";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column2";
											cell.text = "확정보험료";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column3";
											cell.text = "총계속";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 4},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column4";
											cell.text = "해당";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 5},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column5";
											cell.text = "유예";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 6},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column6";
											cell.text = "합계";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 7},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column7";
											cell.text = "비월납";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 8},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column8";
											cell.text = "부활";
										}
									},
									{
										"constraint": {"rowIndex": 1, "colIndex": 9},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column9";
											cell.text = "기타";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column10";
											cell.text = "추가납입";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 11, "rowSpan": 2, "colSpan": 1},
										"configurator": function(cell){
											cell.filterable = false;
											cell.sortable = false;
											cell.targetColumnName = "column11";
											cell.text = "선납";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4, "rowSpan": 1, "colSpan": 3},
										"configurator": function(cell){
											cell.text = "월납계속";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7, "rowSpan": 1, "colSpan": 3},
										"configurator": function(cell){
											cell.text = "기타계속";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "31px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnName = "column1";
											cell.control = (function(){
												var output_6 = new cpr.controls.Output();
												output_6.bind("value").toDataColumn("column1");
												return output_6;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "column12";
											cell.suppressible = true;
											cell.control = (function(){
												var output_7 = new cpr.controls.Output();
												output_7.style.setClasses(["text-left"]);
												output_7.bind("value").toDataColumn("column12");
												return output_7;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "column2";
											cell.control = (function(){
												var output_8 = new cpr.controls.Output();
												output_8.value = "0";
												output_8.dataType = "number";
												output_8.format = "s#,##0";
												output_8.style.setClasses(["text-right"]);
												output_8.bind("value").toDataColumn("column2");
												return output_8;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "column3";
											cell.control = (function(){
												var output_9 = new cpr.controls.Output();
												output_9.value = "0";
												output_9.dataType = "number";
												output_9.format = "s#,##0";
												output_9.style.setClasses(["text-right"]);
												output_9.bind("value").toDataColumn("column3");
												return output_9;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 4},
										"configurator": function(cell){
											cell.columnName = "column4";
											cell.control = (function(){
												var output_10 = new cpr.controls.Output();
												output_10.value = "0";
												output_10.dataType = "number";
												output_10.format = "s#,##0";
												output_10.style.setClasses(["text-right"]);
												output_10.bind("value").toDataColumn("column4");
												return output_10;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 5},
										"configurator": function(cell){
											cell.columnName = "column5";
											cell.control = (function(){
												var output_11 = new cpr.controls.Output();
												output_11.value = "0";
												output_11.dataType = "number";
												output_11.format = "s#,##0";
												output_11.style.setClasses(["text-right"]);
												output_11.bind("value").toDataColumn("column5");
												return output_11;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 6},
										"configurator": function(cell){
											cell.columnName = "column6";
											cell.control = (function(){
												var output_12 = new cpr.controls.Output();
												output_12.value = "0";
												output_12.dataType = "number";
												output_12.format = "s#,##0";
												output_12.style.setClasses(["text-right"]);
												output_12.bind("value").toDataColumn("column6");
												return output_12;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 7},
										"configurator": function(cell){
											cell.columnName = "column7";
											cell.control = (function(){
												var output_13 = new cpr.controls.Output();
												output_13.value = "0";
												output_13.dataType = "number";
												output_13.format = "s#,##0";
												output_13.style.setClasses(["text-right"]);
												output_13.bind("value").toDataColumn("column7");
												return output_13;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 8},
										"configurator": function(cell){
											cell.columnName = "column8";
											cell.control = (function(){
												var output_14 = new cpr.controls.Output();
												output_14.value = "0";
												output_14.dataType = "number";
												output_14.format = "s#,##0";
												output_14.style.setClasses(["text-right"]);
												output_14.bind("value").toDataColumn("column8");
												return output_14;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 9},
										"configurator": function(cell){
											cell.columnName = "column9";
											cell.control = (function(){
												var output_15 = new cpr.controls.Output();
												output_15.value = "0";
												output_15.dataType = "number";
												output_15.format = "s#,##0";
												output_15.style.setClasses(["text-right"]);
												output_15.bind("value").toDataColumn("column9");
												return output_15;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 10},
										"configurator": function(cell){
											cell.columnName = "column10";
											cell.control = (function(){
												var output_16 = new cpr.controls.Output();
												output_16.value = "0";
												output_16.dataType = "number";
												output_16.format = "s#,##0";
												output_16.style.setClasses(["text-right"]);
												output_16.bind("value").toDataColumn("column10");
												return output_16;
											})();
											cell.controlConstraint = {};
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 11},
										"configurator": function(cell){
											cell.columnName = "column11";
											cell.control = (function(){
												var output_17 = new cpr.controls.Output();
												output_17.value = "0";
												output_17.dataType = "number";
												output_17.format = "s#,##0";
												output_17.style.setClasses(["text-right"]);
												output_17.bind("value").toDataColumn("column11");
												return output_17;
											})();
											cell.controlConstraint = {};
										}
									}
								]
							}
						});
						grid_1.style.setClasses(["list-normal"]);
						container.addChild(grid_1, {
							"autoSize": "height",
							"width": "1052px",
							"height": "498px"
						});
					})(group_9);
					container.addChild(group_9, {
						"autoSize": "none",
						"width": "1600px",
						"height": "503px"
					});
					var group_10 = new cpr.controls.Container();
					group_10.style.setClasses(["button-table-area"]);
					var formLayout_4 = new cpr.controls.layouts.FormLayout();
					formLayout_4.scrollable = false;
					formLayout_4.topMargin = "0px";
					formLayout_4.rightMargin = "0px";
					formLayout_4.bottomMargin = "0px";
					formLayout_4.leftMargin = "0px";
					formLayout_4.horizontalSpacing = "0px";
					formLayout_4.verticalSpacing = "0px";
					formLayout_4.setColumns(["1fr", "43px", "1fr"]);
					formLayout_4.setColumnAutoSizing(1, true);
					formLayout_4.setRows(["1fr"]);
					group_10.setLayout(formLayout_4);
					(function(container){
						var group_11 = new cpr.controls.Container();
						group_11.style.setClasses(["button-table-bottom-left-area"]);
						var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
						flowLayout_3.scrollable = false;
						flowLayout_3.horizontalSpacing = 10;
						flowLayout_3.verticalSpacing = 0;
						flowLayout_3.lineWrap = false;
						group_11.setLayout(flowLayout_3);
						(function(container){
							var button_5 = new cpr.controls.Button("btn1");
							button_5.value = "엑셀다운로드";
							button_5.style.setClasses(["btn-secondary01", "btn-md"]);
							container.addChild(button_5, {
								"autoSize": "width",
								"width": "100px",
								"height": "30px"
							});
						})(group_11);
						container.addChild(group_11, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var group_12 = new cpr.controls.Container();
						group_12.style.setClasses(["button-table-bottom-center-area"]);
						var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
						flowLayout_4.scrollable = false;
						flowLayout_4.horizontalSpacing = 10;
						flowLayout_4.verticalSpacing = 0;
						flowLayout_4.horizontalAlign = "center";
						group_12.setLayout(flowLayout_4);
						container.addChild(group_12, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var group_13 = new cpr.controls.Container();
						group_13.style.setClasses(["button-table-bottom-right-area"]);
						var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
						flowLayout_5.scrollable = false;
						flowLayout_5.horizontalSpacing = 10;
						flowLayout_5.verticalSpacing = 0;
						flowLayout_5.horizontalAlign = "right";
						flowLayout_5.lineWrap = false;
						group_13.setLayout(flowLayout_5);
						(function(container){
							var button_6 = new cpr.controls.Button("btn2");
							button_6.value = "다음";
							button_6.style.setClasses(["btn-primary04", "btn-md"]);
							container.addChild(button_6, {
								"autoSize": "width",
								"width": "100px",
								"height": "30px"
							});
						})(group_13);
						container.addChild(group_13, {
							"colIndex": 2,
							"rowIndex": 0
						});
					})(group_10);
					container.addChild(group_10, {
						"autoSize": "height",
						"width": "1600px",
						"height": "30px"
					});
					var group_14 = new cpr.controls.Container();
					group_14.style.setClasses(["commentary"]);
					var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_6.scrollable = false;
					verticalLayout_6.spacing = 8;
					verticalLayout_6.leftMargin = 10;
					verticalLayout_6.rightMargin = 10;
					verticalLayout_6.topMargin = 10;
					verticalLayout_6.bottomMargin = 10;
					group_14.setLayout(verticalLayout_6);
					(function(container){
						var output_18 = new cpr.controls.Output();
						output_18.value = "단위: 건, 천원 / 더블클릭시 전사→채널→본부→지점→영업소 순으로 조회됩니다.";
						container.addChild(output_18, {
							"autoSize": "height",
							"width": "904px",
							"height": "20px"
						});
					})(group_14);
					container.addChild(group_14, {
						"autoSize": "height",
						"width": "1600px",
						"height": "42px"
					});
				})(group_8);
				container.addChild(group_8, {
					"autoSize": "height",
					"width": "1600px",
					"height": "591px"
				});
			})(group_3);
			container.addChild(group_3, {
				"autoSize": "height",
				"width": "4236px",
				"height": "638px"
			});
		}
	});
	app.title = "조직별계속보험료";
	cpr.core.Platform.INSTANCE.register(app);
})();
